Repository ziglang/zig, pull requests merged in 2019-10, with the labels that each got.

#3365 Fix pipe syscall for MIPS
  lib/std/os/linux.zig
  lib/std/os/linux/mipsel.zig
  lib/std/os/test.zig
Labels: arch-mips, os-linux, standard library

#3374 stage1: fix compile error on macOS Xcode 11.1
  src/dump_analysis.cpp
Labels: os-macos, stage1

#3368 fix: container member access `usingnamespace` decls fails
  src/ir.cpp
  test/stage1/behavior.zig
  test/stage1/behavior/bugs/3367.zig
Labels: stage1

#3398 Correct std.os.connect_async docs
  lib/std/os.zig
Labels: docs, standard library

#3389 Win32
  lib/std/special/compiler_rt.zig
  lib/std/special/compiler_rt/aulldiv.zig
  lib/std/special/compiler_rt/aullrem.zig
  lib/std/special/compiler_rt/extendXfYf2_test.zig
  lib/std/special/start_windows_tls.zig
  src/analyze.cpp
  src/codegen.cpp
Labels: arch-i386, os-windows

#3419 stage1: fix root top-level-struct typename
  src/analyze.cpp
  src/analyze.hpp
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#3426 stage1: fix ir_resolve_str() to return slice
  src/ir.cpp
  test/stage1/behavior.zig
  test/stage1/behavior/bugs/3384.zig
Labels: stage1

#3425 Extern unions should not trigger active field check
  src/ir.cpp
  test/stage1/behavior/union.zig
Labels: stage1

#3439 Add support for the statx syscall
  lib/std/os/bits/linux.zig
  lib/std/os/bits/linux/arm-eabi.zig
  lib/std/os/linux.zig
  lib/std/os/linux/test.zig
Labels: os-linux, standard library

#3437 Fix compilation of updateTimes on 32bit platforms
  lib/std/fs/file.zig
  lib/std/io/test.zig
Labels: standard library

#3464 UEFI improvements
  lib/std/os/uefi.zig
  lib/std/os/uefi/protocols/absolute_pointer_protocol.zig
  lib/std/os/uefi/protocols/edid_active_protocol.zig
  lib/std/os/uefi/protocols/edid_discovered_protocol.zig
  lib/std/os/uefi/protocols/edid_override_protocol.zig
  lib/std/os/uefi/protocols/graphics_output_protocol.zig
  lib/std/os/uefi/protocols/hii.zig
  lib/std/os/uefi/protocols/hii_database_protocol.zig
  lib/std/os/uefi/protocols/hii_popup_protocol.zig
  lib/std/os/uefi/protocols/rng_protocol.zig
  lib/std/os/uefi/protocols/simple_pointer_protocol.zig
  lib/std/os/uefi/protocols/simple_text_input_ex_protocol.zig
  lib/std/os/uefi/protocols/simple_text_output_protocol.zig
  lib/std/os/uefi/status.zig
  lib/std/os/uefi/tables/boot_services.zig
  lib/std/os/uefi/tables/configuration_table.zig
  lib/std/os/uefi/tables/runtime_services.zig
  lib/std/os/uefi/tables/system_table.zig
  lib/std/os/uefi/tables/table_header.zig
Labels: os-uefi

#3474 Adds documentation for std.fmt.format grammar and customization.
  lib/std/fmt.zig
Labels: standard library

#3432 Add documentation on function parameter type inference.
  doc/langref.html.in
Labels: docs

#3537 fix std.os.accept4
  lib/std/os.zig
Labels: standard library

#3531 generated docs: vertically align fns with comments
  lib/std/special/docs/index.html
Labels: docs

#3540 Add some documentation for standard library things.
  lib/std/array_list.zig
  lib/std/debug/failing_allocator.zig
  lib/std/mem.zig
Labels: docs, standard library

#3541 fix json parser crashing on empty input
  doc/langref.html.in
  lib/std/json.zig
Labels: standard library

#3555 Document PriorityQueue.
  lib/std/priority_queue.zig
Labels: docs

#3562 DragonFlyBSD support
  lib/std/atomic/queue.zig
  lib/std/atomic/stack.zig
  lib/std/c.zig
  lib/std/c/dragonfly.zig
  lib/std/debug.zig
  lib/std/event/channel.zig
  lib/std/event/fs.zig
  lib/std/event/group.zig
  lib/std/event/lock.zig
  lib/std/event/loop.zig
  lib/std/fs.zig
  lib/std/fs/get_app_data_dir.zig
  lib/std/mutex.zig
  lib/std/os.zig
  lib/std/os/bits.zig
  lib/std/os/bits/darwin.zig
  lib/std/os/bits/dragonfly.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/bits/linux.zig
  lib/std/os/bits/netbsd.zig
  lib/std/os/dragonfly.zig
  lib/std/os/test.zig
  lib/std/statically_initialized_mutex.zig
  src/libc_installation.cpp
  src/link.cpp
  src/os.cpp
  src/os.hpp
  src/target.cpp
  test/stage1/behavior/byteswap.zig
  test/stage1/behavior/vector.zig
Labels: os-dragonfly
