Repository ziglang/zig, pull requests merged in 2019-12, with the labels that each got.

#3715 Misc windows additions+fixes
  lib/std/child_process.zig
  lib/std/os/bits/windows.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/ntdll.zig
  lib/std/os/windows/status.zig
  lib/std/os/windows/ws2_32.zig
  lib/std/thread.zig
Labels: breaking, os-windows, standard library

#3733 Pick up WinMain with proper CC
  src/analyze.cpp
  src/analyze.hpp
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#3883 print call in build.zig needs to use a tuple argument
  lib/std/build.zig
Labels: standard library

#3881 fix con_in difinition and add EFI_SIMPLE_TEXT_INPUT_PROTOCOL difinition
  lib/std/os/uefi/protocols.zig
  lib/std/os/uefi/protocols/simple_text_input_protocol.zig
  lib/std/os/uefi/tables/system_table.zig
Labels: os-uefi, standard library

#3922 More eventfd stuff
  lib/std/child_process.zig
Labels: standard library

#3514 langref table of contents in a separate column on large displays
  doc/docgen.zig
  doc/langref.html.in
Labels: docs

#3552 generated docs: log trace instead of error
  lib/std/special/docs/main.js
Labels: docs

#3527 added -- to pass args to zig build commands
  lib/std/build.zig
  lib/std/special/build_runner.zig
Labels: zig build system

#3948 Fix sentinel value of opaque pointers in typeInfo
  src/ir.cpp
  test/stage1/behavior/type_info.zig
Labels: stage1

#3969 freebsd: add OS and libc bits missing for test-std
  lib/std/c/freebsd.zig
  lib/std/dynamic_library.zig
  lib/std/os/bits/freebsd.zig
Labels: os-freebsd, standard library

#3935 Translate-c-2 the rest
  lib/std/fmt.zig
  lib/std/zig/ast.zig
  lib/std/zig/parse.zig
  lib/std/zig/render.zig
  src-self-hosted/c_tokenizer.zig
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/translate_c.zig
Labels: translate-c

#3986 Two small translate-c(-2) patches
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#3987 std.unicode fixes
  lib/std/unicode.zig
  lib/std/unicode/throughput_test.zig
Labels: standard library

#3992 Add missing deferred deinits to `math.big.Int.toString`
  lib/std/math/big/int.zig
Labels: standard library

#3968 Clean up linux sigprocmask, raise
  lib/std/c.zig
  lib/std/os.zig
  lib/std/os/bits/linux.zig
  lib/std/os/linux.zig
Labels: standard library

#3967 Use std.meta.eql from std.testing.expectEqual
  lib/std/testing.zig
Labels: standard library

#3648 breaking: JSON unescape
  lib/std/json.zig
  lib/std/json/test.zig
Labels: standard library

#3669 ArrayList: ptrAt function returns pointer to item at given index
  lib/std/array_list.zig
Labels: standard library

#4002 std.Target missing address of operator to coerce slice type
  lib/std/target.zig
Labels: standard library, zig build system

#4010 Fix ptrCast of zero-sized type
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#4009 Resolve more types as needed
  src/analyze.cpp
  src/codegen.cpp
  src/ir.cpp
  test/stage1/behavior/error.zig
Labels: bug, stage1

#4007 std.json: cleanups
  lib/std/json.zig
  lib/std/meta.zig
Labels: standard library

#3943 install header in separate folder
  lib/std/build.zig
Labels: zig build system
