Repository ziglang/zig, pull requests merged in 2019-08, with the labels that each got.

#2985 Fix build references
  std/build.zig
Labels: zig build system

#2979 Fix public function lookup in rb
  std/rb.zig
Labels: standard library

#2994 Check if /dev/urandom is a character device
  std/os.zig
  std/os/bits/darwin.zig
  std/os/bits/freebsd.zig
  std/os/darwin.zig
  std/os/freebsd.zig
Labels: standard library

#2998 std: return Elf object from constructors instead of filling in pointer
  std/debug.zig
  std/elf.zig
Labels: standard library

#2797 hash algorithm improvements
  std/hash.zig
  std/hash/auto_hash.zig
  std/hash/throughput_test.zig
  std/hash/wyhash.zig
  std/hash_map.zig
  std/http/headers.zig
Labels: standard library

#2991 mingw improvements
  src/os.cpp
  src/os.hpp
  src/target.cpp
  std/os/windows.zig
Labels: os-windows

#3060 auto_hash with deep/shallow hashing
  std/event/fs.zig
  std/hash/auto_hash.zig
  std/hash/benchmark.zig
  std/hash/wyhash.zig
  std/hash_map.zig
  std/http/headers.zig
  std/std.zig
  tools/process_headers.zig
  tools/update_glibc.zig
Labels: standard library

#3139 zig fmt: fix nested if
  std/special/compiler_rt/comparetf2.zig
  std/zig/parser_test.zig
  std/zig/render.zig
Labels: enhancement
