Repository ziglang/zig, pull requests merged in 2019-11, with the labels that each got.

#3577 stage1: add linux XDG Base Directory support
  src/compiler.cpp
  src/os.cpp
  src/os.hpp
Labels: os-linux, stage1

#3588 Tiny std fixes
  lib/std/c.zig
  lib/std/c/darwin.zig
Labels: standard library

#3592 std: Add fifo useful for buffers
  lib/std/fifo.zig
  lib/std/std.zig
Labels: standard library

#3447 build: initial support for using vcpkg libraries
  lib/std/build.zig
  lib/std/target.zig
Labels: zig build system

#3709 Catch invalid type from peer resolution
  src/ir.cpp
  test/compile_errors.zig
Labels: bug, stage1

#3705 std: fix outdated valgrind module
  lib/std/valgrind.zig
  lib/std/valgrind/callgrind.zig
  lib/std/valgrind/memcheck.zig
Labels: bug, standard library

#3700 Fix bug on empty error union
  src/ir.cpp
  test/stage1/behavior/error.zig
Labels: bug, stage1

#3695 Windows definitions
  lib/std/os/bits/windows.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/ntdll.zig
  lib/std/os/windows/ws2_32.zig
Labels: os-windows, standard library

#3706 translate-c: add support for MacroQualified definitions
  src-self-hosted/clang.zig
  src/translate_c.cpp
  src/zig_clang.cpp
  src/zig_clang.h
  test/translate_c.zig
Labels: translate-c

#3710 Make StreamServer return address of accepted client
  lib/std/net.zig
  lib/std/net/test.zig
Labels: standard library

#3694 std.testing.expectEqual: show differing pointer values
  lib/std/testing.zig
Labels: standard library

#3734 Stage1: Add compile error for an empty switch on a integer
  src/range_set.cpp
  test/compile_errors.zig
Labels: stage1

#3644 Improvements to std.fifo
  lib/std/fifo.zig
Labels: standard library

#3744 std: update for linux 5.4
  lib/std/os/bits/linux.zig
Labels: os-linux, standard library

#3502 unembed ConstExprValue from IrInstruction and intern 1-possible-value types
  src/all_types.hpp
  src/analyze.cpp
  src/analyze.hpp
  src/bigint.cpp
  src/bigint.hpp
  src/codegen.cpp
  src/dump_analysis.cpp
  src/hash_map.hpp
  src/ir.cpp
  src/ir.hpp
  src/ir_print.cpp
  src/ir_print.hpp
  src/memory_profiling.cpp
  src/memory_profiling.hpp
  src/util.cpp
Labels: stage1

#3762 stage1: avoid building empty memory_profiling.cpp
  CMakeLists.txt
Labels: stage1

#3774 stage1: consolodate interning
  src/all_types.hpp
  src/analyze.cpp
  src/codegen.cpp
  src/ir.cpp
  src/memory_profiling.cpp
  src/memory_profiling.hpp
Labels: stage1

#3764 refactor std/debug.zig DwarfInfo operations to be methods
  lib/std/debug.zig
Labels: breaking, standard library

#3776 stage1: fix bad intern counting
  src/ir.cpp
Labels: stage1

#3714 Optimize binary search algorithm
  lib/std/sort.zig
Labels: standard library

#3769 Add initCapacity for buffer & arraylist
  lib/std/array_list.zig
  lib/std/buffer.zig
Labels: standard library

#3773 Implements std.testing.expectEqual for tagged unions.
  lib/std/testing.zig
Labels: work in progress

#3790 Windows: fix test/standalone/shared_library
  lib/std/build.zig
Labels: bug, os-windows, standard library
