Repository ziglang/zig, pull requests merged in 2020-12, with the labels that each got.

#6955 Localhost is special
  lib/std/net.zig
Labels: standard library

#7279 Special case SemanticVersion in addBuildOption
  lib/std/build.zig
Labels: standard library, zig build system

#7269 std: Add nosuspend around stderr.print calls
  lib/std/debug.zig
Labels: standard library

#7273 lld+macho: patch lld output on Apple Silicon by calculating and embedding adhoc code signature
  src/codegen.zig
  src/link.zig
  src/link/MachO.zig
  src/link/MachO/CodeSignature.zig
  src/link/MachO/commands.zig
  src/main.zig
Labels: os-macos, stage2

#7293 stage1: allow idx 0 err to be put into error_name_table
  src/stage1/codegen.cpp
  test/standalone.zig
  test/standalone/issue_7030/build.zig
  test/standalone/issue_7030/main.zig
Labels: stage1

#7302 Version-gate appending -syslibroot flag to lld
  src/Compilation.zig
  src/link/MachO.zig
Labels: os-macos

#7304 macho: specify -install_name as full dylib's name
  src/link/MachO.zig
Labels: os-macos, stage2

#7300 std: Add a few helpers for matching ascii strings
  lib/std/ascii.zig
Labels: standard library

#7326 std.c: freeing null is a no-op
  lib/std/c.zig
Labels: standard library

#7310 std.json: unreachable -> expect in tests
  lib/std/json/test.zig
Labels: standard library

#7367 stage2: add aarch64 load/store pair of registers instructions
  src/codegen.zig
  src/codegen/aarch64.zig
Labels: arch-arm64, stage2

#7368 stage2: MachO export trie cleanup
  lib/std/macho.zig
  src/link/MachO.zig
  src/link/MachO/Trie.zig
Labels: arch-arm64, os-macos, stage2

#7378 Translate-c: support referencing C containers in macros
  src/translate_c.zig
  test/stage1/behavior/translate_c_macros.h
  test/stage1/behavior/translate_c_macros.zig
Labels: translate-c

#7369 Add io_uring TIMEOUT and TIMEOUT_REMOVE operations:
  lib/std/os/linux/io_uring.zig
Labels: os-linux, standard library

#7334 Support casting enums to all int types in translate-c.
  src/translate_c.zig
  test/run_translated_c.zig
  test/translate_c.zig
Labels: translate-c

#7098 Implements std.fs.path.extension
  lib/std/fs/path.zig
Labels: standard library

#7383 Add missed Linux syscalls
  lib/std/os/bits/linux/arm-eabi.zig
  lib/std/os/bits/linux/arm64.zig
  lib/std/os/bits/linux/i386.zig
  lib/std/os/bits/linux/powerpc64.zig
  lib/std/os/bits/linux/riscv64.zig
  lib/std/os/bits/linux/sparc64.zig
  lib/std/os/bits/linux/x86_64.zig
Labels: os-linux, standard library

#7380 openbsd: link with required system libraries
  build.zig
  src/link/Elf.zig
Labels: os-openbsd

#7444 openbsd: crt0.o file is different when build static or dynamic mode
  src/link/Elf.zig
Labels: os-openbsd

#7417 create SendToError
  lib/std/fs/file.zig
  lib/std/os.zig
Labels: standard library

#7425 std: Fix StackFallbackAllocator
  lib/std/heap.zig
Labels: standard library

#7414 Add baudrate constants for Linux.
  lib/std/os/bits/linux.zig
Labels: standard library

#7516 macho: space preallocation, and various cleanups and fixes
  src/link/MachO.zig
  src/link/MachO/CodeSignature.zig
  src/link/MachO/Trie.zig
  src/link/MachO/commands.zig
Labels: os-macos, stage2

#7111 Implement emit-h
  src/Compilation.zig
  src/codegen/c.zig
  src/link/C.zig
  src/link/cbe.h
  src/main.zig
  src/test.zig
  test/stage2/cbe.zig
Labels: stage2

#7524 Added std.io.counting_reader
  CMakeLists.txt
  lib/std/io.zig
  lib/std/io/counting_reader.zig
Labels: standard library

#7529 Fix Gimli hash on 16n byte inputs
  lib/std/crypto/gimli.zig
Labels: standard library

#7490 openbsd: fix siginfo_t struct definition
  lib/std/os/bits/openbsd.zig
Labels: os-openbsd

#7523 std.c: add fmemopen
  lib/std/c.zig
Labels: standard library

#7422 stage1: float_*_ieee597: only swap bytes when targeting different endianness than native
  src/stage1/ir.cpp
  src/stage1/parse_f128.c
  src/stage1/zigendian.h
Labels: stage1

#7519 More pthreads integration
  CMakeLists.txt
  lib/std/Progress.zig
  lib/std/ResetEvent.zig
  lib/std/StaticResetEvent.zig
  lib/std/auto_reset_event.zig
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/c/freebsd.zig
  lib/std/c/linux.zig
  lib/std/debug.zig
  lib/std/fs/test.zig
  lib/std/mutex.zig
  lib/std/std.zig
  src/Compilation.zig
  src/Event.zig
  src/ThreadPool.zig
  src/WaitGroup.zig
Labels: stage2, standard library

#7531 Move ArrayListSentineled to std lib orphanage
  lib/std/array_list.zig
  lib/std/array_list_sentineled.zig
  lib/std/child_process.zig
  lib/std/io.zig
  lib/std/io/counting_reader.zig
  lib/std/json.zig
  lib/std/net.zig
  lib/std/os/linux/io_uring.zig
  lib/std/std.zig
  src/DepTokenizer.zig
  test/standalone/brace_expansion/main.zig
Labels: proposal, standard library

#7191 stage2: add compile log statement
  src/Compilation.zig
  src/Module.zig
  src/astgen.zig
  src/codegen/c.zig
  src/link/C.zig
  src/link/Coff.zig
  src/link/Elf.zig
  src/link/MachO.zig
  src/value.zig
  src/zir.zig
  src/zir_sema.zig
  test/stage2/test.zig
Labels: stage2

#7449 add termios bits for darwin
  lib/std/os/bits/darwin.zig
Labels: os-macos, standard library

#7483 Make hasUniqueRepresentation false for slices
  lib/std/hash/auto_hash.zig
  lib/std/meta/trait.zig
Labels: standard library

#7601 stage2: SemVer compliance for development builds
  CMakeLists.txt
  build.zig
  src/config.zig.in
Labels: stage2

#7608 macho: add preliminary support for DWARF debugging symbols
  src/link/MachO.zig
  src/link/MachO/DebugSymbols.zig
  src/link/MachO/commands.zig
Labels: os-macos, stage2
