Repository ziglang/zig, pull requests merged in 2020-04, with the labels that each got.

#4898 stage1: make C++ switch fallthrough an error
  CMakeLists.txt
  src/analyze.cpp
  src/codegen.cpp
  src/dump_analysis.cpp
  src/ir.cpp
  src/target.cpp
  src/tokenizer.cpp
  src/util_base.hpp
Labels: stage1

#4908 Modernize LinearFifo for new stream conventions
  lib/std/fifo.zig
Labels: standard library

#4921 Update all remaining uses of &outStream().stream
  lib/std/hash/benchmark.zig
  lib/std/unicode/throughput_test.zig
  lib/std/zig/perf_test.zig
  tools/merge_anal_dumps.zig
Labels: standard library

#4918 Update fmt.zig - custom format() needs to be pub
  lib/std/fmt.zig
Labels: standard library

#4920 stage1: add compile errors for sentinel slicing
  src/ir.cpp
  test/compile_errors.zig
  test/stage1/behavior.zig
  test/stage1/behavior/slice_sentinel_comptime.zig
Labels: stage1

#4868 new ArrayList API
  lib/std/array_list.zig
  lib/std/array_list_sentineled.zig
  lib/std/build.zig
  lib/std/build/emit_raw.zig
  lib/std/coff.zig
  lib/std/debug.zig
  lib/std/dwarf.zig
  lib/std/fs.zig
  lib/std/http/headers.zig
  lib/std/io/in_stream.zig
  lib/std/json.zig
  lib/std/math/big/rational.zig
  lib/std/net.zig
  lib/std/special/build_runner.zig
  lib/std/unicode.zig
  src-self-hosted/libc_installation.zig
  src-self-hosted/stage2.zig
  src-self-hosted/translate_c.zig
  test/standalone/brace_expansion/main.zig
  test/tests.zig
  tools/merge_anal_dumps.zig
Labels: standard library

#4933 Adds some documentation to std.atomic.Queue.
  lib/std/atomic/queue.zig
Labels: docs, standard library

#4942 Tidy up compiler_rt/atomics
  lib/std/special/compiler_rt/atomics.zig
Labels: standard library

#4901 translate-c: RemAssign and DivAssign
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4684 Translate C: Add comment containing c source location for failed decls
  src-self-hosted/translate_c.zig
Labels: translate-c

#4857 Rewrite the bound checks in slice operator
  lib/std/debug.zig
  lib/std/fs.zig
  src/codegen.cpp
  test/runtime_safety.zig
Labels: stage1

#4794 langref: small updates
  doc/langref.html.in
Labels: docs

#4678 std/zig/parse_string_literal.zig: add hex+unicode escapes
  lib/std/zig/parse_string_literal.zig
Labels: standard library

#4973 Nameless fields
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#5013 std: add some basic windows user32 definitions
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/user32.zig
Labels: os-windows, standard library

#5015 fix efi file protocol structure definitions
  lib/std/os/uefi/protocols/file_protocol.zig
Labels: os-uefi, standard library

#5014 Update documentation of @panic
  doc/langref.html.in
Labels: docs

#5016 os.fstatat
  lib/std/os.zig
Labels: standard library

#5026 std: fix StreamSource to disallow writing to a const buffer
  lib/std/io/stream_source.zig
Labels: standard library

#5046 Translate-c correct invalid shortcut
  lib/std/array_list.zig
  lib/std/math/big/int.zig
  lib/std/os.zig
  lib/std/os/windows/gdi32.zig
  lib/std/os/windows/user32.zig
  lib/std/zig/parser_test.zig
  src-self-hosted/stage2.zig
  src-self-hosted/translate_c.zig
  test/stage1/behavior/for.zig
  test/translate_c.zig
Labels: translate-c

#5072 debug: Minor QOL improvements for osx
  lib/std/debug.zig
Labels: standard library

#5069 build: Create the output directory if it doesn't exist
  lib/std/build.zig
Labels: standard library

#5095 std.os.readv: Add missing iov_count declaration
  lib/std/os.zig
Labels: standard library

#5094 std: Introduce the Once synchronization primitive
  lib/std/once.zig
  lib/std/std.zig
Labels: standard library

#5103 fix uninitialized ZigValue
  src/all_types.hpp
  src/ir.cpp
Labels: stage1

#5117 Added peer type resolution for [*]T and *[N]T.
  src/ir.cpp
  test/stage1/behavior/cast.zig
Labels: stage1

#5135 stage1: Prevent the creation of illegal pointer types
  src/analyze.cpp
  src/ir.cpp
  test/stage1/behavior/pointers.zig
Labels: stage1

#5125 macos: add fallback version detection
  lib/std/zig/system.zig
  lib/std/zig/system/macos.zig
Labels: os-macos, stage2

#5172 Fix f64 variants of math.cosh and math.sinh to accept negative inputs.
  lib/std/math/cosh.zig
  lib/std/math/sinh.zig
Labels: standard library

#5167 Fix issue with std.json incorrectly replacing forward slashes with a backslash
  lib/std/json.zig
Labels: standard library
