Repository ziglang/zig, pull requests merged in 2020-01, with the labels that each got.

#4023 Fix segfault in bit shift safety check
  src/ir.cpp
  test/stage1/behavior/bit_shifting.zig
Labels: stage1

#4033 translate-c properly handle unused var-args
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4036 Don't ptrCast a result-location assignment to _
  src/ir.cpp
  test/stage1/behavior/bitcast.zig
Labels: stage1

#4032 Prefer simple ptrCast between opaque types
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4027 fix float ops with respect to vectors
  doc/langref.html.in
  lib/std/math/sqrt.zig
  lib/std/special/c.zig
  src/all_types.hpp
  src/codegen.cpp
  src/ir.cpp
  src/ir.hpp
  src/ir_print.cpp
  test/stage1/behavior/floatop.zig
  test/stage1/behavior/math.zig
Labels: breaking, enhancement

#3950 Document std.Mutex.
  lib/std/mutex.zig
Labels: docs, standard library

#4053 add test harness for "run translated C" tests
  build.zig
  lib/std/build.zig
  lib/std/build/check_file.zig
  lib/std/build/run.zig
  lib/std/build/translate_c.zig
  lib/std/build/write_file.zig
  lib/std/fs.zig
  src/codegen.cpp
  src/codegen.hpp
  src/main.cpp
  test/run_translated_c.zig
  test/src/compare_output.zig
  test/src/run_translated_c.zig
  test/src/translate_c.zig
  test/tests.zig
Labels: translate-c

#4064 use @intCast instead of @as for shift rhs
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4078 Better InitListExpr translation
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/translate_c.zig
Labels: translate-c

#4073 Add more compiler-rt functions for ARM platform
  lib/std/special/compiler_rt.zig
  lib/std/special/compiler_rt/floatundisf.zig
  lib/std/special/compiler_rt/floatunsisf.zig
Labels: arch-arm32

#4052 translate-c: use @intToPtr to cast away qualifiers
  src-self-hosted/translate_c.zig
  test/run_translated_c.zig
  test/translate_c.zig
Labels: translate-c

#4083 Better _Bool translation
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/run_translated_c.zig
  test/translate_c.zig
Labels: translate-c

#4092 Add std.mem.zeroes to the standard library
  lib/std/mem.zig
Labels: standard library

#4090 Prevent bitCast to enum types
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#4085 Preserve packed attribute in C translated struct
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/run_translated_c.zig
  test/translate_c.zig
Labels: translate-c

#3930 added -- to pass args to zig build commands
  lib/std/build.zig
  lib/std/special/build_runner.zig
Labels: standard library, zig build system

#3946 build support list options
  lib/std/build.zig
Labels: zig build system

#3989 std: sentinel terminated pointers for utf16 apis
  lib/std/child_process.zig
  lib/std/fs/file.zig
  lib/std/fs/get_app_data_dir.zig
  lib/std/os.zig
  lib/std/os/uefi/protocols/simple_text_output_protocol.zig
  lib/std/os/uefi/tables/runtime_services.zig
  lib/std/os/uefi/tables/system_table.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/ntdll.zig
  lib/std/os/windows/shell32.zig
  lib/std/unicode.zig
Labels: standard library

#4091 json: implement copy_strings=false
  lib/std/json.zig
Labels: standard library

#4101 More translate-c fixes
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/run_translated_c.zig
  test/translate_c.zig
Labels: translate-c

#4070 Add removeIdx function to PriorityQueue.
  lib/std/priority_queue.zig
Labels: standard library

#4121 std: fix LoggingAllocator, add simple test
  lib/std/heap.zig
  lib/std/heap/logging_allocator.zig
Labels: standard library

#4122 Fix #4118
  src-self-hosted/translate_c.zig
  test/run_translated_c.zig
Labels: translate-c

#4129 Fix windows child process creation
  lib/std/child_process.zig
Labels: os-windows, standard library

#4132 Handle forward-declared functions
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/run_translated_c.zig
Labels: translate-c

#4149 Add WaitForSingleObject function to std.os.windows
  lib/std/os/windows.zig
Labels: os-windows, standard library

#4146 Correct TypeId docs
  doc/langref.html.in
Labels: docs

#4139 strip cwd from compile error paths
  src/errmsg.cpp
Labels: stage1

#4156 docs: update grammar to remove C strings and add anon literals
  doc/langref.html.in
Labels: docs

#4161 prefer C++ compiler builtins for BREAKPOINT
  src/util.hpp
Labels: stage1

#4162 Fix @call being too eager to resolve the fn argument
  src/ir.cpp
  test/compile_errors.zig
  test/stage1/behavior/call.zig
Labels: stage1

#4153 small doc fix
  doc/langref.html.in
Labels: docs

#3957 stage2 parser: fix segfault on extern block
  lib/std/zig/ast.zig
  lib/std/zig/parse.zig
  lib/std/zig/parser_test.zig
  lib/std/zig/render.zig
Labels: stage2, standard library

#4175 [docs] Add libc dependency to Sentinel-Terminated Pointers example
  doc/langref.html.in
Labels: docs

#4137 Fix std.child_process.ChildProcess.spawnWindow when app_name is relative
  lib/std/child_process.zig
Labels: os-windows, standard library

#4186 stage1: move local native_libc.txt to global
  src/codegen.cpp
  src/compiler.cpp
  src/compiler.hpp
  src/glibc.cpp
  src/link.cpp
  src/main.cpp
  src/os.cpp
  src/os.hpp
Labels: stage1

#4195 Port __clzsi2 from compiler_rt
  lib/std/special/compiler_rt.zig
  lib/std/special/compiler_rt/clzsi2.zig
  lib/std/special/compiler_rt/clzsi2_test.zig
Labels: arch-arm32

#4216 std: use non-exhaustive enums from crc module
  lib/std/hash/benchmark.zig
  lib/std/hash/crc.zig
Labels: standard library

#4217 std: turn EAI_ constants into a non-exhaustive enum
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/c/freebsd.zig
  lib/std/c/linux.zig
  lib/std/net.zig
Labels: standard library

#4220 Allow @tagName on enum literals
  src/ir.cpp
  test/stage1/behavior/enum.zig
Labels: stage1

#4230 fixed typo - "path" lead to undeclared identifier
  lib/std/dynamic_library.zig
Labels: standard library

#4222 Prevent crash with empty non-exhaustive enum
  src/analyze.cpp
  src/ir.cpp
  test/stage1/behavior/enum.zig
  test/stage1/behavior/union.zig
Labels: bug, stage1

#4219 Handle {s} format for C strings.
  lib/std/fmt.zig
Labels: standard library

#4247 Fix ICE in build addAssemblyFile
  lib/std/build.zig
Labels: zig build system

#4263 Refactor some debug stuff
  lib/std/debug.zig
  lib/std/io/out_stream.zig
  test/stack_traces.zig
Labels: standard library

#4279 stage1: make sure to create native_libc.txt dir
  src/codegen.cpp
  src/main.cpp
Labels: stage1

#4290 split IrInstruction into IrInst, IrInstSrc, IrInstGen
  src/all_types.hpp
  src/analyze.cpp
  src/analyze.hpp
  src/codegen.cpp
  src/ir.cpp
  src/ir.hpp
  src/ir_print.cpp
  src/ir_print.hpp
  src/parser.cpp
Labels: stage1

#4264 Add support for target details (CPUs and their supported features)
  lib/std/buffer.zig
  lib/std/build.zig
  lib/std/builtin.zig
  lib/std/debug.zig
  lib/std/fmt.zig
  lib/std/fmt/parse_float.zig
  lib/std/io/test.zig
  lib/std/math/fabs.zig
  lib/std/math/isinf.zig
  lib/std/math/isnan.zig
  lib/std/meta.zig
  lib/std/os/linux/tls.zig
  lib/std/special/compiler_rt/addXf3_test.zig
  lib/std/special/compiler_rt/fixtfdi_test.zig
  lib/std/special/compiler_rt/fixtfsi_test.zig
  lib/std/special/compiler_rt/fixtfti_test.zig
  lib/std/special/compiler_rt/fixunstfdi_test.zig
  lib/std/special/compiler_rt/fixunstfsi_test.zig
  lib/std/special/compiler_rt/fixunstfti_test.zig
  lib/std/special/compiler_rt/floattitf_test.zig
  lib/std/special/compiler_rt/floatuntitf_test.zig
  lib/std/special/compiler_rt/mulXf3_test.zig
  lib/std/special/compiler_rt/truncXfYf2_test.zig
  lib/std/target.zig
  lib/std/target/aarch64.zig
  lib/std/target/amdgpu.zig
  lib/std/target/arm.zig
  lib/std/target/avr.zig
  lib/std/target/bpf.zig
  lib/std/target/hexagon.zig
  lib/std/target/mips.zig
  lib/std/target/msp430.zig
  lib/std/target/nvptx.zig
  lib/std/target/powerpc.zig
  lib/std/target/riscv.zig
  lib/std/target/sparc.zig
  lib/std/target/systemz.zig
  lib/std/target/wasm.zig
  lib/std/target/x86.zig
  src-self-hosted/main.zig
  src-self-hosted/print_targets.zig
  src-self-hosted/stage1.zig
  src/all_types.hpp
  src/codegen.cpp
  src/error.cpp
  src/ir.cpp
  src/main.cpp
  src/target.cpp
  src/target.hpp
  src/userland.cpp
  src/userland.h
  src/zig_llvm.cpp
  test/compile_errors.zig
  test/stage1/behavior/math.zig
  test/tests.zig
  test/translate_c.zig
Labels: breaking

#4133 Sets memory to undefined when freed from allocator
  lib/std/http/headers.zig
  lib/std/mem.zig
Labels: standard library

#4300 More debug fixes - This time Windows gets a treat
  lib/std/debug.zig
Labels: os-windows, standard library

#4316 translate-c: Handle fn protos wrapped in parenthesis
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4239 rb: **breaking** change API to be thread-safe
  lib/std/rb.zig
Labels: breaking, standard library

#4333 translate-c: Fix translation of fn pointers
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4339 std: update for linux 5.5 release
  lib/std/os/bits/linux.zig
Labels: os-linux, standard library

#4340 Windows error codes as non-exhaustive enums
  lib/std/event/fs.zig
  lib/std/fmt.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/mutex.zig
  lib/std/os.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/error.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/ntstatus.zig
  lib/std/os/windows/status.zig
  lib/std/os/windows/win32error.zig
  lib/std/reset_event.zig
Labels: os-windows, standard library
