Repository ziglang/zig, pull requests merged in 2020-06, with the labels that each got.

#5475 support name resolution on windows
  lib/std/c.zig
  lib/std/net.zig
  lib/std/net/test.zig
  lib/std/os.zig
  lib/std/os/bits/windows.zig
  lib/std/os/windows/ws2_32.zig
Labels: os-windows, standard library

#5510 pass allocator to self.resize() in appendNTimes()
  lib/std/array_list.zig
Labels: standard library

#5534 std.os.windows.OpenFile: Handle FILE_IS_A_DIRECTORY status
  lib/std/os/windows.zig
Labels: os-windows, standard library

#5566 Stage2 garbage collect decls
  lib/std/comptime_string_map.zig
  lib/std/debug.zig
  lib/std/http/headers.zig
  lib/std/net.zig
  lib/std/sort.zig
  src-self-hosted/Module.zig
  src-self-hosted/main.zig
  src-self-hosted/test.zig
  src-self-hosted/type.zig
  src-self-hosted/value.zig
  src-self-hosted/zir.zig
  test/stage2/zir.zig
Labels: breaking, enhancement, stage2, standard library

#5563 support Writer for OutStream
  lib/std/debug.zig
  lib/std/fs/file.zig
  lib/std/io.zig
  lib/std/io/bit_out_stream.zig
  lib/std/io/bit_writer.zig
  lib/std/io/buffered_atomic_file.zig
  lib/std/io/buffered_out_stream.zig
  lib/std/io/buffered_writer.zig
  lib/std/io/c_out_stream.zig
  lib/std/io/c_writer.zig
  lib/std/io/counting_out_stream.zig
  lib/std/io/counting_writer.zig
  lib/std/io/fixed_buffer_stream.zig
  lib/std/io/multi_out_stream.zig
  lib/std/io/multi_writer.zig
  lib/std/io/out_stream.zig
  lib/std/io/writer.zig
  lib/std/zig/render.zig
Labels: standard library

#5539 stage1: fix constness in some corner cases
  src/ir.cpp
  test/stage1/behavior.zig
  test/stage1/behavior/bugs/5474.zig
Labels: stage1

#5589 Add doc example for extracting WASI preopens
  doc/langref.html.in
  lib/std/fs/wasi.zig
Labels: os-wasi

#5570 Add strict_align to pre-v6 ARM targets
  lib/std/target/arm.zig
Labels: arch-arm32

#5609 stage1: remove obsolete branch in ir_analyze_cast
  src/ir.cpp
Labels: stage1

#5598 ArrayList(u8) support writer interface
  lib/std/array_list.zig
Labels: standard library

#5607 std: clean up debug stderr variables
  lib/std/debug.zig
  lib/std/json.zig
Labels: standard library

#5348 Introduce std.log
  lib/std/debug.zig
  lib/std/log.zig
  lib/std/std.zig
Labels: standard library

#5631 Fix using io from std.log
  lib/std/log.zig
Labels: standard library

#5661 [libstd]: add std.fs.File.readAllAlloc tests
  lib/std/fs/file.zig
  lib/std/fs/test.zig
  lib/std/io/reader.zig
Labels: standard library

#5685 Fix issue #5618
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#5677 [libstd]: implement fstatat in WASI plus fix on macOS
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/os.zig
  lib/std/os/test.zig
Labels: os-macos, os-wasi, standard library

#5684 Add tests for using directory operations on files
  lib/std/fs.zig
  lib/std/fs/test.zig
Labels: standard library

#5588 LEB128 overhaul and output
  lib/std/debug/leb128.zig
Labels: standard library

#5064 new allocator interface
  lib/std/array_list.zig
  lib/std/c.zig
  lib/std/heap.zig
  lib/std/heap/arena_allocator.zig
  lib/std/heap/logging_allocator.zig
  lib/std/mem.zig
  lib/std/os/windows/bits.zig
  lib/std/testing.zig
  lib/std/testing/failing_allocator.zig
  lib/std/testing/leak_count_allocator.zig
Labels: standard library
