Repository ziglang/zig, pull requests merged in 2020-07, with the labels that each got.

#5788 std.mem.dupe is deprecated, move all references in std
  lib/std/buf_map.zig
  lib/std/build.zig
  lib/std/cache_hash.zig
  lib/std/fs.zig
  lib/std/fs/path.zig
  lib/std/fs/watch.zig
  lib/std/http/headers.zig
  lib/std/json.zig
  lib/std/math/big/int.zig
  lib/std/net.zig
  lib/std/priority_queue.zig
  lib/std/process.zig
  lib/std/zig/cross_target.zig
  lib/std/zig/system.zig
Labels: standard library

#5773 Fix issue 5757: increase branch quota for formatting enums
  lib/std/fmt.zig
Labels: standard library

#5857 Use unmanaged datastructures from std.http.headers
  lib/std/hash_map.zig
  lib/std/http/headers.zig
  lib/std/std.zig
Labels: standard library

#5831 Explain Language Ref's Hello World
  doc/langref.html.in
Labels: docs

#5868 Stage2 improvements
  lib/std/zig/ast.zig
  lib/std/zig/parse.zig
  lib/std/zig/render.zig
  src-self-hosted/Module.zig
  src-self-hosted/codegen.zig
  src-self-hosted/ir.zig
  src-self-hosted/liveness.zig
  src-self-hosted/translate_c.zig
  src-self-hosted/type.zig
  src-self-hosted/value.zig
  src-self-hosted/zir.zig
  test/stage2/compare_output.zig
Labels: breaking, enhancement, stage2, standard library

#5885 self-hosted compiler local consts
  lib/std/zig/ast.zig
  lib/std/zig/parse.zig
  lib/std/zig/render.zig
  src-self-hosted/Module.zig
  src-self-hosted/astgen.zig
  src-self-hosted/codegen.zig
  src-self-hosted/ir.zig
  src-self-hosted/translate_c.zig
  src-self-hosted/zir.zig
Labels: breaking, stage2

#5879 Implement readlink on Windows
  lib/std/fs.zig
  lib/std/fs/test.zig
  lib/std/os.zig
  lib/std/os/test.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/zig/system.zig
Labels: os-windows, standard library

#5068 macOS: macho ld64.lld fixes
  src-self-hosted/stage2.zig
  src/link.cpp
  src/stage2.cpp
  src/stage2.h
  src/target.cpp
  src/util.hpp
Labels: os-macos

#5370 std: fix json parsing into unions
  lib/std/json.zig
Labels: bug, standard library

#5317 Provide Ip4Address and Ip6Address in addition to Address
  lib/std/net.zig
Labels: standard library

#5932 new trait `hasUniqueRepresentation` and hashmap speedup
  lib/std/hash/auto_hash.zig
  lib/std/hash_map.zig
  lib/std/meta/trait.zig
Labels: optimization, standard library

#5925 Add writer to LinearFifo instead of deprecated outStream
  lib/std/fifo.zig
Labels: standard library

#5922 Zig docs look tiny on mobile screens
  doc/langref.html.in
Labels: docs

#5937 Replace DeviceIoControl with FsControlFile
  lib/std/os/windows.zig
  lib/std/os/windows/ntdll.zig
Labels: os-windows, standard library

#5923 Adds support for RunStep to use the result of a WriteFileStep.
  lib/std/build/run.zig
Labels: standard library, zig build system

#5945 Add Zig wrapper for kernel32.DeviceIoControl
  lib/std/os/windows.zig
Labels: os-windows, standard library

#5949 Split DeviceIoControl path into two fn call paths
  lib/std/os/windows.zig
Labels: os-windows, standard library
