Repository ziglang/zig, pull requests merged in 2020-08, with the labels that each got.

#5964 elf: Iterate over headers w/o need for allocator
  lib/std/build/emit_raw.zig
  lib/std/elf.zig
Labels: standard library

#5960 Refactor out file and dir creation routines in Windows
  lib/std/child_process.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/watch.zig
  lib/std/os.zig
  lib/std/os/bits/windows.zig
  lib/std/os/test.zig
  lib/std/os/windows.zig
Labels: os-windows, standard library

#5996 stage1: elide `@intToPtr` alignment safety check for 1-byte alignment
  src/codegen.cpp
Labels: stage1

#5998 std: introduce GeneralPurposeAllocator
  doc/langref.html.in
  lib/std/array_list.zig
  lib/std/atomic/queue.zig
  lib/std/debug.zig
  lib/std/heap.zig
  lib/std/heap/arena_allocator.zig
  lib/std/heap/general_purpose_allocator.zig
  lib/std/heap/logging_allocator.zig
  lib/std/math.zig
  lib/std/mem.zig
  lib/std/mem/Allocator.zig
  lib/std/mutex.zig
  lib/std/once.zig
  lib/std/special/test_runner.zig
  lib/std/std.zig
  lib/std/testing.zig
  lib/std/testing/failing_allocator.zig
  lib/std/testing/leak_count_allocator.zig
  src-self-hosted/link.zig
  src-self-hosted/main.zig
  src-self-hosted/test.zig
  src/codegen.cpp
  src/ir.cpp
Labels: breaking, enhancement, standard library

#6002 Fixes floating point alignment in std.fmt.format
  lib/std/fmt.zig
Labels: standard library

#5993 Implement std.os.windows.GetPathNameByHandle using NT routines only
  lib/std/os.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
Labels: os-windows, standard library

#6010 copy_file_range linux syscall
  lib/std/builtin.zig
  lib/std/c/linux.zig
  lib/std/fs/file.zig
  lib/std/fs/test.zig
  lib/std/os.zig
  lib/std/os/linux.zig
  lib/std/target.zig
Labels: standard library

#6038 docs: Fix reference to General Purpose Allocator
  doc/langref.html.in
Labels: docs

#5701 Add std.os.getFdPath and std.fs.Dir.realpath
  lib/std/fs.zig
  lib/std/fs/test.zig
  lib/std/os.zig
Labels: os-linux, os-macos, os-windows, standard library

#6006 PowerPC: Fix build error when targeting CPUs with numeric model name
  lib/std/target/powerpc.zig
Labels: arch-powerpc

#6075 std/crypto: gimli.Aead.decrypt()'s ad should be const
  lib/std/crypto/gimli.zig
Labels: standard library

#6069 stage2: fix signed <-> unsigned Value casts
  src-self-hosted/value.zig
Labels: stage2

#6060 Stage2: more optionals stuff
  src-self-hosted/Module.zig
  src-self-hosted/astgen.zig
  src-self-hosted/codegen.zig
  src-self-hosted/ir.zig
  src-self-hosted/type.zig
  src-self-hosted/zir.zig
  src-self-hosted/zir_sema.zig
Labels: stage2

#6056 stage2: add a wasm backend
  src-self-hosted/Module.zig
  src-self-hosted/codegen/wasm.zig
  src-self-hosted/link.zig
  src-self-hosted/link/MachO.zig
  src-self-hosted/link/Wasm.zig
  src-self-hosted/main.zig
  test/stage2/compare_output.zig
Labels: arch-wasm32, stage2

#6077 Cleaned up RISC-V instruction creation, added 32-bit immediates
  src-self-hosted/codegen.zig
  src-self-hosted/codegen/riscv64.zig
Labels: arch-riscv64, stage2

#6081 ristretto255: add uniform string->element map & inversionless equivalence check
  lib/std/crypto/25519/field.zig
  lib/std/crypto/25519/ristretto255.zig
Labels: standard library

#6083 stage2/link: clarify comments on calling order
  src-self-hosted/link.zig
Labels: stage2

#6086 Stage2: more astgen stuff
  lib/std/zig.zig
  src-self-hosted/Module.zig
  src-self-hosted/astgen.zig
  src-self-hosted/type.zig
  src-self-hosted/value.zig
  src-self-hosted/zir.zig
  src-self-hosted/zir_sema.zig
  test/stage2/compare_output.zig
Labels: stage2

#6085 Write out Mach-O header
  lib/std/macho.zig
  src-self-hosted/link.zig
  src-self-hosted/link/MachO.zig
Labels: os-macos, stage2

#6102 Write page zero as first segment for Mach-O exes
  src-self-hosted/link/MachO.zig
Labels: os-macos, stage2

#6104 add UTIME_NOW and UTIME_OMIT constants for use in utimensat/futimens
  lib/std/os/bits/linux.zig
Labels: os-linux, standard library

#6095 Breaking: sort std/crypto functions into categories
  lib/std/bloom_filter.zig
  lib/std/build/write_file.zig
  lib/std/cache_hash.zig
  lib/std/crypto.zig
  lib/std/crypto/25519/ed25519.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/blake2.zig
  lib/std/crypto/blake3.zig
  lib/std/crypto/chacha20.zig
  lib/std/crypto/gimli.zig
  lib/std/crypto/hmac.zig
  lib/std/crypto/md5.zig
  lib/std/crypto/sha1.zig
  lib/std/crypto/sha2.zig
  lib/std/crypto/sha3.zig
  lib/std/crypto/test.zig
  lib/std/rand.zig
  lib/std/zig.zig
  tools/process_headers.zig
Labels: breaking, standard library

#6106 Add macosx end-to-end smoke test
  test/stage2/test.zig
Labels: os-macos, stage2

#6142 Fix unused argument error when formatting std.Target
  lib/std/target.zig
Labels: standard library

#6146 Use O_NOCTTY open flag
  lib/std/fs.zig
  lib/std/fs/file.zig
Labels: standard library

#6157 Fix & update windows version stuff
  lib/std/target.zig
  lib/std/zig/system.zig
Labels: os-windows, standard library

#6161 Add (empty) __TEXT segment load command
  lib/std/macho.zig
  src-self-hosted/link/MachO.zig
Labels: os-macos, stage2, standard library

#6163 stage2: codegen for conditional branching
  build.zig
  src-self-hosted/astgen.zig
  src-self-hosted/codegen.zig
  src-self-hosted/link/Elf.zig
  src-self-hosted/type.zig
  src-self-hosted/zir.zig
  test/stage2/test.zig
Labels: stage2

#6164 Improve crypto benchmarks
  lib/std/crypto/benchmark.zig
  lib/std/crypto/chacha20.zig
  lib/std/crypto/gimli.zig
  lib/std/math.zig
  lib/std/math/asinh.zig
  lib/std/math/atan.zig
  lib/std/math/atanh.zig
  lib/std/math/ceil.zig
  lib/std/math/exp.zig
  lib/std/math/exp2.zig
  lib/std/math/expm1.zig
  lib/std/math/floor.zig
  lib/std/math/log1p.zig
  lib/std/math/round.zig
  lib/std/math/tanh.zig
  lib/std/math/trunc.zig
  lib/std/mem.zig
Labels: standard library

#6159 std.mem.count
  lib/std/mem.zig
Labels: standard library

#6177 ensure main return type is not i8
  lib/std/start.zig
Labels: standard library

#6160 Add Keyword Reference section
  doc/langref.html.in
Labels: docs

#6174 Improve io.Reader.skipBytes and add tests
  lib/std/io/reader.zig
Labels: standard library

#6191 fix _reset in simple_text_input_protocol.zig
  lib/std/os/uefi/protocols/simple_text_input_protocol.zig
Labels: os-uefi, standard library

#6198 std: Open the eventfd fd with CLOEXEC flag
  lib/std/child_process.zig
Labels: standard library

#6182 handle lack of privilege to create symbolic links on windows
  lib/std/fs/test.zig
  lib/std/os/test.zig
  lib/std/os/windows.zig
Labels: os-windows, standard library

#6189 std: Add std.math.divCeil
  lib/std/math.zig
Labels: standard library

#6200 Add more missing MachO constants and structs
  lib/std/macho.zig
Labels: os-macos, standard library

#6201 std.ChildProcess: pass CLOEXEC when creating error pipe
  lib/std/child_process.zig
Labels: standard library

#6184 std.meta.TrailerFlags: use @Type to improve API
  lib/std/meta/trailer_flags.zig
  lib/std/zig/ast.zig
  lib/std/zig/render.zig
  src-self-hosted/Module.zig
  src-self-hosted/astgen.zig
  src-self-hosted/codegen.zig
  src-self-hosted/link/Elf.zig
  src-self-hosted/translate_c.zig
Labels: breaking, stage2, standard library

#6197 gpa: Fix bookkeeping logic
  lib/std/heap/general_purpose_allocator.zig
Labels: standard library
