Repository ziglang/zig, pull requests merged in 2020-02, with the labels that each got.

#4348 Winsock errors can be an enum
  lib/std/os/windows.zig
  lib/std/os/windows/ws2_32.zig
Labels: os-windows, standard library

#4343 Add support for dependent packages when using build.zig
  lib/std/build.zig
Labels: zig build system

#4366 crypto: Add BLAKE3 hashing algorithm
  lib/std/crypto.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/blake3.zig
Labels: standard library

#4337 stdlib: Add binary search function
  lib/std/sort.zig
Labels: standard library

#4327 Add basic linux termios implementation
  lib/std/c.zig
  lib/std/os.zig
  lib/std/os/bits/linux.zig
  lib/std/os/linux.zig
Labels: os-linux, standard library

#4383 std: Fix edge case in isAbsolute fn family
  lib/std/fs/path.zig
Labels: os-windows, standard library

#4390 stage1: guard against case-mismatched build types
  CMakeLists.txt
Labels: stage1

#4363 Use std.c.tokenizer in translate-c
  lib/std/c/tokenizer.zig
  src-self-hosted/c_tokenizer.zig
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: standard library, translate-c

#4345 Fix double close in openElfDebugInfo
  lib/std/debug.zig
Labels: standard library

#4369 std.crypto.gimli enhancements
  lib/std/crypto/benchmark.zig
  lib/std/crypto/gimli.zig
  lib/std/rand.zig
Labels: enhancement, standard library

#4428 Add cast between [*c]T and ?[*:0]T on fn parameter
  src/ir.cpp
  test/stage1/behavior/cast.zig
Labels: stage1

#4441 stage1: limit cmake checks on build type
  CMakeLists.txt
Labels: stage1

#4442 Migrate tests from FixedBufferAllocator to testing.allocator
  lib/std/array_list.zig
  lib/std/ascii.zig
  lib/std/cstr.zig
  lib/std/fs/get_app_data_dir.zig
  lib/std/fs/path.zig
  lib/std/http/headers.zig
  lib/std/io.zig
  lib/std/io/test.zig
  lib/std/json.zig
  lib/std/json/test.zig
  lib/std/os/test.zig
  lib/std/process.zig
  lib/std/sort.zig
  lib/std/unicode.zig
  lib/std/zig/parser_test.zig
  test/stage1/behavior/bugs/1851.zig
Labels: standard library

#4440 ir: Don't crash when converting undefined ptrs
  src/ir.cpp
Labels: stage1

#4449 modernize std.meta
  lib/std/meta.zig
  lib/std/meta/trait.zig
Labels: standard library

#4453 Translate-c improve macro cast translation
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4451 Migrate (more) tests from FixedBufferAllocator to testing.allocator
  lib/std/json.zig
  lib/std/json/write_stream.zig
  lib/std/math/big/int.zig
  lib/std/math/big/rational.zig
  lib/std/mem.zig
  lib/std/net/test.zig
  lib/std/testing.zig
Labels: standard library

#4467 translate-c: change OutOfMemory → ASTUnitFailure
  src-self-hosted/stage1.zig
  src-self-hosted/translate_c.zig
  src/error.cpp
  src/userland.h
Labels: stage2

#4478 self-hosted libc and dynamic linker detection
  CMakeLists.txt
  build.zig
  cmake/install.cmake
  lib/std/c.zig
  lib/std/child_process.zig
  lib/std/event.zig
  lib/std/event/batch.zig
  lib/std/event/group.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/mem.zig
  lib/std/os.zig
  lib/std/os/test.zig
  lib/std/os/windows/ntdll.zig
  lib/std/process.zig
  lib/std/target.zig
  lib/std/time.zig
  src-self-hosted/c.zig
  src-self-hosted/introspect.zig
  src-self-hosted/libc_installation.zig
  src-self-hosted/stage2.zig
  src-self-hosted/util.zig
  src-self-hosted/windows_sdk.zig
  src/all_types.hpp
  src/cache_hash.cpp
  src/codegen.cpp
  src/codegen.hpp
  src/compiler.cpp
  src/compiler.hpp
  src/error.cpp
  src/error.hpp
  src/libc_installation.cpp
  src/libc_installation.hpp
  src/link.cpp
  src/main.cpp
  src/os.cpp
  src/os.hpp
  src/stage2.cpp
  src/stage2.h
  src/target.cpp
  src/target.hpp
  src/util.cpp
  src/windows_sdk.h
  src/zig_clang.h
Labels: breaking, stage1, stage2

#4460 Add an appendValues method to ArrayList to append a value n times.
  lib/std/array_list.zig
Labels: standard library

#4511 stage1/ir_print: show GenConst in trailing fahsion
  src/ir_print.cpp
Labels: stage1

#4514 remove std.io.readLine
  lib/std/io.zig
  test/standalone/guess_number/main.zig
Labels: breaking

#4509 sub-architecture annihilation
  lib/std/build.zig
  lib/std/builtin.zig
  lib/std/os/linux/tls.zig
  lib/std/target.zig
  lib/std/target/aarch64.zig
  lib/std/target/amdgpu.zig
  lib/std/target/arm.zig
  lib/std/target/avr.zig
  lib/std/target/bpf.zig
  lib/std/target/hexagon.zig
  lib/std/target/mips.zig
  lib/std/target/msp430.zig
  lib/std/target/nvptx.zig
  lib/std/target/powerpc.zig
  lib/std/target/riscv.zig
  lib/std/target/sparc.zig
  lib/std/target/systemz.zig
  lib/std/target/wasm.zig
  lib/std/target/x86.zig
  src-self-hosted/libc_installation.zig
  src-self-hosted/print_targets.zig
  src-self-hosted/stage2.zig
  src/codegen.cpp
  src/error.cpp
  src/glibc.cpp
  src/main.cpp
  src/stage2.cpp
  src/stage2.h
  src/target.cpp
  src/target.hpp
  src/zig_llvm.cpp
  src/zig_llvm.h
  test/compile_errors.zig
  test/tests.zig
  test/translate_c.zig
Labels: breaking

#4525 update std lib to integrate with libc for environ
  lib/std/c.zig
  lib/std/os.zig
  lib/std/os/test.zig
  lib/std/os/windows/bits.zig
  lib/std/process.zig
  lib/std/start.zig
  lib/std/zig/system.zig
  src/os.cpp
Labels: standard library

#4520 Format decimal 0.0 with no precision as just 0
  lib/std/fmt.zig
Labels: standard library

#4304 Add "automatic" JSON facilities
  lib/std/json.zig
Labels: standard library
