Repository ziglang/zig, pull requests merged in 2020-09, with the labels that each got.

#5999 New hashmap implementation
  lib/std/array_hash_map.zig
  lib/std/buf_set.zig
  lib/std/hash_map.zig
  lib/std/heap/general_purpose_allocator.zig
  lib/std/http/headers.zig
  lib/std/std.zig
  src-self-hosted/Module.zig
  src-self-hosted/codegen.zig
  src-self-hosted/codegen/c.zig
  src-self-hosted/link.zig
  src-self-hosted/link/Elf.zig
  src-self-hosted/liveness.zig
  src-self-hosted/translate_c.zig
  src-self-hosted/type.zig
  src-self-hosted/value.zig
  src-self-hosted/zir.zig
  src-self-hosted/zir_sema.zig
Labels: standard library

#6218 std: add fmt option to escape non-printable characters
  lib/std/fmt.zig
Labels: standard library

#6244 stage2: write out simple Mach-O object file
  src-self-hosted/codegen.zig
  src-self-hosted/link/MachO.zig
Labels: os-macos, stage2

#6232 std: Don't trust stat() size in readAllAlloc fns
  lib/std/array_list.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/test.zig
  src-self-hosted/Module.zig
  src-self-hosted/main.zig
  src-self-hosted/stage2.zig
Labels: standard library

#6265 BPF: Implement rest of pseudo instructions
  lib/std/os/linux/bpf.zig
Labels: standard library

#6268 BPF: add some more documentation
  lib/std/os/linux/bpf.zig
Labels: standard library

#6287 Zlib: Make deinit function public
  lib/std/compress/zlib.zig
Labels: standard library

#6285 Add the Linux TCP socket options
  lib/std/os/bits/linux.zig
Labels: os-linux, standard library

#6289 macho: fix bug where __text section would get overwritten
  lib/std/macho.zig
  src-self-hosted/link/MachO.zig
Labels: os-macos, stage2

#6304 std: Fix empty PriorityQueue iteration crash
  lib/std/priority_queue.zig
Labels: standard library

#6296 std: add option to use single-threaded event loop
  lib/std/event/loop.zig
Labels: standard library

#6298 std: fix errorset of std.os.seteuid/setegid
  lib/std/os.zig
Labels: standard library

#5527 Implement support for powerpc64{,le}
  lib/std/os/bits/linux.zig
  lib/std/os/bits/linux/powerpc64.zig
  lib/std/os/linux.zig
  lib/std/os/linux/powerpc64.zig
  lib/std/os/linux/tls.zig
  lib/std/special/c.zig
  lib/std/start.zig
  src/analyze.cpp
  src/target.cpp
  src/target.hpp
Labels: arch-powerpc

#6320 std: add prctl and securebits definitions for linux/C
  lib/std/c.zig
  lib/std/os.zig
  lib/std/os/bits/linux.zig
  lib/std/os/bits/linux/prctl.zig
  lib/std/os/bits/linux/securebits.zig
  lib/std/os/linux.zig
Labels: os-linux, standard library

#6333 std: Limit the read/write size on Darwin
  lib/std/os.zig
Labels: os-macos, standard library

#6331 BPF: helper definitions
  lib/std/os/linux/bpf.zig
  lib/std/os/linux/bpf/helpers.zig
  lib/std/os/linux/bpf/kern.zig
Labels: standard library

#6347 Use std.log in LibcInstallation `parse` instead of taking `stderr`
  src-self-hosted/libc_installation.zig
  src-self-hosted/stage2.zig
Labels: standard library

#6360 Two std.fmt fixes
  lib/std/fmt.zig
  src-self-hosted/translate_c.zig
Labels: standard library

#6406 ZIG_WORKAROUND_4799 is not required with LLVM 10.0.1
  README.md
Labels: docs

#6398 Revamp crypto/aes
  lib/std/crypto.zig
  lib/std/crypto/aes.zig
  lib/std/crypto/aes/aesni.zig
  lib/std/crypto/aes/soft.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/modes.zig
Labels: standard library

#6413 Make ArenaAllocator try to resize first
  lib/std/heap.zig
  lib/std/heap/arena_allocator.zig
Labels: enhancement, standard library

#6412 Make os.zig not depend on the event loop
  lib/std/event/loop.zig
  lib/std/fs/file.zig
  lib/std/net.zig
  lib/std/os.zig
Labels: standard library

#6435 Make LinearFifo not crash when discarding from empty buffer
  lib/std/fifo.zig
Labels: standard library

#6397 Fix for Windows: std.os.windows.DeleteFile()
  lib/std/fs/test.zig
  lib/std/os/windows.zig
Labels: os-windows, standard library

#6441 New std.event.Lock implementation
  lib/std/event/lock.zig
Labels: standard library

#6453 Fix std.event.Future
  lib/std/event/future.zig
  lib/std/event/lock.zig
Labels: standard library

#6416 Implements std.meta.Tuple(), implements #4607 in userland.
  lib/std/meta.zig
Labels: enhancement, standard library

#6415 Implements std.meta.ArgsTuple.
  lib/std/meta.zig
Labels: enhancement, standard library

#6450 std/crypto: make Gimli 60% faster
  lib/std/crypto/benchmark.zig
  lib/std/crypto/gimli.zig
Labels: enhancement, standard library
