Repository ziglang/zig, pull requests merged in 2020-11, with the labels that each got.

#6901 Add missing self arg in event Loop recvfrom
  lib/std/event/loop.zig
Labels: standard library

#6904 std: make std.fmt.bufPrintIntToSlice public
  lib/std/fmt.zig
Labels: standard library

#6792 Initial sparc64-linux bringup
  lib/std/os/bits/linux.zig
  lib/std/os/bits/linux/sparc64.zig
  lib/std/os/linux.zig
  lib/std/os/linux/sparc64.zig
  lib/std/os/linux/tls.zig
  lib/std/special/c.zig
  lib/std/start.zig
  lib/std/target.zig
  lib/std/target/sparc.zig
  src/stage1/analyze.cpp
  src/stage1/target.cpp
  src/stage1/target.hpp
  test/stack_traces.zig
Labels: arch-sparc64, os-linux

#6929 Fix file descriptor leak in fs.openFileZ
  lib/std/fs.zig
Labels: standard library

#6920 stage1: Fix *WithOverflow intrinsics with u0 values
  src/stage1/ir.cpp
  test/stage1/behavior/math.zig
Labels: stage1

#6932 macOS: fix linking issues on BigSur
  lib/std/zig/system.zig
  lib/std/zig/system/macos.zig
  src/Compilation.zig
  src/link.zig
  src/link/MachO.zig
Labels: os-macos

#6921 stage2: ask for more file descriptors
  lib/std/os/bits/darwin.zig
  src/main.zig
  src/stage1/os.cpp
Labels: enhancement, stage2

#6956 Another big-endian fix for Gimli
  lib/std/crypto/gimli.zig
Labels: standard library

#6982 Fix CoInitializeEx so it can take a null pointer
  lib/std/os/windows/bits.zig
  lib/std/os/windows/ole32.zig
Labels: os-windows, standard library

#6949 std.crypto: namespace constructions a bit more
  lib/std/crypto.zig
  lib/std/crypto/benchmark.zig
Labels: standard library

#6953 std/crypto: don't constrain Gimli hash output to a fixed length
  lib/std/crypto/gimli.zig
Labels: standard library

#6895 linux: add fallocate()
  lib/std/c/linux.zig
  lib/std/os/bits/linux.zig
  lib/std/os/linux.zig
  lib/std/os/linux/test.zig
Labels: standard library

#6993 stage1: Make sure union(enum(T)) is valid
  src/stage1/analyze.cpp
  test/compile_errors.zig
Labels: stage1

#6974 prctl improvements
  lib/std/os.zig
  lib/std/os/bits/linux/prctl.zig
Labels: os-linux, standard library

#6990 Re-enable system linker hack
  build.zig
  lib/std/build.zig
  src/Compilation.zig
  src/link.zig
  src/link/MachO.zig
Labels: os-macos, stage1, stage2

#6914 Fix std.ResetEvent.timedWait on darwin/macOS.
  lib/std/reset_event.zig
Labels: standard library

#6975 std: Make file locking tests less fragile
  lib/std/fs/test.zig
Labels: standard library

#6566 std: Introduce SemanticVersion data structure
  lib/std/SemanticVersion.zig
  lib/std/std.zig
Labels: standard library

#7017 Fix reduce documentation
  doc/langref.html.in
Labels: docs

#6865 Fix json parser close tracking
  lib/std/json.zig
Labels: standard library

#7044 Simple sets of commits for OpenBSD support
  lib/std/os/bits/openbsd.zig
  lib/std/reset_event.zig
  lib/std/thread.zig
Labels: os-openbsd, standard library

#7073 stage1: Avoid resolving type entry in [0]T
  src/stage1/analyze.cpp
  src/stage1/ir.cpp
  test/stage1/behavior/array.zig
Labels: stage1

#6900 Add stage2 AArch64 backend
  src/codegen.zig
  src/codegen/aarch64.zig
  src/type.zig
  test/stage2/aarch64.zig
  test/stage2/test.zig
Labels: arch-arm64, stage2

#7126 std: Make windows.ReadFile allow short reads
  lib/std/os/windows.zig
Labels: enhancement, os-windows, standard library

#7132 libstd: add more MachO consts and structs
  lib/std/macho.zig
Labels: os-macos, standard library

#7130 stage2 aarch64: add NOP instruction
  src/codegen/aarch64.zig
Labels: arch-arm64, stage2

#7002 Add mem.timingSafeEql() for constant-time array comparison
  lib/std/crypto.zig
  lib/std/crypto/bcrypt.zig
  lib/std/crypto/ghash.zig
  lib/std/crypto/poly1305.zig
  lib/std/crypto/salsa20.zig
  lib/std/crypto/utils.zig
  lib/std/mem.zig
Labels: enhancement, standard library

#6827 linuxWaitFd: make NetworkSubsystemFailed error unreachable
  lib/std/event/loop.zig
Labels: standard library

#7063 std/crypto: add ISAPv2 (ISAP-A-128a) AEAD
  lib/std/crypto.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/isap.zig
Labels: standard library

#7016 std/crypto: implement the Hash-To-Curve standard for Edwards25519
  lib/std/crypto/25519/edwards25519.zig
  lib/std/crypto/25519/field.zig
Labels: enhancement, standard library

#7117 std/crypto: use NAF for multi-scalar edwards25519 multiplication
  lib/std/crypto/25519/edwards25519.zig
Labels: standard library

#7082 std: openDirAbsolute and accessAbsolute
  lib/std/fs.zig
  lib/std/fs/test.zig
  lib/std/os.zig
Labels: standard library

#7144 stage2 aarch64: add PC relative address instructions
  src/codegen/aarch64.zig
Labels: arch-arm64, stage2

#7114 std: make meta.IntType a compile error
  doc/langref.html.in
  lib/std/meta.zig
Labels: docs, standard library

#7084 std.mem: make sliceAsBytes, etc. respect volatile
  lib/std/mem.zig
Labels: standard library

#7087 stage1: Add architecture-specific clobbers to asm()
  src/stage1/codegen.cpp
Labels: stage1

#7000 Added std.meta.fieldNames
  lib/std/meta.zig
Labels: standard library

#6598 std: expose all atomic operations from std.atomic.Int
  lib/std/atomic/int.zig
Labels: standard library

#6649 make Version.parse less strict
  lib/std/builtin.zig
  lib/std/zig/system.zig
Labels: standard library

#6434 std: add LinearFifo(...).pump(src_reader, dest_writer)
  lib/std/fifo.zig
  test/standalone/cat/main.zig
Labels: standard library

#7154 std.atomic.{Int,Bool}
  CMakeLists.txt
  lib/std/atomic.zig
  lib/std/atomic/bool.zig
  lib/std/atomic/int.zig
Labels: standard library

#7145 Change seed for Murmur2_64 from u32 to u64
  lib/std/hash/murmur.zig
Labels: standard library

#6385 std: Make C allocator respect the required alignment
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/c/dragonfly.zig
  lib/std/c/freebsd.zig
  lib/std/c/linux.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/c/windows.zig
  lib/std/heap.zig
  src/stage1/codegen.cpp
Labels: enhancement, standard library

#7118 edwards25519 - skip useless operations and duplicate lookup table
  lib/std/crypto/25519/edwards25519.zig
Labels: standard library

#7210 std/crypto - edwards25519 precomp: prefer doublings over adds
  lib/std/crypto/25519/edwards25519.zig
Labels: standard library

#7192 std: use mem.asBytes in Ip4Address.parse so it works at comptime
  lib/std/net.zig
Labels: standard library

#7231 stage2: Hello, Silicon!\n
  lib/std/macho.zig
  src/codegen.zig
  src/codegen/aarch64.zig
  src/link.zig
  src/link/MachO.zig
  src/link/MachO/CodeSignature.zig
  src/main.zig
  test/stage2/aarch64.zig
Labels: arch-arm64, arch-x86_64, os-macos, stage2

#6559 Add Reader.readAllArrayListAligned for ArrayLists of arbitrary alignment
  lib/std/fs/file.zig
  lib/std/io/reader.zig
Labels: standard library

#7248 std: Avoid deadlock in the signal handler
  lib/std/debug.zig
Labels: standard library

#7226 std.meta: add assumeSentinel
  lib/std/debug.zig
  lib/std/fs.zig
  lib/std/meta.zig
  lib/std/net.zig
  lib/std/os.zig
  lib/std/os/linux/vdso.zig
  lib/std/zig/system.zig
Labels: standard library

#7116 stage2 ARM: add basic arithmetic instructions
  src/codegen.zig
  test/stage2/arm.zig
Labels: arch-arm32, stage2

#7259 fix memory leak in BufMap
  lib/std/buf_map.zig
Labels: standard library
