Repository ziglang/zig, pull requests merged in 2020-05, with the labels that each got.

#5058 correct usages of std.fs.dir.DeleteFileError
  lib/std/fs.zig
  lib/std/fs/test.zig
Labels: standard library

#5249 fix behavior test with --test-evented-io on windows
  lib/std/child_process.zig
  lib/std/debug.zig
  lib/std/dynamic_library.zig
  lib/std/event/loop.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/path.zig
  lib/std/fs/test.zig
  lib/std/io.zig
  lib/std/net.zig
  lib/std/os.zig
  lib/std/os/windows.zig
  lib/std/pdb.zig
  lib/std/reset_event.zig
  src-self-hosted/test.zig
Labels: breaking, standard library

#5257 Add scoped typedef to translate-c
  src-self-hosted/translate_c.zig
  test/run_translated_c.zig
Labels: translate-c

#5287 fix copy/paste error in AllocWithOptionaPayload
  lib/std/mem.zig
Labels: standard library

#5296 std: fix RTLD_ constants on OSX
  lib/std/os/bits/darwin.zig
Labels: os-macos, standard library

#4892 mem.zeroes - add sentinel terminated array support
  lib/std/mem.zig
Labels: standard library

#5308 mem.eql need slice type
  doc/langref.html.in
Labels: docs

#5118 fix json.WriteStream.emitJson
  lib/std/json.zig
  lib/std/json/write_stream.zig
Labels: standard library

#5321 Add helper functions and docstrings to ascii.zig
  lib/std/ascii.zig
Labels: standard library

#5254 Apply naming conventions of structs to files
  doc/langref.html.in
Labels: docs

#5175 std: add io.MultiOutStream
  lib/std/io.zig
  lib/std/io/multi_out_stream.zig
Labels: standard library

#5020 docs: search perf
  lib/std/special/docs/index.html
  lib/std/special/docs/main.js
Labels: docs

#5032 Translate C: Redo Add comment containing c source location for failed decls.
  lib/std/zig/render.zig
  src-self-hosted/translate_c.zig
Labels: translate-c

#5329 macos: use realpath$DARWIN_EXTSN
  lib/std/c.zig
  lib/std/c/darwin.zig
Labels: os-macos

#5310 Creates `std.ascii.control_code` that contains the C0 control codes
  lib/std/ascii.zig
Labels: standard library

#5231 Add mechanism for extracting preopens from the runtime
  lib/std/fs.zig
  lib/std/fs/wasi.zig
Labels: os-wasi

#5361 linux: remove duplicated fields
  lib/std/os/bits/linux.zig
Labels: os-linux, standard library

#5057 stage1: fix assert fail on opaque fn ptr param
  src/analyze.cpp
  src/analyze.hpp
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#5164 A couple of helpers for streams that I've found helpful
  lib/std/io/in_stream.zig
Labels: standard library

#5303 Add/fix missing WASI functionality to pass libstd tests
  build.zig
  ci/azure/linux_script
  lib/std/build.zig
  lib/std/fmt.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/get_app_data_dir.zig
  lib/std/fs/path.zig
  lib/std/fs/test.zig
  lib/std/fs/wasi.zig
  lib/std/io/test.zig
  lib/std/net/test.zig
  lib/std/os.zig
  lib/std/os/bits/wasi.zig
  lib/std/os/test.zig
  lib/std/packed_int_array.zig
  lib/std/process.zig
  lib/std/testing.zig
  lib/std/time.zig
  lib/std/zig/parser_test.zig
  test/stage1/behavior.zig
  test/stage1/behavior/align.zig
  test/stage1/behavior/shuffle.zig
  test/stage1/behavior/vector.zig
  test/tests.zig
Labels: os-wasi, standard library

#5378 improve std.zig.parse performance using flat arrays for AST nodes and tokens
  doc/docgen.zig
  lib/std/heap/arena_allocator.zig
  lib/std/linked_list.zig
  lib/std/rand.zig
  lib/std/testing.zig
  lib/std/zig/ast.zig
  lib/std/zig/parse.zig
  lib/std/zig/parser_test.zig
  lib/std/zig/render.zig
  lib/std/zig/tokenizer.zig
  src-self-hosted/clang.zig
  src-self-hosted/main.zig
  src-self-hosted/translate_c.zig
  src/analyze.cpp
  src/ir.cpp
Labels: breaking, enhancement, optimization, stage2

#5438 More vector support in std.meta
  lib/std/meta.zig
Labels: standard library

#5440 Make align expr on fns a compile error in Wasm
  src/analyze.cpp
  test/compile_errors.zig
  test/stage1/behavior/align.zig
Labels: arch-wasm32

#5366 Add include dirs to translate-c (close #5098)
  lib/std/build/translate_c.zig
Labels: standard library, zig build system

#5184 Extern functions are now evaluated to undefined values at comptime in TypeOf calls.
  src/ir.cpp
  test/stage1/behavior.zig
  test/stage1/behavior/bugs/4328.zig
Labels: stage1

#5477 Fix WSARecvFrom signature
  lib/std/os/windows/ws2_32.zig
Labels: os-windows, standard library

#5478 linux: fix IOSQE_BIT decl and io_uring_sqe flags
  lib/std/os/bits/linux.zig
Labels: os-linux, standard library

#5491 stage1: fix unresolved inferred error sets
  src/ir.cpp
  test/stage1/behavior.zig
  test/stage1/behavior/bugs/5487.zig
Labels: stage1
