Repository ziglang/zig, pull requests merged in 2020-03, with the labels that each got.

#4586 Fill out windows PEB definition
  lib/std/os/windows/bits.zig
Labels: os-windows, standard library

#4585 target: Implement OS version detection for Windows
  lib/std/os/windows/bits.zig
  lib/std/os/windows/ntdll.zig
  lib/std/zig/system.zig
Labels: os-windows, standard library

#4601 Allow wrapping in VDSO lookup
  lib/std/os/linux/vdso.zig
Labels: os-linux, os-windows, standard library

#4618 improvements to std.fs, std.os
  doc/docgen.zig
  lib/std/build.zig
  lib/std/build/write_file.zig
  lib/std/c.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/watch.zig
  lib/std/os.zig
  lib/std/os/linux.zig
  lib/std/os/test.zig
  lib/std/os/windows.zig
  src-self-hosted/compilation.zig
  src-self-hosted/test.zig
  test/cli.zig
Labels: breaking, standard library

#4242 Mobile support in generated documentation
  lib/std/special/docs/index.html
  lib/std/special/docs/main.js
Labels: docs

#4633 Fix formatting of i1 values
  lib/std/fmt.zig
  lib/std/math.zig
Labels: standard library

#4636 Translate-c macro comma operator
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4637 Translate-c demote struct to opaque if unable to translate field type
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4648 stage1: fix regression
  src/analyze.cpp
Labels: stage1

#4653 std: fix sendfile on macOS and FreeBSD
  lib/std/c/darwin.zig
  lib/std/c/freebsd.zig
  lib/std/os.zig
Labels: os-freebsd, os-macos, standard library

#4651 std: Nicer way to access the PEB
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
Labels: os-windows, standard library

#4660 Translate-c more macro ops
  src-self-hosted/translate_c.zig
  test/translate_c.zig
Labels: translate-c

#4664 llvm10/stage1: fix compile error on macOS Xcode 11.4
  src/zig_clang.cpp
Labels: stage1

#4430 Add UTF-8 to UTF-16LE literal conversion to fix #4325
  lib/std/unicode.zig
Labels: standard library

#4689 std: One more cpuid fix
  lib/std/zig/system/x86.zig
Labels: standard library

#4690 Translate-c fixes
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/translate_c.zig
Labels: translate-c

#4687 Fix grammar from "C pointers cannot point opaque types"
  src/ir.cpp
  test/compile_errors.zig
Labels: stage1

#4614 ir: Create usize result_loc for array subscript expr
  src/ir.cpp
  test/compile_errors.zig
  test/stage1/behavior/array.zig
Labels: stage1

#4692 std: add some definitions for netlink sockets
  lib/std/os/bits/linux.zig
  lib/std/os/bits/linux/netlink.zig
Labels: os-linux, standard library

#4702 std: Fix detection of Linux kernel version
  lib/std/os/bits/linux.zig
  lib/std/zig/system.zig
Labels: os-linux, standard library

#4703 Translate-c improvements
  src-self-hosted/clang.zig
  src-self-hosted/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/translate_c.zig
Labels: translate-c

#4579 add allocSentinel function
  lib/std/mem.zig
Labels: standard library

#4706 std: simplify format enum-literals
  lib/std/fmt.zig
Labels: standard library

#4710 rework I/O stream abstractions
  doc/docgen.zig
  doc/langref.html.in
  lib/std/atomic/queue.zig
  lib/std/buffer.zig
  lib/std/build.zig
  lib/std/build/emit_raw.zig
  lib/std/build/run.zig
  lib/std/child_process.zig
  lib/std/coff.zig
  lib/std/debug.zig
  lib/std/debug/leb128.zig
  lib/std/dwarf.zig
  lib/std/elf.zig
  lib/std/event/group.zig
  lib/std/event/lock.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/heap.zig
  lib/std/heap/logging_allocator.zig
  lib/std/io.zig
  lib/std/io/bit_in_stream.zig
  lib/std/io/bit_out_stream.zig
  lib/std/io/buffered_atomic_file.zig
  lib/std/io/buffered_in_stream.zig
  lib/std/io/buffered_out_stream.zig
  lib/std/io/c_out_stream.zig
  lib/std/io/counting_out_stream.zig
  lib/std/io/fixed_buffer_stream.zig
  lib/std/io/in_stream.zig
  lib/std/io/out_stream.zig
  lib/std/io/peek_stream.zig
  lib/std/io/seekable_stream.zig
  lib/std/io/serialization.zig
  lib/std/io/stream_source.zig
  lib/std/io/test.zig
  lib/std/json.zig
  lib/std/json/write_stream.zig
  lib/std/net.zig
  lib/std/net/test.zig
  lib/std/os.zig
  lib/std/os/test.zig
  lib/std/os/windows.zig
  lib/std/pdb.zig
  lib/std/progress.zig
  lib/std/special/build_runner.zig
  lib/std/std.zig
  lib/std/zig/ast.zig
  lib/std/zig/parser_test.zig
  lib/std/zig/render.zig
  lib/std/zig/system.zig
  src-self-hosted/libc_installation.zig
  src-self-hosted/print_targets.zig
  src-self-hosted/stage2.zig
  test/compare_output.zig
  test/standalone/guess_number/main.zig
  test/tests.zig
Labels: breaking

#4628 std.fmt.format — with streams
  lib/std/buffer.zig
  lib/std/builtin.zig
  lib/std/fifo.zig
  lib/std/fmt.zig
  lib/std/http/headers.zig
  lib/std/io/out_stream.zig
  lib/std/json.zig
  lib/std/math/big/int.zig
  lib/std/net.zig
  lib/std/os/uefi.zig
  src-self-hosted/dep_tokenizer.zig
  src-self-hosted/translate_c.zig
Labels: standard library

#4743 fix Serializer to work with new OutStream API
  lib/std/io/serialization.zig
Labels: standard library

#4735 zig build system: correctly handle multiple output artifacts
  doc/docgen.zig
  lib/std/build.zig
  lib/std/c.zig
  lib/std/fs.zig
  lib/std/mem.zig
  lib/std/os.zig
  lib/std/os/linux.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  src/codegen.cpp
  src/link.cpp
  src/main.cpp
Labels: breaking

#4751 Change the default stdin behavior of RunStep to .Inherit
  lib/std/build/run.zig
Labels: breaking

#4753 fix a couple sockfds to be fd_t rather than i32
  lib/std/os.zig
Labels: os-windows, standard library

#4759 ir: More changes to sentinel-terminated const arrays
  src/analyze.cpp
  src/codegen.cpp
  src/ir.cpp
  test/stage1/behavior/array.zig
Labels: stage1

#4752 slicing with comptime start and end indexes results in pointer-to-array
  doc/langref.html.in
  lib/std/crypto/aes.zig
  lib/std/crypto/blake2.zig
  lib/std/crypto/chacha20.zig
  lib/std/crypto/md5.zig
  lib/std/crypto/poly1305.zig
  lib/std/crypto/sha1.zig
  lib/std/crypto/sha2.zig
  lib/std/crypto/sha3.zig
  lib/std/crypto/x25519.zig
  lib/std/fmt.zig
  lib/std/fs.zig
  lib/std/hash/auto_hash.zig
  lib/std/hash/siphash.zig
  lib/std/hash/wyhash.zig
  lib/std/json.zig
  lib/std/mem.zig
  lib/std/meta.zig
  lib/std/meta/trait.zig
  lib/std/net.zig
  lib/std/os/windows.zig
  lib/std/rand.zig
  lib/std/unicode.zig
  src-self-hosted/stage2.zig
  src-self-hosted/translate_c.zig
  src/all_types.hpp
  src/analyze.cpp
  src/analyze.hpp
  src/codegen.cpp
  src/ir.cpp
  test/compare_output.zig
  test/compile_errors.zig
  test/runtime_safety.zig
  test/stage1/behavior/align.zig
  test/stage1/behavior/cast.zig
  test/stage1/behavior/eval.zig
  test/stage1/behavior/misc.zig
  test/stage1/behavior/pointers.zig
  test/stage1/behavior/ptrcast.zig
  test/stage1/behavior/slice.zig
  test/stage1/behavior/struct.zig
Labels: breaking

#4731 std: Multithreaded-aware panic handler
  lib/std/debug.zig
Labels: standard library

#4783 debug: Correct version check in debug_line parser
  lib/std/dwarf.zig
Labels: standard library

#4793 Netbsd forever
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/c/netbsd.zig
  lib/std/debug.zig
  lib/std/fs.zig
  lib/std/os.zig
  lib/std/os/bits/netbsd.zig
  lib/std/thread.zig
  src/link.cpp
  src/os.cpp
Labels: os-netbsd

#4807 std: Minor changes to TLS handling
  lib/std/os/linux/tls.zig
  lib/std/start.zig
  lib/std/thread.zig
Labels: os-linux, standard library

#4811 self-hosted: use fs.selfExePathAlloc
  lib/std/fs.zig
  src-self-hosted/introspect.zig
Labels: standard library

#4836 Fix typo in Serializer declaration
  lib/std/io/serialization.zig
Labels: standard library

#4843 tcpConnectToHost - fixed compilation error
  lib/std/net.zig
Labels: standard library

#4855 compiler-rt: Implement all the shift builtins
  lib/std/special/compiler_rt.zig
  lib/std/special/compiler_rt/ashldi3_test.zig
  lib/std/special/compiler_rt/ashlti3.zig
  lib/std/special/compiler_rt/ashlti3_test.zig
  lib/std/special/compiler_rt/ashrdi3_test.zig
  lib/std/special/compiler_rt/ashrti3.zig
  lib/std/special/compiler_rt/ashrti3_test.zig
  lib/std/special/compiler_rt/lshrdi3_test.zig
  lib/std/special/compiler_rt/lshrti3.zig
  lib/std/special/compiler_rt/lshrti3_test.zig
  lib/std/special/compiler_rt/shift.zig
Labels: standard library

#4861 std: fix compile error since WinsockError was changed
  lib/std/os/windows.zig
Labels: os-windows, standard library

#4860 ir: Avoid constant-folding ptr to sentinels
  src/ir.cpp
  test/stage1/behavior/array.zig
Labels: stage1

#4858 std: mem span functions should be able to take an optional pointer
  lib/std/mem.zig
Labels: standard library

#4851 mem.zeroes .Array improvements
  lib/std/mem.zig
Labels: standard library

#4867 compiler-rt: implement clear_cache for arm32-linux
  lib/std/special/compiler_rt.zig
  lib/std/special/compiler_rt/clear_cache.zig
Labels: arch-arm32, os-linux

#4876 std: linux syscall numbers are now an extensible enum
  lib/std/os.zig
  lib/std/os/bits/linux/arm-eabi.zig
  lib/std/os/bits/linux/arm64.zig
  lib/std/os/bits/linux/i386.zig
  lib/std/os/bits/linux/mipsel.zig
  lib/std/os/bits/linux/riscv64.zig
  lib/std/os/bits/linux/x86_64.zig
  lib/std/os/linux.zig
  lib/std/os/linux/arm-eabi.zig
  lib/std/os/linux/arm64.zig
  lib/std/os/linux/i386.zig
  lib/std/os/linux/mipsel.zig
  lib/std/os/linux/riscv64.zig
  lib/std/os/linux/tls.zig
  lib/std/os/linux/x86_64.zig
  lib/std/special/compiler_rt/clear_cache.zig
Labels: os-linux, standard library

#4873 Fix std.fifo.LinearFifo
  lib/std/fifo.zig
Labels: standard library

#4543 std.json improvements
  lib/std/json.zig
  lib/std/json/write_stream.zig
Labels: standard library
