Repository ziglang/zig, pull requests merged in 2020-10, with the labels that each got.

#6461 stage1: Fix @Type(.Enum) with invalid tag_type
  src/stage1/ir.cpp
  test/compile_errors.zig
Labels: stage1

#6455 add runDetached to event loop
  lib/std/event/loop.zig
Labels: standard library

#6419 std.fmt: add comptimePrint
  lib/std/fmt.zig
Labels: enhancement, standard library

#6402 Implement @Type for Fn
  lib/std/builtin.zig
  src/stage1/ir.cpp
  test/compile_errors.zig
  test/stage1/behavior/type.zig
  test/stage1/behavior/type_info.zig
Labels: stage1

#6484 Some windows fixes
  lib/libc/mingw/lib32/user32.def
  src/mingw.zig
Labels: os-windows

#6494 Emit reloc patch
  lib/std/build.zig
  src/Compilation.zig
  src/link.zig
  src/link/Elf.zig
  src/main.zig
Labels: enhancement, stage1

#6506 Print error when running `zig test/run` without a source file
  src/main.zig
Labels: stage1

#6518 Reintroduce progress display when compiling C files
  src/Compilation.zig
Labels: enhancement

#6490 std: Add pow(a,b) for big ints
  lib/std/math/big/int.zig
  lib/std/math/big/int_test.zig
Labels: enhancement, standard library

#6454 std/crypto: implement the HKDF construction
  lib/std/crypto.zig
  lib/std/crypto/hkdf.zig
Labels: enhancement, standard library

#6463 std/crypto: add GHASH implementation
  lib/std/crypto.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/ghash.zig
  lib/std/crypto/poly1305.zig
Labels: enhancement, standard library

#6476 Link basic MachO executables with stage2
  lib/std/macho.zig
  src/codegen.zig
  src/link/MachO.zig
  test/stage2/test.zig
Labels: os-macos, stage2

#6496 std: implement {get, set}rlimit for linux
  lib/std/c.zig
  lib/std/c/linux.zig
  lib/std/os.zig
  lib/std/os/bits/linux.zig
  lib/std/os/linux.zig
  lib/std/os/test.zig
Labels: os-linux, standard library

#6558 stage1: Implement @reduce builtin for vector types
  lib/std/builtin.zig
  src/stage1/all_types.hpp
  src/stage1/codegen.cpp
  src/stage1/ir.cpp
  src/stage1/ir_print.cpp
  src/zig_llvm.cpp
  src/zig_llvm.h
  test/stage1/behavior/vector.zig
Labels: stage1

#6472 Add a few missing deallocations of temporaries to stage1
  src/stage1/analyze.cpp
  src/stage1/codegen.cpp
  src/stage1/ir.cpp
  src/stage1/os.cpp
Labels: stage1

#6591 std/crypto/25519: faster (mod 2^255-19) square root computation
  lib/std/crypto/25519/field.zig
Labels: standard library

#6585 stage1: improve error messages for missing `try` statements
  src/stage1/ir.cpp
  test/compile_errors.zig
Labels: stage1

#6505 add WaitGroup to std.event
  lib/std/event.zig
  lib/std/event/loop.zig
  lib/std/event/wait_group.zig
Labels: enhancement, standard library

#6599 stage2: Remove obsolete addPadding fn and callsites from MachO linker
  src/link/MachO.zig
Labels: os-macos, stage2

#6595 std.fmt.comptimePrint: Return null terminated string
  lib/std/fmt.zig
Labels: standard library

#6547 std/crypto/ghash: add pmull support on aarch64
  lib/std/crypto/ghash.zig
Labels: enhancement, standard library

#6516 std: Make file copy ops use zero-copy mechanisms
  lib/std/c/darwin.zig
  lib/std/fs.zig
  lib/std/os.zig
Labels: enhancement, standard library

#6619 include compiler_rt and c for wasm static libraries
  src/Compilation.zig
  src/link/Wasm.zig
Labels: stage2

#6637 Update WASI preopens doc section to use GPA
  doc/langref.html.in
Labels: docs, os-wasi

#6658 Rename .macosx to .macos
  lib/std/c.zig
  lib/std/debug.zig
  lib/std/dynamic_library.zig
  lib/std/event/loop.zig
  lib/std/fs.zig
  lib/std/fs/get_app_data_dir.zig
  lib/std/fs/test.zig
  lib/std/fs/watch.zig
  lib/std/os.zig
  lib/std/os/bits.zig
  lib/std/os/test.zig
  lib/std/packed_int_array.zig
  lib/std/process.zig
  lib/std/special/compiler_rt/clear_cache.zig
  lib/std/target.zig
  lib/std/time.zig
  lib/std/zig/cross_target.zig
  lib/std/zig/system.zig
  src/codegen/llvm.zig
  src/link/MachO.zig
  src/target.zig
  src/type.zig
  src/zig_llvm.cpp
  test/stack_traces.zig
  test/stage2/test.zig
  test/tests.zig
Labels: breaking

#6643 std/crypto: add a vectorized ChaCha20 implementation
  lib/std/crypto/chacha20.zig
Labels: standard library

#6651 Force comptime on comptimePrint
  lib/std/fmt.zig
Labels: standard library

#6650 stage2: enable incremental MachO linking
  src/link/MachO.zig
  test/stage2/test.zig
Labels: os-macos, stage2

#6652 Event Channel: updated linked list node initialization
  lib/std/event/channel.zig
Labels: standard library

#6655 Integrate std.time.sleep with the event loop
  lib/std/auto_reset_event.zig
  lib/std/event/loop.zig
  lib/std/std.zig
  lib/std/time.zig
Labels: standard library

#6447 std: move std.meta.refAllDecls to std.testing
  lib/std/build.zig
  lib/std/build/emit_raw.zig
  lib/std/crypto.zig
  lib/std/math.zig
  lib/std/meta.zig
  lib/std/rand.zig
  lib/std/std.zig
  lib/std/target.zig
  lib/std/testing.zig
  lib/std/zig.zig
Labels: standard library

#6616 Darwin rusage
  lib/std/os/bits/darwin.zig
  lib/std/os/bits/linux.zig
Labels: os-macos, standard library

#6549 std/crypto/hmac: remove HmacBlake2s256 definition
  lib/std/crypto/hmac.zig
Labels: standard library

#6638 add minimal openbsd support
  lib/std/c.zig
  lib/std/c/openbsd.zig
  lib/std/debug.zig
  lib/std/dynamic_library.zig
  lib/std/event/loop.zig
  lib/std/fs.zig
  lib/std/fs/get_app_data_dir.zig
  lib/std/fs/watch.zig
  lib/std/os.zig
  lib/std/os/bits.zig
  lib/std/os/bits/openbsd.zig
  lib/std/os/openbsd.zig
  lib/std/packed_int_array.zig
  lib/std/process.zig
  lib/std/target.zig
  lib/std/zig/cross_target.zig
  src/libc_installation.zig
  src/link/Elf.zig
  src/stage1.zig
  src/stage1/os.cpp
  src/stage1/os.hpp
  src/target.zig
Labels: os-openbsd

#6686 BYOS support for system.isatty(fd: fd_t);
  lib/std/os.zig
Labels: enhancement, os-bring-your-own

#6728 Fix invalid call to dupePkg in build.zig
  lib/std/build.zig
Labels: standard library, zig build system

#6742 Update Documentation to use -O instead
  doc/langref.html.in
Labels: docs

#6733 Add import for std.io in json.zig
  lib/std/json.zig
Labels: standard library

#6738 Fix incorrect equations in langref
  doc/langref.html.in
Labels: docs

#6740 std: Implement featureSetHasAny/featureSetHasAll
  lib/std/target.zig
  lib/std/zig/cross_target.zig
Labels: standard library

#6764 Change --enable-valgrind flag to -fvalgrind in std/build.zig
  lib/std/build.zig
Labels: zig build system

#6744 stage1: Implement `@intCast` between vectors
  doc/docgen.zig
  doc/langref.html.in
  src/stage1/codegen.cpp
  src/stage1/ir.cpp
  test/compile_errors.zig
  test/runtime_safety.zig
  test/stage1/behavior/cast.zig
Labels: stage1

#6719 std/crypto/25519: add support for batch Ed25519 signature verification
  lib/std/crypto/25519/ed25519.zig
  lib/std/crypto/25519/edwards25519.zig
  lib/std/crypto/25519/scalar.zig
  lib/std/crypto/benchmark.zig
Labels: standard library

#6786 Fix a typo (s/multple/multiple/)
  lib/std/crypto/aes/aesni.zig
  lib/std/crypto/aes/armcrypto.zig
  lib/std/crypto/aes/soft.zig
Labels: standard library

#6791 cc: fix regression on macOS after adding libc headers
  src/Compilation.zig
Labels: os-macos

#6788 make selfExePath() compile on OpenBSD
  lib/std/fs.zig
Labels: standard library

#6795 test runner: use the correct number in leak report
  lib/std/special/test_runner.zig
Labels: standard library

#6809 std/crypto: add (X)Salsa20 and NaCl boxes
  lib/std/crypto.zig
  lib/std/crypto/25519/ed25519.zig
  lib/std/crypto/25519/x25519.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/salsa20.zig
Labels: standard library

#6805 openbsd: make dl_phdr_info cross arches
  lib/std/elf.zig
  lib/std/os/bits/openbsd.zig
Labels: os-openbsd, standard library

#6796 std/crypto: add the bcrypt password hashing function
  lib/std/crypto.zig
  lib/std/crypto/bcrypt.zig
Labels: standard library

#6782 std/crypto: vectorize BLAKE3
  lib/std/crypto/blake3.zig
Labels: optimization, standard library

#6787 Make lastIndexOf use the same cut-off between BMH as indexOf
  lib/std/mem.zig
Labels: standard library

#6776 fix type mismatch in std.net.StreamServer
  lib/std/net.zig
Labels: standard library

#6761 Format null type in std.fmt
  lib/std/fmt.zig
Labels: standard library

#6842 std: Apple Silicon: no fstat$INODE64 symbol found
  lib/std/c.zig
  lib/std/c/darwin.zig
Labels: arch-arm64, os-macos, standard library

#6836 std/crypto: adjust aesni parallelism to CPU models
  lib/std/crypto/aes/aesni.zig
Labels: standard library

#6807 stage1: Correctly generated optional constant values
  src/stage1/ir.cpp
  test/stage1/behavior/type_info.zig
Labels: stage1

#6863 std: Better handling of type values in expectEqual
  lib/std/testing.zig
Labels: standard library

#6857 stage1: Fix small bug in pointer type analysis
  src/stage1/analyze.cpp
  test/stage1/behavior.zig
  test/stage1/behavior/bugs/6850.zig
Labels: stage1

#6862 std/math: add support for vectors to rotl()/rotr()
  lib/std/math.zig
Labels: standard library

#6852 std: set page size to 16KB for aarch64 macos
  lib/std/mem.zig
Labels: arch-arm64, os-macos, standard library

#6859 std/crypto: vectorize Salsa20
  lib/std/crypto/salsa20.zig
Labels: standard library

#6849 Changed "macosx" to "macos" in support os to better relfect the output of…
  doc/langref.html.in
Labels: docs

#6801 make addBuildOption append type
  lib/std/build.zig
Labels: zig build system

#6819 std/crypto/blake2b: allow the initial output length to be set
  lib/std/crypto/blake2.zig
Labels: standard library

#6763 panic when empty string passed as dest_rel_path to addInstallFileWithDir
  lib/std/build.zig
Labels: zig build system

#6654 stage2 ARM: more stuff
  src/codegen.zig
  src/codegen/arm.zig
Labels: arch-arm32, arch-arm64, stage2

#6811 stage1: Error out when trying to execute `unreachable`
  doc/langref.html.in
  src/stage1/ir.cpp
  test/compile_errors.zig
Labels: stage1

#6645 fix #3237: resolve undefined symbol _DllMainCRTStartup
  src/link/Coff.zig
Labels: os-windows, stage2

#6660 Stage2 switch and package imports
  src/Compilation.zig
  src/Module.zig
  src/RangeSet.zig
  src/astgen.zig
  src/codegen.zig
  src/ir.zig
  src/liveness.zig
  src/main.zig
  src/test.zig
  src/type.zig
  src/value.zig
  src/zir.zig
  src/zir_sema.zig
  test/stage2/test.zig
Labels: stage2
