Repository ziglang/zig, pull requests merged in 2021-01, with the labels that each got.

#7640 Don't process.exit() on invalid option use .markInvalidUserInput
  lib/std/build.zig
Labels: zig build system

#7632 macho: unblock stage2 on 32bit platforms
  src/link/MachO.zig
  src/link/MachO/CodeSignature.zig
  src/link/MachO/DebugSymbols.zig
  src/link/MachO/Trie.zig
  src/link/MachO/imports.zig
Labels: stage2

#7634 Add PackedIntArray .initAllTo function
  lib/std/packed_int_array.zig
Labels: standard library

#7619 Fix ssize_t definition
  src/stage1/os.cpp
Labels: stage1

#7113 stage2 AArch64: logicalShiftedRegister
  src/codegen.zig
  src/codegen/aarch64.zig
Labels: arch-arm64, stage2

#7506 zig cc: detect framework include paths when native
  lib/libc/include/aarch64-macos-gnu/libkern/OSAtomic.h
  lib/libc/include/aarch64-macos-gnu/libkern/OSSpinLockDeprecated.h
  lib/libc/include/x86_64-macos-gnu/libkern/OSAtomic.h
  lib/libc/include/x86_64-macos-gnu/libkern/OSSpinLockDeprecated.h
  lib/std/zig/system.zig
  src/Compilation.zig
  src/main.zig
Labels: os-macos, stage2, zig cc

#7642 stage1: Use correct format specifier for size_t parameters
  src/stage1/os.hpp
Labels: os-windows, stage1

#7647 stage2: comptime function calls and inline function calls
  build.zig
  src/Compilation.zig
  src/Module.zig
  src/astgen.zig
  src/codegen.zig
  src/codegen/c.zig
  src/codegen/wasm.zig
  src/config.zig.in
  src/link/Elf.zig
  src/link/MachO/DebugSymbols.zig
  src/llvm_backend.zig
  src/main.zig
  src/value.zig
  src/zir.zig
  src/zir_sema.zig
  test/stage2/test.zig
  test/stage2/zir.zig
Labels: enhancement, stage2

#7681 stage2: basic fn args for aarch64
  src/codegen.zig
  src/link/MachO.zig
  test/stage2/aarch64.zig
Labels: arch-arm64, os-linux, os-macos, stage2

#7678 Improve uring definitions
  lib/std/os/bits/linux.zig
  lib/std/os/linux/io_uring.zig
Labels: os-linux, standard library

#7684 Fix off-by-one error in SinglyLinkedList.len() and add associated tests
  lib/std/linked_list.zig
Labels: standard library

#7651 Allow dollar sign $ in identifiers in translate-c
  lib/std/c/tokenizer.zig
  test/run_translated_c.zig
Labels: translate-c

#7692 freebsd, netbsd, dragonfly: add struct timeval
  lib/std/os/bits/dragonfly.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/bits/netbsd.zig
Labels: os-dragonfly, os-freebsd, os-netbsd, standard library

#7719 Want native headers when linking with frameworks
  src/main.zig
Labels: os-macos

#7715 builder: propagate env_map for child processes
  lib/std/build.zig
Labels: zig build system

#7571 Add compileError message for StringHashMap in AutoHashMap
  lib/std/hash_map.zig
Labels: standard library

#7713 added mem.containsAtLeast
  lib/std/mem.zig
Labels: standard library

#7723 stage2: Implicitly enable --eh_frame_hdr when compiling c/c++ files
  src/main.zig
Labels: stage2, zig cc

#7725 stage2: initial implementation of control flow in LLVM backend + TZIR printing
  src/codegen/llvm.zig
  src/codegen/llvm/bindings.zig
  src/test.zig
  src/zir.zig
  test/stage2/llvm.zig
Labels: stage2

#7729 Remove deprecated stream aliases
  CMakeLists.txt
  doc/langref.html.in
  lib/std/array_list.zig
  lib/std/fifo.zig
  lib/std/fs/file.zig
  lib/std/heap/logging_allocator.zig
  lib/std/io.zig
  lib/std/io/bit_in_stream.zig
  lib/std/io/bit_out_stream.zig
  lib/std/io/bit_reader.zig
  lib/std/io/bit_writer.zig
  lib/std/io/buffered_atomic_file.zig
  lib/std/io/buffered_in_stream.zig
  lib/std/io/buffered_out_stream.zig
  lib/std/io/buffered_reader.zig
  lib/std/io/buffered_writer.zig
  lib/std/io/c_out_stream.zig
  lib/std/io/counting_out_stream.zig
  lib/std/io/counting_writer.zig
  lib/std/io/find_byte_writer.zig
  lib/std/io/fixed_buffer_stream.zig
  lib/std/io/in_stream.zig
  lib/std/io/multi_out_stream.zig
  lib/std/io/multi_writer.zig
  lib/std/io/out_stream.zig
  lib/std/io/peek_stream.zig
  lib/std/io/stream_source.zig
  lib/std/json.zig
  lib/std/pdb.zig
  lib/std/zig/render.zig
  src/main.zig
Labels: breaking, standard library

#7067 update path.join to recognize any separators that isSep does
  lib/std/fs/path.zig
Labels: standard library

#7134 The std.fs.Watch rewrite PR
  lib/std/fs/watch.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/windows.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
Labels: standard library

#7146 Stage2 begin implementing container types
  src/Module.zig
  src/astgen.zig
  src/type.zig
  src/type/Enum.zig
  src/type/Struct.zig
  src/type/Union.zig
  src/value.zig
  src/zir.zig
  src/zir_sema.zig
Labels: stage2

#7124 std: Decouple network streams from fs.File
  lib/std/net.zig
  lib/std/net/test.zig
Labels: enhancement, standard library

#7171 os/bits: add the termios_c_cc bits
  lib/std/os/bits/linux.zig
Labels: standard library

#7195 A win32-api proposal, implemented for user32.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/user32.zig
Labels: accepted, os-windows, proposal, standard library

#7200 Type coercion for pointers to anon literals
  src/stage1/ir.cpp
  test/compile_errors.zig
  test/stage1/behavior/array.zig
  test/stage1/behavior/slice.zig
  test/stage1/behavior/struct.zig
  test/stage1/behavior/union.zig
Labels: stage1

#7297 Add std.fmt.formatDuration and std.fmt.duration
  lib/std/fmt.zig
Labels: standard library

#7714 macos: reimplement OS version detection
  lib/std/target.zig
  lib/std/zig/system.zig
  lib/std/zig/system/macos.zig
Labels: os-macos

#7753 Move fmt.testFmt to testing.expectFmt
  lib/std/SemanticVersion.zig
  lib/std/fmt.zig
  lib/std/testing.zig
  lib/std/zig/fmt.zig
Labels: standard library

#7731 stage2: lay the groundwork in prep for extern fn
  src/Module.zig
  src/codegen.zig
  src/link/Coff.zig
  src/link/Elf.zig
  src/link/MachO.zig
  src/link/Wasm.zig
Labels: stage2

#7746 macho: extern functions come to MachO!
  src/codegen.zig
  src/link/MachO.zig
  src/link/MachO/DebugSymbols.zig
  src/link/MachO/imports.zig
  test/stage2/aarch64.zig
  test/stage2/test.zig
Labels: arch-arm64, arch-x86_64, os-macos, stage2

#7762 std.os.uefi.protocols.FileProtocol: fix and expose get_position, set_position
  lib/std/os/uefi/protocols/file_protocol.zig
Labels: os-uefi, standard library

#7781 macho: use target architecture page size in code signature calculation
  src/link/MachO.zig
  src/link/MachO/CodeSignature.zig
Labels: os-macos, stage2

#7785 organize std lib concurrency primitives and add RwLock
  CMakeLists.txt
  lib/std/Progress.zig
  lib/std/SpinLock.zig
  lib/std/Thread.zig
  lib/std/Thread/AutoResetEvent.zig
  lib/std/Thread/Condition.zig
  lib/std/Thread/Mutex.zig
  lib/std/Thread/ResetEvent.zig
  lib/std/Thread/RwLock.zig
  lib/std/Thread/Semaphore.zig
  lib/std/Thread/StaticResetEvent.zig
  lib/std/atomic/queue.zig
  lib/std/auto_reset_event.zig
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/c/emscripten.zig
  lib/std/c/freebsd.zig
  lib/std/c/fuchsia.zig
  lib/std/c/haiku.zig
  lib/std/c/hermit.zig
  lib/std/c/linux.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/debug.zig
  lib/std/event/lock.zig
  lib/std/event/loop.zig
  lib/std/event/wait_group.zig
  lib/std/fs/test.zig
  lib/std/heap/general_purpose_allocator.zig
  lib/std/mutex.zig
  lib/std/once.zig
  lib/std/os/windows/bits.zig
  lib/std/os/windows/kernel32.zig
  lib/std/std.zig
  lib/std/thread.zig
  src/Compilation.zig
  src/ThreadPool.zig
  src/WaitGroup.zig
Labels: breaking, standard library

#7773 translate-c: ensure bools are cast to int when necessary
  src/translate_c.zig
  test/run_translated_c.zig
Labels: translate-c

#7768 crypto: add legacy keccak hash functions
  lib/std/crypto/sha3.zig
Labels: standard library

#7787 macho: ensure that strtab always follows symtab
  src/link/MachO.zig
  test/stage2/aarch64.zig
  test/stage2/test.zig
Labels: os-macos, stage2

#7783 stage2 ARM: add extra load/store instructions
  src/codegen.zig
  src/codegen/arm.zig
Labels: arch-arm32, stage2

#7716 stage1: SPARCv9 f128 enablement
  lib/std/special/compiler_rt.zig
  lib/std/special/compiler_rt/sparc.zig
  src/stage1/codegen.cpp
Labels: arch-sparc64

#7802 stage2 aarch64: add basic genSetStack
  src/codegen.zig
Labels: arch-arm64, stage2

#7804 stage2 aarch64: add basic function pro/epilogue
  src/codegen.zig
  src/codegen/aarch64.zig
  test/stage2/aarch64.zig
Labels: arch-arm64, stage2

#7803 macho: improve x86_64 tests; clean fixups on error
  src/link/MachO.zig
  test/stage2/test.zig
Labels: arch-x86_64, os-macos, stage2

#7806 macho: refactor undef symbol handling
  src/codegen.zig
  src/link/MachO.zig
  src/link/MachO/imports.zig
Labels: os-macos, stage2

#7814 std: Fixed pipe2 fallback
  lib/std/c.zig
  lib/std/c/dragonfly.zig
  lib/std/c/freebsd.zig
  lib/std/c/linux.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/os.zig
Labels: standard library

#7797 stage2: wasm - Refactor codegen for wasm similar to other backends
  src/codegen/wasm.zig
  src/link/Wasm.zig
  test/stage2/test.zig
  test/stage2/wasm.zig
Labels: stage2

#7818 Macho more cleanup
  src/Module.zig
  src/link/MachO.zig
  src/link/MachO/DebugSymbols.zig
Labels: os-macos, stage2

#7829 stage2 macho: make int casts fallible where necessary
  src/link/MachO.zig
  src/link/MachO/DebugSymbols.zig
  src/link/MachO/commands.zig
  test/stage2/aarch64.zig
  test/stage2/darwin.zig
  test/stage2/test.zig
Labels: os-macos, stage2

#7880 windows: make sure to handle PATH_NOT_FOUND when deleting files
  lib/std/os/windows.zig
Labels: os-windows, standard library

#7858 Add MAX_RW_COUNT limit to std.os.pread()
  lib/std/os.zig
Labels: standard library

#7889 Fix integer overflow when calling joinZ with empty slices
  lib/std/mem.zig
Labels: standard library

#7811 add error for slice.len increment beyond bounds
  src/stage1/ir.cpp
  test/compile_errors.zig
Labels: stage1

#7898 Improve error messages in std.fmt
  lib/std/fmt.zig
Labels: standard library
