Repository ziglang/zig, pull requests merged in 2021-05, with the labels that each got.

#8678 std: Accept unaligned slice in several ArrayListAligned ops
  lib/std/array_list.zig
Labels: standard library

#8690 stage1: Fix other OS target
  src/stage1/stage1.h
  src/stage1/target.cpp
Labels: bug, os-bring-your-own, stage1

#8691 x/net: fix tcp tests for openbsd and add missing `fmt` import
  lib/std/x/net/ip.zig
  lib/std/x/net/tcp.zig
  lib/std/x/os/Socket.zig
Labels: os-openbsd

#8741 bsd: detect os version
  lib/std/os/bits/openbsd.zig
  lib/std/target.zig
  lib/std/zig/system.zig
Labels: os-dragonfly, os-netbsd, os-openbsd

#8744 azure: bump timeout for macos-arm64
  ci/azure/pipelines.yml
Labels: arch-arm64, os-macos

#8698 std/mem: add sliceTo(), deprecate spanZ(), lenZ()
  lib/std/mem.zig
  lib/std/meta.zig
Labels: standard library

#8720 Fix shrinkAndFree and remove shrinkRetainingCapacity in PriorityQueue and PriorityDequeue
  lib/std/priority_dequeue.zig
  lib/std/priority_queue.zig
Labels: breaking

#8760 Add experimental Darling support for cross testing macOS
  build.zig
  lib/std/build.zig
  lib/std/zig/cross_target.zig
  src/test.zig
  test/tests.zig
Labels: enhancement

#8769 macho: fix bug with symbol growth and realloc
  src/link/MachO.zig
  test/stage2/darwin.zig
Labels: backend-self-hosted, os-macos, stage2

#8771 macho: require _main as global export in self-hosted
  src/link/MachO.zig
  test/stage2/darwin.zig
Labels: backend-self-hosted, os-macos, stage2

#8764 Fix duplicate_field_behavior UseFirst for parse in json.zig
  lib/std/json.zig
Labels: standard library

#8773 macho: put dSYM bundle in zig-cache
  src/link/MachO.zig
Labels: backend-self-hosted, os-macos, stage2

#8778 std.testing: Added newline to the error messages
  lib/std/testing.zig
Labels: standard library

#8784 macho: fix DWARF in dSYM and sym naming more consistent
  src/link/MachO.zig
  src/link/MachO/DebugSymbols.zig
  test/stage2/darwin.zig
Labels: backend-self-hosted, os-macos, stage2

#8783 std.meta.trait: Remove `isIntegerNumber` and `isFloatingNumber`
  lib/std/meta/trait.zig
Labels: standard library

#8806 zig ld: add preliminary mechanism for linking dylibs
  CMakeLists.txt
  lib/std/macho.zig
  src/link/MachO.zig
  src/link/MachO/Dylib.zig
  src/link/MachO/Symbol.zig
  src/link/MachO/Zld.zig
  src/link/MachO/commands.zig
  test/standalone.zig
Labels: os-macos, zig ld

#8838 Const correct GUID parameter of getInfo and setInfo
  lib/std/os/uefi/protocols/file_protocol.zig
Labels: os-uefi, standard library

#8859 fix accidental quadratic dependence on haystack length in replace and replacementSize
  lib/std/mem.zig
Labels: standard library

#8864 zld: permit system static libs
  src/link/MachO.zig
  src/link/MachO/Archive.zig
  src/link/MachO/Dylib.zig
  src/link/MachO/Object.zig
  src/link/MachO/Zld.zig
  test/standalone.zig
  test/standalone/link_static_lib_as_system_lib/a.c
  test/standalone/link_static_lib_as_system_lib/a.h
  test/standalone/link_static_lib_as_system_lib/build.zig
  test/standalone/link_static_lib_as_system_lib/main.zig
Labels: os-macos, zig ld

#8857 wasm: produce static lib by default and rename produced object files to simply .o from .o.wasm
  doc/docgen.zig
  doc/langref.html.in
  lib/std/target.zig
  src/link/Wasm.zig
  src/main.zig
Labels: arch-wasm32, breaking, os-freestanding, os-wasi

#7664 implement nt path conversion for windows
  lib/std/fs.zig
  lib/std/fs/test.zig
  lib/std/mem.zig
  lib/std/os/windows.zig
  lib/std/os/windows/kernel32.zig
  lib/std/os/windows/test.zig
Labels: os-windows, standard library

#8870 cc,wasi: force isysroot to / when building WASI libc
  src/wasi_libc.zig
Labels: arch-wasm32, os-wasi, zig cc

#8863 fix Boyer-Moore-Horspool algorithm in indexOfPos and lastIndexOf when element type is larger than a byte
  lib/std/mem.zig
Labels: bug, standard library

#8730 overhaul elf csu (c-runtime startup) logic
  lib/std/Thread.zig
  lib/std/c/dragonfly.zig
  lib/std/child_process.zig
  lib/std/os/bits/dragonfly.zig
  lib/std/special/compiler_rt/emutls.zig
  src/Compilation.zig
  src/libc_installation.zig
  src/link/Elf.zig
  src/musl.zig
  src/target.zig
  test/stack_traces.zig
Labels: os-dragonfly, os-freebsd, os-netbsd, os-openbsd

#8882 dragonfly: pass `zig build test`
  lib/std/dynamic_library.zig
  lib/std/fs/test.zig
  lib/std/os/bits/dragonfly.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/bits/netbsd.zig
  lib/std/os/bits/openbsd.zig
Labels: os-dragonfly

#8911 zld: dylib paths need nul terminator included
  src/link/MachO/commands.zig
Labels: os-macos, zig ld

#8912 build: allow specifying rpaths explicitly
  lib/std/build.zig
Labels: zig build system

#7918 Add option to ignore unknown fields when parsing json
  lib/std/json.zig
Labels: standard library

#8938 std.json improvements
  lib/std/json.zig
Labels: standard library

#8866 std.sync.atomic: extended atomic helper functions
  CMakeLists.txt
  lib/std/Thread.zig
  lib/std/Thread/Condition.zig
  lib/std/Thread/Mutex.zig
  lib/std/Thread/StaticResetEvent.zig
  lib/std/atomic.zig
  lib/std/atomic/Atomic.zig
  lib/std/atomic/bool.zig
  lib/std/atomic/int.zig
  lib/std/json.zig
  lib/std/os.zig
  lib/std/packed_int_array.zig
  lib/std/target.zig
  src/BuiltinFn.zig
Labels: standard library
