Repository ziglang/zig, pull requests merged in 2021-08, with the labels that each got.

#9491 Make linux syscalls accessible with non-Linux target OS
  lib/std/os/bits.zig
  lib/std/os/bits/darwin.zig
  lib/std/os/bits/dragonfly.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/bits/haiku.zig
  lib/std/os/bits/linux.zig
  lib/std/os/bits/netbsd.zig
  lib/std/os/bits/openbsd.zig
  lib/std/os/bits/posix.zig
  lib/std/os/bits/wasi.zig
  lib/std/os/bits/windows.zig
  lib/std/os/linux/arm-eabi.zig
  lib/std/os/linux/arm64.zig
  lib/std/os/linux/i386.zig
  lib/std/os/linux/mips.zig
  lib/std/os/linux/powerpc.zig
  lib/std/os/linux/powerpc64.zig
  lib/std/os/linux/riscv64.zig
  lib/std/os/linux/sparc64.zig
  lib/std/os/linux/thumb.zig
  lib/std/os/linux/x86_64.zig
Labels: standard library

#9506 std: check for overflow in writeCurrentStackTrace
  lib/std/debug.zig
Labels: standard library

#9515 libstd: add ArrayHashMap.popOrNull function
  lib/std/array_hash_map.zig
Labels: proposal, standard library

#9521 Include system libc headers if natively linking frameworks on macOS
  src/Compilation.zig
Labels: os-macos

#9534 linux: add missing FUTEX definitions
  lib/std/os/bits/linux.zig
Labels: standard library, os-linux

#9531 Make mem.split and mem.tokenize generic instead of assuming u8
  build.zig
  lib/std/SemanticVersion.zig
  lib/std/build.zig
  lib/std/builtin.zig
  lib/std/child_process.zig
  lib/std/fs.zig
  lib/std/fs/path.zig
  lib/std/mem.zig
  lib/std/net.zig
  lib/std/os.zig
  lib/std/process.zig
  lib/std/zig/cross_target.zig
  lib/std/zig/system.zig
  src/Cache.zig
  src/Compilation.zig
  src/codegen.zig
  src/glibc.zig
  src/libc_installation.zig
  src/link/MachO/Dylib.zig
  src/main.zig
  src/test.zig
  test/behavior/bugs/6456.zig
  test/tests.zig
  tools/update_glibc.zig
  tools/update_spirv_features.zig
Labels: breaking, standard library

#9538 Ip4Address parser: reject 0-prefixed components
  lib/std/net.zig
  lib/std/net/test.zig
Labels: standard library

#9542 macho: fix linking of dylibs and frameworks
  src/link/MachO.zig
  src/link/MachO/Dylib.zig
  test/standalone.zig
  test/standalone/link_frameworks/build.zig
  test/standalone/link_frameworks/main.c
Labels: os-macos, zig ld

#9549 macho: handle TAPI v3 and simplify handling of dependent dynamic libraries
  src/link/MachO.zig
  src/link/MachO/Archive.zig
  src/link/MachO/Dylib.zig
  src/link/MachO/Object.zig
  src/link/tapi.zig
  src/link/tapi/yaml.zig
Labels: os-macos, zig ld

#9227 WASI,libc: fix libstd with wasi-libc linkage, and enable tests.
  lib/std/Thread.zig
  lib/std/c.zig
  lib/std/c/wasi.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/wasi.zig
  lib/std/io/c_writer.zig
  lib/std/os.zig
  lib/std/os/bits/wasi.zig
  lib/std/process.zig
  lib/std/start.zig
  lib/std/testing.zig
  src/stage1/codegen.cpp
  test/cases.zig
  test/stage2/darwin.zig
  test/tests.zig
Labels: arch-wasm32, os-wasi

#9545 Fix darwin ulock usage on macOS
  lib/std/Thread/Futex.zig
  lib/std/c/darwin.zig
Labels: standard library

#9036 Add std.io.Reader.readUntilDelimiter()
  lib/std/io/reader.zig
Labels: standard library

#9051 Clarify async/await language documentation.
  doc/langref.html.in
Labels: docs

#9307 std.json: Add support for recursive objects to std.json.parse
  lib/std/fmt.zig
  lib/std/fmt/parse_float.zig
  lib/std/json.zig
Labels: standard library

#9247 Fix issue where root.os.panic could return
  lib/std/builtin.zig
Labels: os-bring-your-own

#9160 dragonfly: port libc++
  lib/libcxx/include/__config
  lib/libcxx/include/__locale
  lib/libcxx/include/locale
  lib/libcxx/src/locale.cpp
Labels: os-dragonfly

#8980 Add a flag to build a single-threaded compiler, for debugging
  build.zig
Labels: stage2

#9558 mingw.zig: fix logic to add crt sources
  src/mingw.zig
Labels: stage2

#9571 stage2 Air: add struct_field_ptr_index_{0..3}
  src/Air.zig
  src/Liveness.zig
  src/Sema.zig
  src/codegen.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/codegen/wasm.zig
  src/print_air.zig
  test/stage2/cbe.zig
Labels: stage2

#9015 std.os: (p)writev should perform partial writes if iov.len > IOV_MAX
  lib/std/os.zig
  lib/std/os/bits/darwin.zig
  lib/std/os/bits/dragonfly.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/bits/netbsd.zig
  lib/std/os/bits/wasi.zig
  lib/std/os/test.zig
Labels: standard library

#9613 std: move errno to become an nonexhaustive enum
  CMakeLists.txt
  lib/std/Thread.zig
  lib/std/Thread/Condition.zig
  lib/std/Thread/Futex.zig
  lib/std/Thread/Mutex.zig
  lib/std/Thread/ResetEvent.zig
  lib/std/Thread/RwLock.zig
  lib/std/Thread/StaticResetEvent.zig
  lib/std/c.zig
  lib/std/c/darwin.zig
  lib/std/c/linux.zig
  lib/std/c/netbsd.zig
  lib/std/fs.zig
  lib/std/fs/wasi.zig
  lib/std/io/c_writer.zig
  lib/std/os.zig
  lib/std/os/bits/darwin.zig
  lib/std/os/bits/dragonfly.zig
  lib/std/os/bits/freebsd.zig
  lib/std/os/bits/haiku.zig
  lib/std/os/bits/linux.zig
  lib/std/os/bits/linux/errno-generic.zig
  lib/std/os/bits/linux/errno-mips.zig
  lib/std/os/bits/linux/errno-sparc.zig
  lib/std/os/bits/linux/errno/generic.zig
  lib/std/os/bits/linux/errno/mips.zig
  lib/std/os/bits/linux/errno/sparc.zig
  lib/std/os/bits/netbsd.zig
  lib/std/os/bits/openbsd.zig
  lib/std/os/bits/wasi.zig
  lib/std/os/bits/windows.zig
  lib/std/os/linux.zig
  lib/std/os/linux/bpf.zig
  lib/std/os/linux/io_uring.zig
  lib/std/os/linux/test.zig
  lib/std/os/wasi.zig
  lib/std/process.zig
  lib/std/special/compiler_rt/emutls.zig
  lib/std/time.zig
  lib/std/x/os/socket_posix.zig
Labels: breaking, standard library

#9577 std/crypto: add scrypt kdf
  lib/std/crypto.zig
  lib/std/crypto/bcrypt.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/phc_encoding.zig
  lib/std/crypto/scrypt.zig
Labels: breaking, standard library

#9134 BoundedArray: a simple way to represent small data whose max size is known
  lib/std/bounded_array.zig
  lib/std/std.zig
Labels: standard library
