Repository ziglang/zig, pull requests merged in 2021-02, with the labels that each got.

#7847 stage2: rework astgen result locations
  src/Module.zig
  src/astgen.zig
  src/codegen.zig
  src/ir.zig
  src/zir.zig
  src/zir_sema.zig
  test/stage2/test.zig
Labels: stage2

#7922 std.json support for comptime fields
  lib/std/json.zig
Labels: standard library

#7883 Fixes for std.Thread.Condition
  lib/std/Thread/Condition.zig
Labels: standard library

#7819 stage2 ARM: save function arguments to stack for debugging
  src/codegen.zig
Labels: arch-arm32, stage2

#7912 std.json large number support
  lib/std/json.zig
Labels: standard library

#7937 siphash: update the link to the SipHash paper
  lib/std/crypto/siphash.zig
Labels: standard library

#7479 Make translate-c use intermediate AST
  CMakeLists.txt
  lib/std/zig/parser_test.zig
  lib/std/zig/render.zig
  src/Compilation.zig
  src/astgen.zig
  src/clang.zig
  src/translate_c.zig
  src/translate_c/ast.zig
  src/type.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/run_translated_c.zig
  test/translate_c.zig
Labels: translate-c

#8042 Add epoll_pwait2 Linux syscall
  lib/std/os/bits/linux/arm-eabi.zig
  lib/std/os/bits/linux/arm64.zig
  lib/std/os/bits/linux/i386.zig
  lib/std/os/bits/linux/mips.zig
  lib/std/os/bits/linux/powerpc64.zig
  lib/std/os/bits/linux/riscv64.zig
  lib/std/os/bits/linux/sparc64.zig
  lib/std/os/bits/linux/x86_64.zig
Labels: os-linux, standard library

#8014 Fix fifo readableSliceMut bug in overflow case (and add tests)
  lib/std/fifo.zig
Labels: bug, standard library

#8013 replace ArrayList.shrinkAndFree by ArrayList.shrinkRetainingCapacity
  lib/std/fs.zig
  lib/std/io/reader.zig
  lib/std/json.zig
  lib/std/math/big/int.zig
  lib/std/net.zig
Labels: standard library

#7853 Add link(at) for linux
  lib/std/c.zig
  lib/std/os.zig
  lib/std/os/linux.zig
  lib/std/os/test.zig
Labels: os-linux, standard library

#7755 fix race condition in linuxWaitFd
  lib/std/event/loop.zig
Labels: os-linux, standard library

#8049 Std: Expose reader and writer types of std.fifo.LinearFifo
  lib/std/fifo.zig
Labels: standard library

#7920 Rework AST memory layout for better memory usage and performance
  CMakeLists.txt
  README.md
  build.zig
  doc/docgen.zig
  lib/std/heap/general_purpose_allocator.zig
  lib/std/io.zig
  lib/std/io/auto_indenting_stream.zig
  lib/std/multi_array_list.zig
  lib/std/std.zig
  lib/std/zig.zig
  lib/std/zig/ast.zig
  lib/std/zig/parse.zig
  lib/std/zig/parser_test.zig
  lib/std/zig/render.zig
  lib/std/zig/tokenizer.zig
  src/BuiltinFn.zig
  src/Compilation.zig
  src/Module.zig
  src/astgen.zig
  src/clang.zig
  src/codegen.zig
  src/codegen/c.zig
  src/ir.zig
  src/link.zig
  src/link/C.zig
  src/link/Coff.zig
  src/link/Elf.zig
  src/link/MachO.zig
  src/link/MachO/DebugSymbols.zig
  src/link/Wasm.zig
  src/main.zig
  src/test.zig
  src/translate_c.zig
  src/translate_c/ast.zig
  src/type.zig
  src/zig_clang.cpp
  src/zig_clang.h
  src/zir.zig
  src/zir_sema.zig
  test/run_translated_c.zig
  test/stage2/test.zig
  test/translate_c.zig
Labels: breaking, enhancement, optimization, stage2

#7628 stage2: catch at comptime!
  src/Module.zig
  src/codegen.zig
  src/ir.zig
  src/value.zig
  src/zir.zig
  src/zir_sema.zig
  test/stage2/test.zig
Labels: stage2

#8099 std/crypto/benchmark: update format strings
  lib/std/crypto/benchmark.zig
Labels: standard library

#8098 std/crypto/aes: fix AES {encrypt,decrypt}Wide
  lib/std/crypto/aes/aesni.zig
  lib/std/crypto/aes/armcrypto.zig
Labels: standard library

#8086 std: add sendmsg
  lib/std/os.zig
  lib/std/os/bits/linux/arm64.zig
  lib/std/os/bits/linux/x86_64.zig
  lib/std/os/linux.zig
  lib/std/os/windows.zig
Labels: standard library
