Repository ziglang/zig, pull requests merged in 2021-09, with the labels that each got.

#9417 cmake: also check Homebrew install paths when looking for LLVM
  cmake/Findclang.cmake
  cmake/Findlld.cmake
  cmake/Findllvm.cmake
Labels: os-macos, stage1

#9676 MachO: merges stage1 with self-hosted codepath
  CMakeLists.txt
  lib/std/macho.zig
  src/codegen.zig
  src/link/MachO.zig
  src/link/MachO/Atom.zig
  src/link/MachO/DebugSymbols.zig
  src/link/MachO/Object.zig
  src/link/MachO/bind.zig
  src/link/MachO/commands.zig
  test/stage2/darwin.zig
Labels: os-macos, arch-x86_64, arch-arm64, zig ld

#9040 add functions to decode an epoch timestamp
  lib/std/math.zig
  lib/std/time.zig
  lib/std/time/epoch.zig
Labels: standard library

#9796 elf: add amd64 relocation types
  lib/std/elf.zig
Labels: standard library, os-linux, arch-x86_64

#9817 std.build: fix handling of -Dcpu
  lib/std/build.zig
Labels: zig build system
