Repository ziglang/zig, pull requests merged in 2022-05, with the labels that each got.

#10428 Improve stdlib's random float generation
  lib/std/rand.zig
  lib/std/rand/test.zig
Labels: standard library

#10661 std: add http definitions for Method and Status
  lib/std/http.zig
  lib/std/http/method.zig
  lib/std/http/status.zig
  lib/std/std.zig
Labels: standard library

#10796 Envmap
  doc/docgen.zig
  lib/std/buf_map.zig
  lib/std/build.zig
  lib/std/build/RunStep.zig
  lib/std/child_process.zig
  lib/std/os/windows/ntdll.zig
  lib/std/process.zig
Labels: standard library, os-windows

#10281 std.math.sign: get the sign of a int, float or vector
  lib/std/math.zig
Labels: enhancement, standard library

#11652 std.os: Add memfd_create for FreeBSD
  lib/std/c/freebsd.zig
  lib/std/os.zig
  lib/std/os/linux.zig
  lib/std/os/test.zig
Labels: breaking, standard library, os-freebsd

#11316 stage2: vectorized overflow arithmetic, integer overflow safety, left-shift overflow safety
  lib/std/builtin.zig
  src/Sema.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/arm/CodeGen.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/Emit.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/link/C/zig.h
  src/type.zig
  src/value.zig
  test/behavior/math.zig
  test/behavior/vector.zig
  test/cases/recursive_fibonacci.zig
Labels: enhancement, stage2

#11447 Generate linux syscalls via the Linux source tree
  lib/std/os/linux.zig
  lib/std/os/linux/arm-eabi.zig
  lib/std/os/linux/arm64.zig
  lib/std/os/linux/i386.zig
  lib/std/os/linux/mips.zig
  lib/std/os/linux/powerpc.zig
  lib/std/os/linux/powerpc64.zig
  lib/std/os/linux/riscv64.zig
  lib/std/os/linux/sparc64.zig
  lib/std/os/linux/syscalls.zig
  lib/std/os/linux/x86_64.zig
  tools/generate_linux_syscalls.zig
Labels: enhancement, standard library, os-linux

#11501 stage2: error return traces
  lib/compiler_rt.zig
  lib/std/builtin.zig
  lib/test_runner.zig
  src/Air.zig
  src/AstGen.zig
  src/Compilation.zig
  src/Liveness.zig
  src/Module.zig
  src/Sema.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/arm/CodeGen.zig
  src/arch/riscv64/CodeGen.zig
  src/arch/sparc64/CodeGen.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/CodeGen.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/print_air.zig
  src/type.zig
Labels: enhancement, stage2

#11491 std.math: simplify signbit and copysign
  lib/compiler_rt/fma.zig
  lib/std/math/atanh.zig
  lib/std/math/complex/cosh.zig
  lib/std/math/complex/proj.zig
  lib/std/math/complex/sinh.zig
  lib/std/math/complex/sqrt.zig
  lib/std/math/complex/tanh.zig
  lib/std/math/copysign.zig
  lib/std/math/isfinite.zig
  lib/std/math/isinf.zig
  lib/std/math/isnormal.zig
  lib/std/math/ldexp.zig
  lib/std/math/pow.zig
  lib/std/math/signbit.zig
Labels: enhancement, standard library

#11731 std.PriorityQueue: fix missing siftUp in remove
  lib/std/priority_queue.zig
Labels: bug

#10197 io_uring: implement automatic buffer selection
  lib/std/os/linux/io_uring.zig
Labels: enhancement, standard library

#11695 math: make `cast` return an optional instead of error
  lib/std/Thread.zig
  lib/std/Thread/Condition.zig
  lib/std/Thread/Futex.zig
  lib/std/child_process.zig
  lib/std/debug.zig
  lib/std/dwarf.zig
  lib/std/dynamic_library.zig
  lib/std/fmt.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/io/fixed_buffer_stream.zig
  lib/std/math.zig
  lib/std/math/big/int.zig
  lib/std/os.zig
  lib/std/os/windows.zig
  lib/std/time.zig
  lib/std/zig/system/NativeTargetInfo.zig
  src/Module.zig
  src/Sema.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/aarch64/Emit.zig
  src/arch/arm/CodeGen.zig
  src/arch/arm/Emit.zig
  src/arch/riscv64/CodeGen.zig
  src/arch/sparc64/CodeGen.zig
  src/arch/sparc64/Emit.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/CodeGen.zig
  src/codegen.zig
  src/link/MachO.zig
  src/link/MachO/Atom.zig
  src/link/MachO/DebugSymbols.zig
  src/link/MachO/Dylib.zig
  src/link/MachO/Object.zig
  src/link/tapi/yaml.zig
  src/main.zig
  src/translate_c.zig
Labels: breaking, standard library

#10617 translate-c: reserve space for bitfield.
  src/clang.zig
  src/translate_c.zig
  src/zig_clang.cpp
  src/zig_clang.h
  test/translate_c.zig
Labels: translate-c
