Repository ziglang/zig, pull requests merged in 2022-06, with the labels that each got.

#11565 std.os: ported signal handling in abort() from musl
  lib/std/os.zig
Labels: enhancement, standard library, os-linux

#11779 add const to msghdr_const iov and control pointers
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/c/solaris.zig
  lib/std/os/linux/arm-eabi.zig
  lib/std/os/linux/arm64.zig
  lib/std/os/linux/i386.zig
  lib/std/os/linux/io_uring.zig
  lib/std/os/linux/mips.zig
  lib/std/os/linux/powerpc.zig
  lib/std/os/linux/powerpc64.zig
  lib/std/os/linux/riscv64.zig
  lib/std/os/linux/sparc64.zig
  lib/std/os/linux/x86_64.zig
  lib/std/os/windows/ws2_32.zig
Labels: standard library

#11855 std/crypto: add support for ECDSA signatures
  lib/std/crypto.zig
  lib/std/crypto/ecdsa.zig
Labels: standard library

#11880 std.crypto.ecc: add support for the secp256k1 curve
  lib/std/crypto.zig
  lib/std/crypto/pcurves/common.zig
  lib/std/crypto/pcurves/secp256k1.zig
  lib/std/crypto/pcurves/secp256k1/field.zig
  lib/std/crypto/pcurves/secp256k1/scalar.zig
  lib/std/crypto/pcurves/secp256k1/secp256k1_64.zig
  lib/std/crypto/pcurves/secp256k1/secp256k1_scalar_64.zig
  lib/std/crypto/pcurves/tests/secp256k1.zig
Labels: standard library

#11964 std.math.big.int: breaking API changes to prevent UAF
  lib/std/math/big/int.zig
  lib/std/math/big/int_test.zig
  lib/std/math/big/rational.zig
  src/RangeSet.zig
  src/Sema.zig
Labels: breaking, standard library
