Repository ziglang/zig, pull requests merged in 2022-02, with the labels that each got.

#10742 std: make ArrayHashMap eql function accept an additional param
  lib/std/array_hash_map.zig
  lib/std/builtin.zig
  lib/std/hash/auto_hash.zig
  lib/std/hash_map.zig
  src/InternArena.zig
  src/codegen/spirv/type.zig
  src/type.zig
  src/value.zig
Labels: breaking, standard library, proposal, stage2

#10879 make some errors point to the end of the previous token
  lib/std/zig/Ast.zig
  lib/std/zig/parse.zig
  src/Module.zig
  src/main.zig
  test/compile_errors.zig
  test/stage2/cbe.zig
Labels: stage2

#10486 std: Implement cross-platform metadata API
  lib/std/c/darwin.zig
  lib/std/c/freebsd.zig
  lib/std/c/haiku.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/c/wasi.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/fs/test.zig
  lib/std/os/wasi.zig
Labels: standard library

#10849 std.json: fix compile error for comptime fields
  lib/std/json.zig
  lib/std/testing.zig
  lib/std/zig/c_translation.zig
  lib/std/zig/parser_test.zig
Labels: standard library
