Repository ziglang/zig, pull requests merged in 2022-01, with the labels that each got.

#10456 Support parsing tz timezone data
  build.zig
  lib/std/std.zig
  lib/std/tz.zig
  lib/std/tz/antarctica_davis.tzif
  lib/std/tz/asia_tokyo.tzif
  lib/std/tz/europe_vatican.tzif
Labels: standard library

#9637 std: add json.stringifyAlloc
  lib/std/json.zig
Labels: standard library

#10619 std: add meta.DeclEnum
  lib/std/meta.zig
Labels: standard library

#10675 std: Add some missing termios types to c/linux.zig and os.zig
  lib/std/c/linux.zig
  lib/std/os.zig
Labels: standard library, os-linux

#10668 Stop using LiniarFifo in BufferedWriter
  lib/std/io/buffered_writer.zig
Labels: optimization, standard library

#10510 Normalize some build function names
  build.zig
  lib/std/build.zig
  test/standalone/issue_794/build.zig
  test/standalone/issue_9812/build.zig
  test/standalone/link_interdependent_static_c_libs/build.zig
  test/standalone/link_static_lib_as_system_lib/build.zig
  test/standalone/objc/build.zig
  test/standalone/objcpp/build.zig
  test/standalone/static_c_lib/build.zig
  test/standalone/use_alias/build.zig
  test/tests.zig
Labels: accepted

#10691 std.crypto.random: `Random`s are no longer passed by reference
  lib/std/crypto.zig
Labels: standard library

#10422 fchown: use the 32-bit uid/gid variant of the syscall on 32-bit linux targets.
  lib/std/os/linux.zig
Labels: standard library, os-linux

#10639 Add f80
  CMakeLists.txt
  doc/langref.html.in
  lib/std/math.zig
  lib/std/math/epsilon.zig
  lib/std/math/inf.zig
  lib/std/math/nan.zig
  src/AstGen.zig
  src/Sema.zig
  src/Zir.zig
  src/stage1/all_types.hpp
  src/stage1/analyze.cpp
  src/stage1/codegen.cpp
  src/stage1/ir.cpp
  src/stage1/softfloat.hpp
  src/stage1/softfloat_ext.cpp
  src/stage1/softfloat_ext.hpp
  src/stage1/target.cpp
  src/stage1/target.hpp
  src/type.zig
  src/value.zig
  test/behavior/floatop_stage1.zig
  test/behavior/math_stage1.zig
  test/behavior/muladd.zig
  test/behavior/type_stage1.zig
  test/behavior/widening.zig
Labels: stage1

#9654 More response file support
  doc/docgen.zig
  lib/std/process.zig
  lib/std/unicode.zig
  src/main.zig
  test/cli.zig
  test/compare_output.zig
Labels: breaking
