Repository ziglang/zig, pull requests merged in 2022-08, with the labels that each got.

#12410 std: fix definition of SIG_IGN, SIG_DFL, etc.
  lib/std/c/darwin.zig
  lib/std/c/dragonfly.zig
  lib/std/c/freebsd.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/c/solaris.zig
  lib/std/debug.zig
  lib/std/os.zig
  lib/std/os/linux.zig
  lib/std/os/test.zig
Labels: breaking, standard library

#12445 autodoc: better No Results Found page and other improvements
  lib/docs/index.html
  lib/docs/main.js
Labels: autodoc

#12145 More ABI size and alignment fixes
  lib/std/target.zig
  lib/std/zig.zig
  lib/std/zig/CrossTarget.zig
  lib/std/zig/system/NativeTargetInfo.zig
  src/Compilation.zig
  src/Module.zig
  src/Sema.zig
  src/codegen/llvm.zig
  src/link.zig
  src/link/C.zig
  src/link/Coff.zig
  src/link/Elf.zig
  src/link/MachO.zig
  src/link/NvPtx.zig
  src/link/Plan9.zig
  src/link/SpirV.zig
  src/link/Wasm.zig
  src/main.zig
  src/stage1/codegen.cpp
  src/test.zig
  src/type.zig
  test/behavior/align.zig
Labels: breaking
