Repository ziglang/zig, pull requests merged in 2022-10, with the labels that each got.

#12898 improve header searchlist handling in build, main
  lib/std/build.zig
  src/main.zig
Labels: zig build system, zig cc

#12448 std.ascii: rename functions and other improvements
  lib/std/ascii.zig
Labels: breaking, standard library

#13309 Revamp the ed25519 API
  lib/std/crypto/25519/ed25519.zig
  lib/std/crypto/25519/x25519.zig
  lib/std/crypto/benchmark.zig
Labels: breaking, standard library

#13320 Add reboot syscall
  lib/std/os.zig
  lib/std/os/linux.zig
Labels: standard library

#13321 Add `sockaddr_vm` for vSockets on Linux
  lib/std/os/linux.zig
Labels: standard library

#13332 std.crypto.sign.ecdsa: add support for incremental signatures
  lib/std/crypto/ecdsa.zig
Labels: standard library
