Repository ziglang/zig, pull requests merged in 2022-11, with the labels that each got.

#13548 std.os.linux: Add setitimer and getitimer syscalls
  lib/std/os/linux.zig
Labels: standard library, os-linux

#13541 zig-cache: support windows drive + fwd-slash paths
  src/DepTokenizer.zig
Labels: os-windows

#13554 process.zig: remove unused function getSelfExeSharedLibPaths
  lib/std/process.zig
Labels: breaking, standard library

#13566 std.crypto.onetimeauth.ghash: faster GHASH on modern CPUs
  lib/std/crypto/ghash.zig
Labels: standard library

#13643 std.crypto.ed25519 incremental signatures: hash the fallback noise
  lib/std/crypto/25519/ed25519.zig
Labels: standard library

#13701 Improve aarch64 feature detection based on the readouts from privileged system registers
  lib/std/zig/system/arm.zig
  lib/std/zig/system/windows.zig
Labels: standard library, os-windows, arch-aarch64

#13666 std.mem.Allocator: allow shrink to fail
  doc/docgen.zig
  lib/std/array_hash_map.zig
  lib/std/array_list.zig
  lib/std/build.zig
  lib/std/child_process.zig
  lib/std/debug.zig
  lib/std/fs/file.zig
  lib/std/fs/path.zig
  lib/std/fs/wasi.zig
  lib/std/heap.zig
  lib/std/heap/arena_allocator.zig
  lib/std/heap/general_purpose_allocator.zig
  lib/std/heap/log_to_writer_allocator.zig
  lib/std/heap/logging_allocator.zig
  lib/std/io/reader.zig
  lib/std/json.zig
  lib/std/math/big/int.zig
  lib/std/mem.zig
  lib/std/mem/Allocator.zig
  lib/std/meta/trailer_flags.zig
  lib/std/multi_array_list.zig
  lib/std/net.zig
  lib/std/pdb.zig
  lib/std/segmented_list.zig
  lib/std/testing/failing_allocator.zig
  lib/std/unicode.zig
  lib/std/zig/parse.zig
  src/AstGen.zig
  src/Autodoc.zig
  src/Compilation.zig
  src/Liveness.zig
  src/Module.zig
  src/Sema.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/arm/CodeGen.zig
  src/arch/riscv64/CodeGen.zig
  src/arch/sparc64/CodeGen.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/CodeGen.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/libc_installation.zig
  src/link/Coff.zig
  src/link/Elf.zig
  src/link/MachO.zig
  src/link/MachO/Trie.zig
  src/link/Plan9.zig
  src/link/Wasm.zig
  src/link/Wasm/Object.zig
  src/link/tapi/parse.zig
  src/link/tapi/yaml.zig
  src/main.zig
  src/test.zig
  src/translate_c/ast.zig
  src/value.zig
  test/cases/compile_errors/dereference_anyopaque.zig
  test/compare_output.zig
  test/tests.zig
Labels: breaking
