Repository ziglang/zig, pull requests merged in 2023-05, with the labels that each got.

#15691 Zir: eliminate `field_call_bind` and `field_call_bind_named`
  lib/std/Thread/Mutex.zig
  lib/std/crypto/siphash.zig
  lib/std/hash/auto_hash.zig
  lib/std/hash/wyhash.zig
  src/AstGen.zig
  src/Autodoc.zig
  src/Module.zig
  src/Sema.zig
  src/TypedValue.zig
  src/Zir.zig
  src/print_air.zig
  src/print_zir.zig
  src/type.zig
  src/value.zig
  test/behavior/member_func.zig
  test/cases/compile_errors/member_function_arg_mismatch.zig
Labels: breaking

#15734 std.crypto: expose Fe isOdd & add basic parity tests for each pcurve
  lib/std/crypto/pcurves/p256/scalar.zig
  lib/std/crypto/pcurves/p384/scalar.zig
  lib/std/crypto/pcurves/secp256k1/scalar.zig
  lib/std/crypto/pcurves/tests/p256.zig
  lib/std/crypto/pcurves/tests/p384.zig
  lib/std/crypto/pcurves/tests/secp256k1.zig
Labels: standard library

#15811 std.c: openbsd sigcontext/ucontext fix enum
  lib/std/c/openbsd.zig
Labels: os-openbsd

#15795 std.crypto.ff - Alloc-free, constant-time field arithmetic for crypto
  lib/std/crypto.zig
  lib/std/crypto/Certificate.zig
  lib/std/crypto/ff.zig
  lib/std/crypto/tls/Client.zig
Labels: standard library

#15809 std.crypto.chacha: support larger vectors on AVX2 and AVX512 targets
  lib/std/crypto/chacha20.zig
  lib/std/rand/ChaCha.zig
Labels: standard library

#15815 Make Poly1305 faster by leveraging @addWithOverflow/@subWithOverflow
  lib/std/crypto/poly1305.zig
Labels: standard library

#15810 autodoc: Links to private decls now lead to source files
  lib/docs/main.js
Labels: autodoc

#15730 Fixes `WriteFile.getFileSource` failure on Windows
  lib/std/Build.zig
  lib/std/Build/Step/WriteFile.zig
  test/src/Cases.zig
  test/src/CompareOutput.zig
  test/src/StackTrace.zig
  test/src/run_translated_c.zig
  test/src/translate_c.zig
  test/tests.zig
Labels: breaking, zig build system
