Repository ziglang/zig, pull requests merged in 2023-01, with the labels that each got.

#13699 give BSDs some attention
  CMakeLists.txt
  build.zig
  lib/libcxx/include/__config
  lib/libcxx/include/__locale
  lib/libcxx/include/locale
  lib/libcxx/src/locale.cpp
  lib/std/c/dragonfly.zig
  lib/std/c/freebsd.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
  lib/std/fs.zig
  lib/std/fs/test.zig
  lib/std/os.zig
  lib/std/os/test.zig
  lib/std/target.zig
  src/link/Elf.zig
Labels: os-freebsd, os-netbsd, os-openbsd, os-dragonfly

#14153 stage3 macos: enable -headerpad_max_install_names
  build.zig
Labels: os-macos

#14181 std: collect all options under one namespace
  lib/std/crypto/tlcsprng.zig
  lib/std/debug.zig
  lib/std/event/batch.zig
  lib/std/event/loop.zig
  lib/std/fs.zig
  lib/std/fs/file.zig
  lib/std/io.zig
  lib/std/log.zig
  lib/std/start.zig
  lib/std/std.zig
  lib/test_runner.zig
  src/crash_report.zig
  src/main.zig
  test/behavior/pointers.zig
  test/compare_output.zig
  test/standalone/issue_7030/main.zig
  test/standalone/issue_9693/main.zig
Labels: breaking, standard library

#14214 zig.h: do not assume __GNUC__ is not clang
  lib/zig.h
Labels: os-macos

#14225 stage3 bsd: support dynamic libstdc++/libc++
  build.zig
Labels: os-freebsd, os-netbsd, os-openbsd, os-dragonfly

#14252 Update wasi-libc to a1c7c2c7a4b2813c6f67bd2ef6e0f430d31cebad
  lib/libc/include/wasm-wasi-musl/wasi/api.h
  lib/libc/wasi/libc-bottom-half/cloudlibc/src/libc/dirent/scandirat.c
  lib/libc/wasi/libc-bottom-half/signal/signal.c
  lib/libc/wasi/libc-bottom-half/sources/__wasilibc_real.c
  lib/libc/wasi/libc-bottom-half/sources/isatty.c
  lib/libc/wasi/libc-bottom-half/sources/posix.c
  lib/libc/wasi/libc-top-half/musl/include/pthread.h
  lib/libc/wasi/libc-top-half/musl/include/unistd.h
  lib/libc/wasi/libc-top-half/musl/src/env/__init_tls.c
  lib/libc/wasi/libc-top-half/musl/src/include/pthread.h
  lib/libc/wasi/libc-top-half/musl/src/internal/pthread_impl.h
  lib/libc/wasi/libc-top-half/musl/src/thread/__wait.c
  lib/libc/wasi/libc-top-half/musl/src/thread/pthread_attr_get.c
  lib/libc/wasi/libc-top-half/musl/src/thread/pthread_barrier_destroy.c
  lib/libc/wasi/libc-top-half/musl/src/thread/pthread_barrier_wait.c
  lib/libc/wasi/libc-top-half/musl/src/thread/pthread_create.c
  lib/libc/wasi/libc-top-half/musl/src/thread/pthread_key_create.c
Labels: os-wasi

#14363 FreeBSD: add mcontext_t for aarch64
  lib/std/c/freebsd.zig
  lib/std/debug.zig
  src/crash_report.zig
Labels: enhancement, os-freebsd, arch-aarch64

#14440 std: remove meta.assumeSentinel
  lib/std/fs.zig
  lib/std/meta.zig
  lib/std/os/linux/vdso.zig
Labels: breaking, standard library

#14417 std: restrict mem.span() and mem.len() to sentinel terminated pointers
  lib/std/Thread.zig
  lib/std/bounded_array.zig
  lib/std/cstr.zig
  lib/std/fs.zig
  lib/std/io/fixed_buffer_stream.zig
  lib/std/mem.zig
  src/link/MachO/load_commands.zig
  src/main.zig
  test/behavior/basic.zig
Labels: breaking, standard library
