Repository ziglang/zig, pull requests merged in 2023-11, with the labels that each got.

#17815 wasm-linker: implement `-fno-entry` and correctly pass `--shared` and `--pie` when given
  doc/langref.html.in
  lib/std/Build/Step/Compile.zig
  lib/std/start.zig
  src/link/Wasm.zig
  src/main.zig
  test/link/elf.zig
  test/link/macho/entry/build.zig
  test/link/macho/entry_in_dylib/build.zig
  test/link/wasm/archive/build.zig
  test/link/wasm/basic-features/build.zig
  test/link/wasm/bss/build.zig
  test/link/wasm/export-data/build.zig
  test/link/wasm/export/build.zig
  test/link/wasm/extern-mangle/build.zig
  test/link/wasm/function-table/build.zig
  test/link/wasm/infer-features/build.zig
  test/link/wasm/producers/build.zig
  test/link/wasm/segments/build.zig
  test/link/wasm/shared-memory/build.zig
  test/link/wasm/stack_pointer/build.zig
  test/link/wasm/type/build.zig
Labels: breaking

#18061 std: remove meta.trait
  CMakeLists.txt
  lib/std/array_hash_map.zig
  lib/std/atomic/Atomic.zig
  lib/std/enums.zig
  lib/std/fmt.zig
  lib/std/hash/auto_hash.zig
  lib/std/hash/xxhash.zig
  lib/std/hash_map.zig
  lib/std/io/bit_reader.zig
  lib/std/io/bit_writer.zig
  lib/std/io/test.zig
  lib/std/json/static.zig
  lib/std/json/stringify.zig
  lib/std/math.zig
  lib/std/mem.zig
  lib/std/meta.zig
  lib/std/meta/trait.zig
  lib/std/rand.zig
  lib/std/target.zig
  src/link/Wasm/Object.zig
  src/translate_c.zig
  test/behavior/vector.zig
  test/cases/compile_errors/generic_instantiation_failure_in_generic_function_return_type.zig
Labels: breaking, standard library

#18067 std: use BoundedArray less
  deps/aro/aro/Compilation.zig
  deps/aro/aro/Driver/GCCDetector.zig
  deps/aro/aro/Parser.zig
  deps/aro/aro/text_literal.zig
  lib/std/array_list.zig
  lib/std/crypto/ff.zig
  lib/std/fs.zig
  src/resinator/parse.zig
  tools/gen_spirv_spec.zig
Labels: breaking, standard library

#18076 std.fs: Absorb `IterableDir` into `Dir`
  CMakeLists.txt
  lib/std/Build/Step/InstallDir.zig
  lib/std/child_process.zig
  lib/std/crypto/Certificate/Bundle.zig
  lib/std/fs.zig
  lib/std/fs/AtomicFile.zig
  lib/std/fs/Dir.zig
  lib/std/fs/File.zig
  lib/std/fs/file.zig
  lib/std/fs/test.zig
  lib/std/os.zig
  lib/std/testing.zig
  src/Package/Fetch.zig
  src/Package/Fetch/git.zig
  src/main.zig
  src/windows_sdk.zig
  test/src/Cases.zig
  test/tests.zig
  tools/generate_JSONTestSuite.zig
  tools/process_headers.zig
  tools/update-license-headers.zig
  tools/update-linux-headers.zig
  tools/update_glibc.zig
  tools/update_spirv_features.zig
Labels: breaking, standard library

#18085 rework std.atomic
  CMakeLists.txt
  lib/std/Thread.zig
  lib/std/Thread/Condition.zig
  lib/std/Thread/Futex.zig
  lib/std/Thread/Mutex.zig
  lib/std/Thread/ResetEvent.zig
  lib/std/Thread/RwLock.zig
  lib/std/Thread/WaitGroup.zig
  lib/std/atomic.zig
  lib/std/atomic/Atomic.zig
  lib/std/atomic/queue.zig
  lib/std/atomic/stack.zig
  lib/std/child_process.zig
  lib/std/debug.zig
  lib/std/event/loop.zig
  lib/std/os.zig
  src/crash_report.zig
Labels: breaking, standard library

#18128 bsd: debitrot atomic and debug
  lib/std/Thread/Futex.zig
  lib/std/debug.zig
Labels: standard library, os-freebsd, os-netbsd, os-openbsd, os-dragonfly, os-wasi
