Repository ziglang/zig, pull requests merged in 2023-08, with the labels that each got.

#16645 CLI: stop special-casing LLVM, LLD, and Clang
  lib/std/Build/Step/Compile.zig
  src/main.zig
Labels: breaking

#16755 linux: search for system libc++
  build.zig
Labels: os-linux, linking

#16818 build: do not emit `-iwithsysroot`/`-iframeworkwithsysroot` implicitly
  build.zig
  lib/std/Build/Step/CheckObject.zig
  lib/std/Build/Step/Compile.zig
  lib/std/macho.zig
  src/main.zig
  test/standalone.zig
  test/standalone/ios/build.zig
  test/standalone/ios/main.m
  test/tests.zig
Labels: breaking, zig build system, zig cc

#16917 compiler: move unions into InternPool
  lib/std/dwarf/call_frame.zig
  lib/std/meta.zig
  src/AstGen.zig
  src/InternPool.zig
  src/Module.zig
  src/Sema.zig
  src/TypedValue.zig
  src/Zir.zig
  src/arch/aarch64/abi.zig
  src/arch/arm/abi.zig
  src/arch/wasm/CodeGen.zig
  src/arch/wasm/abi.zig
  src/arch/x86_64/CodeGen.zig
  src/arch/x86_64/abi.zig
  src/codegen.zig
  src/codegen/c.zig
  src/codegen/c/type.zig
  src/codegen/llvm.zig
  src/codegen/spirv.zig
  src/link/Dwarf.zig
  src/type.zig
  src/value.zig
  test/behavior/union.zig
  test/cases/compile_errors/access_inactive_union_field_comptime.zig
  test/cases/compile_errors/dereference_anyopaque.zig
  test/cases/compile_errors/directly_embedding_opaque_type_in_struct_and_union.zig
  test/cases/compile_errors/non-const_variables_of_things_that_require_const_variables.zig
Labels: breaking

#16953 std.os.uefi: reorganize namespaces
  lib/std/builtin.zig
  lib/std/os/uefi.zig
  lib/std/os/uefi/device_path.zig
  lib/std/os/uefi/hii.zig
  lib/std/os/uefi/protocol.zig
  lib/std/os/uefi/protocol/absolute_pointer.zig
  lib/std/os/uefi/protocol/block_io.zig
  lib/std/os/uefi/protocol/device_path.zig
  lib/std/os/uefi/protocol/edid.zig
  lib/std/os/uefi/protocol/file.zig
  lib/std/os/uefi/protocol/graphics_output.zig
  lib/std/os/uefi/protocol/hii_database.zig
  lib/std/os/uefi/protocol/hii_popup.zig
  lib/std/os/uefi/protocol/ip6.zig
  lib/std/os/uefi/protocol/ip6_config.zig
  lib/std/os/uefi/protocol/ip6_service_binding.zig
  lib/std/os/uefi/protocol/loaded_image.zig
  lib/std/os/uefi/protocol/managed_network.zig
  lib/std/os/uefi/protocol/rng.zig
  lib/std/os/uefi/protocol/shell_parameters.zig
  lib/std/os/uefi/protocol/simple_file_system.zig
  lib/std/os/uefi/protocol/simple_network.zig
  lib/std/os/uefi/protocol/simple_pointer.zig
  lib/std/os/uefi/protocol/simple_text_input.zig
  lib/std/os/uefi/protocol/simple_text_input_ex.zig
  lib/std/os/uefi/protocol/simple_text_output.zig
  lib/std/os/uefi/protocol/udp6.zig
  lib/std/os/uefi/protocol/udp6_service_binding.zig
  lib/std/os/uefi/protocols.zig
  lib/std/os/uefi/protocols/absolute_pointer_protocol.zig
  lib/std/os/uefi/protocols/block_io_protocol.zig
  lib/std/os/uefi/protocols/device_path_protocol.zig
  lib/std/os/uefi/protocols/edid_active_protocol.zig
  lib/std/os/uefi/protocols/edid_discovered_protocol.zig
  lib/std/os/uefi/protocols/edid_override_protocol.zig
  lib/std/os/uefi/protocols/file_protocol.zig
  lib/std/os/uefi/protocols/graphics_output_protocol.zig
  lib/std/os/uefi/protocols/hii_popup_protocol.zig
  lib/std/os/uefi/protocols/ip6_config_protocol.zig
  lib/std/os/uefi/protocols/ip6_protocol.zig
  lib/std/os/uefi/protocols/managed_network_protocol.zig
  lib/std/os/uefi/protocols/managed_network_service_binding_protocol.zig
  lib/std/os/uefi/protocols/simple_network_protocol.zig
  lib/std/os/uefi/protocols/simple_pointer_protocol.zig
  lib/std/os/uefi/protocols/simple_text_input_ex_protocol.zig
  lib/std/os/uefi/protocols/udp6_protocol.zig
  lib/std/os/uefi/tables/boot_services.zig
  lib/std/os/uefi/tables/system_table.zig
Labels: breaking, standard library, os-uefi
