Repository ziglang/zig, pull requests merged in 2024-01, with the labels that each got.

#18275 std.heap: add runtime safety for calling `stackFallback(N).get` multiple times
  deps/aro/aro/Compilation.zig
  lib/std/heap.zig
Labels: standard library

#18366 Update styles in std docs to correct display glitch
  lib/docs/index.html
Labels: autodoc

#18586 Move the extern paragraph to a more logical place
  doc/langref.html.in
Labels: docs

#17467 byos: Ease `GeneralPurposeAllocator` integration
  lib/std/debug.zig
  lib/std/heap.zig
Labels: os-bring-your-own

#18219 Minor improvements to the Optionals documentation
  doc/langref.html.in
Labels: docs

#18622 build system: better handle modules that do not have a zig root source file
  lib/std/Build/Step/Compile.zig
  src/Compilation.zig
  src/main.zig
Labels: zig build system

#18394 langref: add information about doctests
  doc/langref.html.in
Labels: docs
