Repository ziglang/zig, pull requests merged in 2024-06, with the labels that each got.

#20167 Replace the `YES_COLOR` env variable with `CLICOLOR_FORCE`
  lib/compiler/build_runner.zig
  lib/std/io/tty.zig
  lib/std/zig.zig
  src/main.zig
  test/src/StackTrace.zig
  tools/doctest.zig
Labels: breaking, release notes

#20213 Document a few non-obvious variable assignments
  doc/langref/test_basic_slices.zig
  doc/langref/test_multidimensional_arrays.zig
  doc/langref/test_union_method.zig
Labels: docs

#20321 enhance `std.Build.Step.Fmt` and use it more
  build.zig
  ci/aarch64-linux-debug.sh
  ci/aarch64-linux-release.sh
  ci/x86_64-linux-debug.sh
  ci/x86_64-linux-release.sh
  lib/std/Build/Step.zig
  lib/std/Build/Step/Fmt.zig
  lib/std/Progress.zig
  lib/std/process/Child.zig
Labels: zig build system, release notes

#20352 Parse WASM linker flags as base 10, like clang
  src/main.zig
Labels: breaking
