Repository ziglang/zig, pull requests merged in 2024-03, with the labels that each got.

#18797 Set the reference's `color-scheme` property to make scrollbars the correct color
  doc/langref.html.in
Labels: docs

#19214 std: fuck usingnamespace
  CMakeLists.txt
  lib/std/c.zig
  lib/std/c/openbsd.zig
  lib/std/enums.zig
  lib/std/os/linux.zig
  lib/std/os/linux/IoUring.zig
  lib/std/os/linux/io_uring_sqe.zig
  lib/std/os/linux/test.zig
  lib/std/os/windows.zig
Labels: breaking, standard library

#18779 bsd: add missing os.IFNAMESIZE
  lib/std/c/dragonfly.zig
  lib/std/c/netbsd.zig
  lib/std/c/openbsd.zig
Labels: os-netbsd, os-openbsd, os-dragonfly

#19303 langref: add basic documentation of RLS
  doc/langref.html.in
Labels: docs

#19156 macos: archive size fix
  src/link/MachO/Archive.zig
Labels: os-macos, linking

#17719 std: introduce pointer stability locks to hash maps
  lib/std/array_hash_map.zig
  lib/std/debug.zig
  lib/std/hash_map.zig
Labels: enhancement, standard library, release notes

#19325 std: adjust DynLib API
  lib/std/c.zig
  lib/std/dynamic_library.zig
  lib/std/os.zig
Labels: standard library

#19360 std: don't do BYOS at the POSIX API layer
  lib/std/os/linux.zig
  lib/std/posix.zig
Labels: breaking, standard library

#19388 cache system file deduplication
  lib/std/Build/Cache.zig
  lib/std/Build/Cache/Directory.zig
  lib/std/Build/Cache/Path.zig
  lib/std/Build/Step.zig
  lib/std/array_hash_map.zig
  src/Compilation.zig
  src/Package.zig
  src/Package/Fetch.zig
  src/Package/Module.zig
  src/glibc.zig
  src/main.zig
Labels: release notes
