Repository ziglang/zig, pull requests merged in 2024-05, with the labels that each got.

#19889 [docs] add examples of array/slice init using result location
  doc/langref/test_arrays.zig
  doc/langref/test_basic_slices.zig
Labels: docs

#20049 std: restructure child process namespace
  CMakeLists.txt
  lib/compiler/aro/aro/Driver.zig
  lib/compiler/std-docs.zig
  lib/std/Build.zig
  lib/std/Build/Step.zig
  lib/std/child_process.zig
  lib/std/process.zig
  lib/std/process/Child.zig
  lib/std/std.zig
  lib/std/zig/LibCInstallation.zig
  src/Compilation.zig
  src/link.zig
  src/link/Coff.zig
  src/link/Wasm.zig
  src/main.zig
  test/src/Cases.zig
  test/standalone/child_process/main.zig
  test/standalone/windows_bat_args/fuzz.zig
  test/standalone/windows_bat_args/test.zig
  test/standalone/windows_spawn/main.zig
  tools/docgen.zig
  tools/generate_linux_syscalls.zig
  tools/update_clang_options.zig
  tools/update_cpu_features.zig
Labels: breaking, standard library, release notes

#20140 std.Build.Step.Run: global lock when child inherits stderr
  lib/std/Build/Step/Run.zig
Labels: zig build system, release notes
