Repository ziglang/zig, pull requests merged in 2024-12, with the labels that each got.

#22180 compiler: Only omit frame pointers by default for `ReleaseSmall`
  src/Package/Module.zig
Labels: release notes

#22202 std.Build.Cache.hit: more discipline in error handling
  lib/std/Build/Cache.zig
  lib/std/Build/Step.zig
  lib/std/posix.zig
  src/Compilation.zig
  src/Zcu/PerThread.zig
  src/link.zig
Labels: breaking, standard library

#22243 Sema: disallow unsafe in-memory coercions
  lib/compiler/build_runner.zig
  lib/std/c/darwin.zig
  src/DarwinPosixSpawn.zig
  src/Sema.zig
  src/clang.zig
  src/link/Coff.zig
  src/translate_c.zig
  test/cases/compile_errors/implicit_cast_between_C_pointer_and_Zig_pointer-bad_const-align-child.zig
  test/cases/compile_errors/implicit_casting_C_pointers_which_would_mess_up_null_semantics.zig
  test/cases/compile_errors/invalid_pointer_coercions.zig
  test/cases/compile_errors/use_implicit_casts_to_assign_null_to_non-nullable_pointer.zig
Labels: breaking

#22264 compiler: disallow `callconv` etc from depending on function parameters
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/InternPool.zig
  src/Sema.zig
  src/Value.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
  src/print_zir.zig
  test/behavior/align.zig
  test/behavior/fn.zig
  test/behavior/type_info.zig
  test/cases/compile_errors/comptime_only_global_align_section_addrspace.zig
  test/cases/compile_errors/invalid_variadic_function.zig
  test/link/macho.zig
Labels: breaking, release notes

#22352 Zir: attach reason to `block_comptime` and improve corresponding error reporting
  lib/std/zig.zig
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Compilation.zig
  src/Sema.zig
  src/Zcu/PerThread.zig
  src/print_zir.zig
  test/cases/compile_errors/address_of_threadlocal_not_comptime_known.zig
  test/cases/compile_errors/anytype_param_requires_comptime.zig
  test/cases/compile_errors/array_mult_with_number_type.zig
  test/cases/compile_errors/asm_at_compile_time.zig
  test/cases/compile_errors/attempted_double_pipe_on_boolean_values.zig
  test/cases/compile_errors/branch_in_comptime_only_scope_uses_condbr_inline.zig
  test/cases/compile_errors/builtin_extern_in_comptime_scope.zig
  test/cases/compile_errors/compile_time_struct_field.zig
  test/cases/compile_errors/condition_comptime_reason_explained.zig
  test/cases/compile_errors/enum_backed_by_comptime_int_must_be_casted_from_comptime_value.zig
  test/cases/compile_errors/error_in_typeof_param.zig
  test/cases/compile_errors/explain_why_fn_is_called_at_comptime.zig
  test/cases/compile_errors/explain_why_generic_fn_is_called_at_comptime.zig
  test/cases/compile_errors/global_var_struct_init_in_comptime_block.zig
  test/cases/compile_errors/global_variable_stored_in_global_const.zig
  test/cases/compile_errors/incorrect_pointer_dereference_syntax.zig
  test/cases/compile_errors/inline_call_runtime_value_to_comptime_param.zig
  test/cases/compile_errors/int-float_conversion_to_comptime_int-float.zig
  test/cases/compile_errors/non-const_expression_function_call_with_struct_return_value_outside_function.zig
  test/cases/compile_errors/non-pure_function_returns_type.zig
  test/cases/compile_errors/non_comptime_param_in_comptime_function.zig
  test/cases/compile_errors/non_constant_expression_in_array_size.zig
  test/cases/compile_errors/runtime_assignment_to_comptime_struct_type.zig
  test/cases/compile_errors/runtime_assignment_to_comptime_union_type.zig
  test/cases/compile_errors/runtime_operation_in_comptime_scope.zig
  test/cases/compile_errors/runtime_to_comptime_num.zig
  test/cases/compile_errors/runtime_value_in_comptime_scope.zig
  test/cases/compile_errors/slice_of_single-item_pointer_bounds.zig
  test/cases/compile_errors/unable_to_evaluate_comptime_expr.zig
  test/cases/compile_errors/unable_to_evaluate_expr_inside_cimport.zig
  test/compile_errors.zig
Labels: release notes
