Repository ziglang/zig, pull requests merged in 2024-08, with the labels that each got.

#20885 std.zig.tokenizer: simplification and spec conformance
  lib/std/crypto/ml_kem.zig
  lib/std/macho.zig
  lib/std/unicode.zig
  lib/std/zig/Ast.zig
  lib/std/zig/AstGen.zig
  lib/std/zig/parser_test.zig
  lib/std/zig/string_literal.zig
  lib/std/zig/system/darwin/macos.zig
  lib/std/zig/system/linux.zig
  lib/std/zig/tokenizer.zig
  src/Package/Manifest.zig
  src/link/tapi/yaml/test.zig
  test/cases/compile_errors/empty_char_lit.zig
  test/cases/compile_errors/invalid_legacy_unicode_escape.zig
  test/cases/compile_errors/invalid_unicode_escape.zig
  test/cases/compile_errors/normal_string_with_newline.zig
  test/compile_errors.zig
  test/run_translated_c.zig
  test/translate_c.zig
Labels: breaking, standard library, release notes

#20867 `std.atomic`: Don't lie to the compiler about memory clobbers in spinLoopHint().
  lib/std/atomic.zig
Labels: standard library, release notes

#20903 std: dwarf namespace reorg + bonus commits
  lib/compiler/test_runner.zig
  lib/std/debug.zig
  lib/std/debug/Dwarf.zig
  lib/std/debug/Dwarf/abi.zig
  lib/std/debug/Dwarf/call_frame.zig
  lib/std/debug/Dwarf/expression.zig
  lib/std/dwarf.zig
  lib/std/fs/Dir.zig
  src/target.zig
  test/tests.zig
Labels: breaking, standard library, release notes

#20908 std.debug: reorg and clarify API goals
  lib/std/debug.zig
  lib/std/debug/Dwarf.zig
  lib/std/debug/Dwarf/abi.zig
  lib/std/debug/Dwarf/call_frame.zig
  lib/std/debug/Dwarf/expression.zig
  lib/std/debug/MemoryAccessor.zig
  lib/std/debug/Pdb.zig
  lib/std/debug/SelfInfo.zig
  lib/std/pdb.zig
  src/crash_report.zig
  test/standalone/coff_dwarf/main.zig
Labels: release notes

#20927 Improve and simplify `std.sort.binarySort` and friends' APIs
  lib/compiler/aro/aro/Preprocessor.zig
  lib/std/debug/SelfInfo.zig
  lib/std/sort.zig
Labels: standard library, release notes

#20953 Ecdsa cross compilation fix + api change
  lib/std/crypto/ecdsa.zig
Labels: breaking, standard library, release notes

#20958 introduce a fuzz testing web interface
  README.md
  lib/compiler/build_runner.zig
  lib/compiler/std-docs.zig
  lib/compiler/test_runner.zig
  lib/docs/wasm/Decl.zig
  lib/docs/wasm/Walk.zig
  lib/docs/wasm/html_render.zig
  lib/docs/wasm/main.zig
  lib/fuzzer.zig
  lib/fuzzer/index.html
  lib/fuzzer/main.js
  lib/fuzzer/wasm/main.zig
  lib/std/Build.zig
  lib/std/Build/Cache/Path.zig
  lib/std/Build/Fuzz.zig
  lib/std/Build/Fuzz/WebServer.zig
  lib/std/Build/Fuzz/abi.zig
  lib/std/Build/Step.zig
  lib/std/Build/Step/Run.zig
  lib/std/debug.zig
  lib/std/debug/Coverage.zig
  lib/std/debug/Dwarf.zig
  lib/std/debug/FixedBufferReader.zig
  lib/std/debug/Info.zig
  lib/std/debug/SelfInfo.zig
  lib/std/http.zig
  lib/std/http/WebSocket.zig
  lib/std/posix.zig
  lib/std/zig/Server.zig
  lib/std/zig/tokenizer.zig
  src/Compilation.zig
  test/standalone/coff_dwarf/build.zig
  test/standalone/coff_dwarf/main.zig
  tools/dump-cov.zig
Labels: zig build system, release notes, fuzzing

#20973 std.json: fix partial strings getting dropped when multi-byte codepoints span input buffers
  lib/std/json/scanner.zig
  lib/std/json/scanner_test.zig
Labels: standard library

#20979 language: add module name field to `@src`
  lib/std/builtin.zig
  src/Sema.zig
  test/behavior/src.zig
Labels: release notes

#21012 std.crypto: better names for everything in utils
  doc/langref.html.in
  lib/std/crypto.zig
  lib/std/crypto/aegis.zig
  lib/std/crypto/aes_gcm.zig
  lib/std/crypto/aes_ocb.zig
  lib/std/crypto/ascon.zig
  lib/std/crypto/bcrypt.zig
  lib/std/crypto/chacha20.zig
  lib/std/crypto/ff.zig
  lib/std/crypto/ghash_polyval.zig
  lib/std/crypto/isap.zig
  lib/std/crypto/keccak_p.zig
  lib/std/crypto/ml_kem.zig
  lib/std/crypto/pcurves/common.zig
  lib/std/crypto/poly1305.zig
  lib/std/crypto/salsa20.zig
  lib/std/crypto/timing_safe.zig
  lib/std/crypto/tlcsprng.zig
Labels: standard library, release notes

#21135 incremental: more progress
  lib/compiler/aro/aro/Builtins/Builtin.zig
  lib/compiler/aro/aro/Parser.zig
  lib/std/crypto/aes/soft.zig
  lib/std/crypto/blake2.zig
  lib/std/crypto/pcurves/p384.zig
  lib/std/enums.zig
  lib/std/hash/xxhash.zig
  lib/std/math.zig
  lib/std/math/hypot.zig
  lib/std/math/nextafter.zig
  lib/std/unicode.zig
  lib/std/zig/AstGen.zig
  src/InternPool.zig
  src/Sema.zig
  src/register_manager.zig
  test/incremental/delete_comptime_decls
  test/incremental/modify_inline_fn
  test/incremental/move_src
Labels: breaking, release notes

#21231 AstGen: disallow fields and decls from sharing names
  CMakeLists.txt
  lib/std/crypto/poly1305.zig
  lib/std/debug/Pdb.zig
  lib/std/debug/SelfInfo.zig
  lib/std/enums.zig
  lib/std/heap/sbrk_allocator.zig
  lib/std/meta.zig
  lib/std/os/uefi/device_path.zig
  lib/std/pdb.zig
  lib/std/zig/AstGen.zig
  src/arch/aarch64/bits.zig
  src/arch/arm/bits.zig
  src/arch/x86_64/CodeGen.zig
  src/arch/x86_64/Disassembler.zig
  src/arch/x86_64/Lower.zig
  src/arch/x86_64/Mir.zig
  src/arch/x86_64/encoder.zig
  src/codegen.zig
  src/codegen/llvm/BitcodeReader.zig
  src/link/Elf.zig
  src/link/Elf/Atom.zig
  src/link/Elf/Thunk.zig
  src/link/Elf/thunks.zig
  src/link/MachO.zig
  src/link/MachO/Atom.zig
  src/link/MachO/Thunk.zig
  src/link/MachO/synthetic.zig
  src/link/MachO/thunks.zig
  test/behavior/call.zig
  test/behavior/packed-union.zig
  test/behavior/struct.zig
  test/behavior/union.zig
  test/cases/compile_errors/colliding_invalid_top_level_functions.zig
  test/cases/compile_errors/decl_shadows_local.zig
  test/cases/compile_errors/duplicate_enum_field.zig
  test/cases/compile_errors/duplicate_struct_field.zig
  test/cases/compile_errors/duplicate_union_field.zig
  test/cases/compile_errors/error_in_struct_initializer_doesnt_crash_the_compiler.zig
  test/cases/compile_errors/field_decl_name_conflict.zig
  test/cases/compile_errors/invalid_duplicate_test_decl_name.zig
  test/cases/compile_errors/invalid_store_to_comptime_field.zig
  test/cases/compile_errors/multiple_function_definitions.zig
  test/cases/compile_errors/redefinition_of_enums.zig
  test/cases/compile_errors/redefinition_of_global_variables.zig
  test/cases/compile_errors/redefinition_of_struct.zig
  test/cases/compile_errors/struct_duplicate_field_name.zig
  test/cases/compile_errors/union_duplicate_enum_field.zig
  test/cases/compile_errors/union_duplicate_field_definition.zig
  test/cases/function_redeclaration.zig
  test/cases/global_variable_redeclaration.zig
  test/compile_errors.zig
Labels: breaking, release notes
