Repository ziglang/zig, pull requests merged in 2024-04, with the labels that each got.

#19260 macos: add zippered support
  lib/compiler/libc.zig
  lib/std/Target/Query.zig
  lib/std/zig/LibCInstallation.zig
  lib/std/zig/system/darwin.zig
  src/link/MachO.zig
  src/link/MachO/Dylib.zig
Labels: os-macos, linking

#18925 Sema: support coercing ref to anonymous array init to many-pointer
  src/Sema.zig
  test/behavior/array.zig
Labels: release notes

#18988 std.Build: add `lazyImport` (`@import` for lazy dependencies)
  lib/compiler/build_runner.zig
  lib/std/Build.zig
  lib/std/math/nextafter.zig
  src/Sema.zig
  test/behavior/fn.zig
Labels: zig build system, release notes

#18920 `std.zig.fmtId`: conditionally escape primitives/`_` (breaking)
  lib/compiler/aro_translate_c/ast.zig
  lib/compiler/test_runner.zig
  lib/std/Build/Step/Options.zig
  lib/std/zig.zig
  lib/std/zig/render.zig
  src/Builtin.zig
  src/InternPool.zig
  src/main.zig
  src/print_zir.zig
  tools/gen_spirv_spec.zig
  tools/generate_linux_syscalls.zig
  tools/update_cpu_features.zig
  tools/update_spirv_features.zig
Labels: breaking, standard library

#19597 introduce std.Build.path; deprecate LazyPath.relative
  lib/std/Build.zig
  lib/std/Build/Step/Compile.zig
  lib/std/Build/Step/ConfigHeader.zig
  test/standalone/test_runner_module_imports/build.zig
  test/standalone/test_runner_path/build.zig
Labels: breaking, zig build system, release notes

#19579 Document packed struct's backing int declaration
  doc/langref.html.in
Labels: docs

#19657 std.fs.Dir.Walker: maintain a null byte in path names
  lib/std/fs/Dir.zig
Labels: breaking, standard library

#19705 Fix WASI threads, again
  lib/std/Thread.zig
Labels: os-wasi

#19743 std.Build: Install Windows DLLs to `<prefix>/bin/` by default
  lib/std/Build/Step/Compile.zig
  lib/std/Build/Step/InstallArtifact.zig
Labels: breaking, zig build system, release notes

#19698 std.process.Child: Mitigate arbitrary command execution vulnerability on Windows (BatBadBut)
  lib/std/child_process.zig
  lib/std/os/windows/kernel32.zig
  lib/std/unicode.zig
  test/standalone/build.zig.zon
  test/standalone/windows_bat_args/build.zig
  test/standalone/windows_bat_args/echo-args.zig
  test/standalone/windows_bat_args/fuzz.zig
  test/standalone/windows_bat_args/test.zig
Labels: release notes

#19768 std.posix.iovec: use .base and .len instead of .iov_base and .iov_len
  lib/compiler/objcopy.zig
  lib/std/crypto/tls/Client.zig
  lib/std/fs/File.zig
  lib/std/fs/test.zig
  lib/std/http/Client.zig
  lib/std/http/Server.zig
  lib/std/net.zig
  lib/std/os/linux.zig
  lib/std/os/linux/IoUring.zig
  lib/std/os/linux/io_uring_sqe.zig
  lib/std/posix.zig
  lib/std/posix/test.zig
  lib/std/zig/Server.zig
  src/Compilation.zig
  src/Module.zig
  src/link/C.zig
  src/link/Dwarf.zig
  src/link/Elf/ZigObject.zig
  src/link/Elf/synthetic_sections.zig
  src/link/Plan9.zig
  src/link/Wasm.zig
Labels: breaking, standard library, release notes

#19784 std.hash.crc: simplify api
  lib/std/debug.zig
  lib/std/hash/benchmark.zig
  lib/std/hash/crc.zig
  lib/std/hash/crc/impl.zig
  lib/std/hash/crc/test.zig
  tools/crc/catalog.txt
  tools/update_crc_catalog.zig
Labels: breaking, standard library, release notes
