Repository ziglang/zig, pull requests merged in 2024-07, with the labels that each got.

#20446 Rename nonSIMDCall* to nonSimdCall*
  lib/std/valgrind.zig
Labels: breaking, standard library

#20475 build: fix WriteFile and addCSourceFiles not adding LazyPath deps
  lib/std/Build/Module.zig
  lib/std/Build/Step/WriteFile.zig
  test/src/Cases.zig
  test/src/CompareOutput.zig
  test/src/RunTranslatedC.zig
  test/src/StackTrace.zig
  test/src/TranslateC.zig
  test/standalone/build.zig.zon
  test/standalone/dep_lazypath/build.zig
  test/standalone/dep_lazypath/inc/foo.h
  test/standalone/dep_lazypath/inctest.zig
  test/tests.zig
Labels: breaking, zig build system, release notes

#20542 std.fs.Dir: Rename OpenDirOptions to OpenOptions
  lib/std/Build/Cache/Path.zig
  lib/std/fs.zig
  lib/std/fs/Dir.zig
  lib/std/posix.zig
  lib/std/testing.zig
Labels: standard library, release notes

#20580 introduce file system watching features to the zig build system
  build.zig
  lib/compiler/build_runner.zig
  lib/compiler/objcopy.zig
  lib/std/Build.zig
  lib/std/Build/Cache.zig
  lib/std/Build/Cache/Path.zig
  lib/std/Build/Step.zig
  lib/std/Build/Step/CheckFile.zig
  lib/std/Build/Step/CheckObject.zig
  lib/std/Build/Step/ConfigHeader.zig
  lib/std/Build/Step/InstallDir.zig
  lib/std/Build/Step/InstallFile.zig
  lib/std/Build/Step/ObjCopy.zig
  lib/std/Build/Step/Options.zig
  lib/std/Build/Step/RemoveDir.zig
  lib/std/Build/Step/Run.zig
  lib/std/Build/Step/UpdateSourceFiles.zig
  lib/std/Build/Step/WriteFile.zig
  lib/std/Build/Watch.zig
  lib/std/os/linux.zig
  lib/std/posix.zig
  lib/std/zig/Server.zig
  src/Compilation.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
  src/main.zig
  test/tests.zig
Labels: breaking, zig build system, release notes

#20633 make zig compiler processes live across rebuilds
  lib/compiler/build_runner.zig
  lib/std/Build.zig
  lib/std/Build/Step.zig
  lib/std/Build/Step/CheckFile.zig
  lib/std/Build/Step/CheckObject.zig
  lib/std/Build/Step/Compile.zig
  lib/std/Build/Step/ConfigHeader.zig
  lib/std/Build/Step/Fail.zig
  lib/std/Build/Step/Fmt.zig
  lib/std/Build/Step/InstallArtifact.zig
  lib/std/Build/Step/InstallDir.zig
  lib/std/Build/Step/InstallFile.zig
  lib/std/Build/Step/ObjCopy.zig
  lib/std/Build/Step/Options.zig
  lib/std/Build/Step/RemoveDir.zig
  lib/std/Build/Step/Run.zig
  lib/std/Build/Step/TranslateC.zig
  lib/std/Build/Step/UpdateSourceFiles.zig
  lib/std/Build/Step/WriteFile.zig
  lib/std/Progress.zig
  lib/std/zig/Server.zig
  src/Compilation.zig
  src/Sema.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
  src/main.zig
  test/standalone/cmakedefine/build.zig
Labels: breaking, standard library, zig build system, release notes

#20632 InternPool: enable separate codegen/linking thread
  lib/std/Progress.zig
  lib/std/mem.zig
  src/InternPool.zig
  src/Zcu/PerThread.zig
  src/main.zig
  src/target.zig
Labels: release notes

#20731 The tale of parallel MachO: part 2
  build.zig
  src/Compilation.zig
  src/arch/x86_64/Emit.zig
  src/arch/x86_64/Lower.zig
  src/codegen.zig
  src/link.zig
  src/link/Elf.zig
  src/link/Elf/Atom.zig
  src/link/Elf/Object.zig
  src/link/Elf/eh_frame.zig
  src/link/Elf/relocatable.zig
  src/link/MachO.zig
  src/link/MachO/Archive.zig
  src/link/MachO/Atom.zig
  src/link/MachO/CodeSignature.zig
  src/link/MachO/Dylib.zig
  src/link/MachO/InternalObject.zig
  src/link/MachO/Object.zig
  src/link/MachO/Symbol.zig
  src/link/MachO/UnwindInfo.zig
  src/link/MachO/ZigObject.zig
  src/link/MachO/dead_strip.zig
  src/link/MachO/dyld_info/Rebase.zig
  src/link/MachO/dyld_info/Trie.zig
  src/link/MachO/dyld_info/bind.zig
  src/link/MachO/fat.zig
  src/link/MachO/file.zig
  src/link/MachO/hasher.zig
  src/link/MachO/relocatable.zig
  src/link/MachO/synthetic.zig
  src/link/MachO/thunks.zig
  src/link/Wasm.zig
  src/link/Wasm/Object.zig
  src/link/tapi.zig
  src/main.zig
Labels: release notes

#20706 `std.posix`: Make `sigaction()` infallible
  lib/std/Progress.zig
  lib/std/debug.zig
  lib/std/posix.zig
  lib/std/posix/test.zig
  lib/std/start.zig
  src/crash_report.zig
Labels: standard library, release notes

#20773 integrate fuzz testing into the build system
  lib/compiler/build_runner.zig
  lib/compiler/test_runner.zig
  lib/fuzzer.zig
  lib/std/Build.zig
  lib/std/Build/Fuzz.zig
  lib/std/Build/Step/Compile.zig
  lib/std/Build/Step/Run.zig
  lib/std/io/test.zig
  lib/std/testing.zig
  lib/std/zig/Client.zig
  lib/std/zig/Server.zig
  src/Compilation.zig
  src/codegen/llvm.zig
  src/link/Elf.zig
  src/main.zig
Labels: zig build system, release notes
