Repository ziglang/zig, pull requests merged in 2024-10, with the labels that each got.

#21585 remove `@fence`
  doc/langref.html.in
  lib/std/Thread/Futex.zig
  lib/std/Thread/ResetEvent.zig
  lib/std/Thread/WaitGroup.zig
  lib/std/atomic.zig
  lib/std/zig/AstGen.zig
  lib/std/zig/AstRlAnnotate.zig
  lib/std/zig/BuiltinFn.zig
  lib/std/zig/Zir.zig
  lib/zig.h
  src/Air.zig
  src/Air/types_resolved.zig
  src/Liveness.zig
  src/Liveness/Verify.zig
  src/Sema.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/arm/CodeGen.zig
  src/arch/riscv64/CodeGen.zig
  src/arch/sparc64/CodeGen.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/CodeGen.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/print_air.zig
  src/print_zir.zig
  test/behavior/atomics.zig
  test/behavior/builtin_functions_returning_void_or_noreturn.zig
  test/cases/compile_errors/atomic_orderings_of_fence_Acquire_or_stricter.zig
Labels: breaking, standard library, release notes

#21608 ppc64: get further along into system bootstrap
  lib/std/os/linux/powerpc64.zig
  lib/std/start.zig
Labels: arch-powerpc

#21622 bsd: revive freebsd and dragonfly
  lib/std/c.zig
  lib/std/posix.zig
Labels: os-freebsd, os-dragonfly

#21688 spirv: fix some bitrot
  src/codegen/spirv.zig
  src/link/SpirV.zig
  test/behavior/basic.zig
  test/behavior/decl_literals.zig
  test/behavior/eval.zig
  test/behavior/inline_switch.zig
  test/behavior/math.zig
  test/behavior/pointers.zig
  test/behavior/switch.zig
Labels: arch-spirv

#21732 compiler: implement `@FieldType`
  doc/langref.html.in
  lib/std/zig/AstGen.zig
  lib/std/zig/AstRlAnnotate.zig
  lib/std/zig/BuiltinFn.zig
  test/behavior/struct.zig
  test/behavior/union.zig
  test/cases/compile_errors/invalid_field_type_usage.zig
Labels: release notes
