Repository ziglang/zig, pull requests merged in 2024-11, with the labels that each got.

#21955 std.crypto: make the key pair API creation consistent
  lib/std/crypto/25519/ed25519.zig
  lib/std/crypto/25519/x25519.zig
  lib/std/crypto/benchmark.zig
  lib/std/crypto/ecdsa.zig
  lib/std/crypto/ml_kem.zig
  lib/std/crypto/salsa20.zig
  lib/std/crypto/tls/Client.zig
Labels: breaking, standard library

#21909 compiler: Disallow `align(0)` everywhere in the language.
  src/Sema.zig
  test/cases/compile_errors/align_zero.zig
  test/cases/compile_errors/function_alignment_on_unsupported_target.zig
Labels: breaking, release notes

#22063 dwarf: fix stepping through an inline loop containing one statement
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Air.zig
  src/Air/types_resolved.zig
  src/Liveness.zig
  src/Liveness/Verify.zig
  src/Sema.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/arm/CodeGen.zig
  src/arch/riscv64/CodeGen.zig
  src/arch/sparc64/CodeGen.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/CodeGen.zig
  src/arch/x86_64/Emit.zig
  src/arch/x86_64/Lower.zig
  src/arch/x86_64/Mir.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/dev.zig
  src/link/Dwarf.zig
  src/link/Elf/ZigObject.zig
  src/main.zig
  src/print_air.zig
  src/print_zir.zig
  test/src/Debugger.zig
Labels: release notes

#21858 add improved std.hash.int - deprecate std.hash.uint32
  lib/std/hash.zig
Labels: standard library, release notes

#22087 std.ArrayHashMap: add `reinit` method and other housekeeping, including the move towards "unmanaged" containers
  lib/std/array_hash_map.zig
Labels: standard library, release notes
