Repository ziglang/zig, pull requests merged in 2024-09, with the labels that each got.

#21264 compiler: implement decl literals
  lib/std/array_hash_map.zig
  lib/std/array_list.zig
  lib/std/hash_map.zig
  lib/std/heap/general_purpose_allocator.zig
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Sema.zig
  src/arch/riscv64/CodeGen.zig
  src/print_zir.zig
  test/behavior.zig
  test/behavior/cast_int.zig
  test/behavior/decl_literals.zig
  test/behavior/struct.zig
  test/behavior/try.zig
  test/behavior/while.zig
  test/cases/compile_errors/cast_enum_literal_to_enum_but_it_doesnt_match.zig
  test/cases/compile_errors/comptime_arg_to_generic_fn_callee_error.zig
Labels: release notes

#21257 compiler: implement labeled switch/continue
  lib/std/zig/Ast.zig
  lib/std/zig/AstGen.zig
  lib/std/zig/Parse.zig
  lib/std/zig/Zir.zig
  lib/std/zig/render.zig
  src/Air.zig
  src/Air/types_resolved.zig
  src/Liveness.zig
  src/Liveness/Verify.zig
  src/Sema.zig
  src/Value.zig
  src/arch/aarch64/CodeGen.zig
  src/arch/arm/CodeGen.zig
  src/arch/riscv64/CodeGen.zig
  src/arch/sparc64/CodeGen.zig
  src/arch/wasm/CodeGen.zig
  src/arch/x86_64/CodeGen.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/codegen/llvm/Builder.zig
  src/codegen/llvm/ir.zig
  src/codegen/spirv.zig
  src/print_air.zig
  src/print_zir.zig
  test/behavior.zig
  test/behavior/switch.zig
  test/behavior/switch_loop.zig
  test/cases/compile_errors/duplicate-unused_labels.zig
Labels: release notes

#21386 std.Build: allow packages to expose arbitrary LazyPaths by name
  lib/std/Build.zig
Labels: zig build system, release notes

#21509 disallow non-scalar sentinel types
  lib/std/builtin.zig
  src/Sema.zig
  test/cases/compile_errors/array slice sentinel mismatch non-scalar.zig
  test/cases/safety/array slice sentinel mismatch non-scalar.zig
Labels: breaking, release notes

#21520 formalize the panic interface
  lib/compiler_rt/common.zig
  lib/std/Thread.zig
  lib/std/builtin.zig
  lib/std/debug.zig
  lib/std/debug/FormattedPanic.zig
  lib/std/debug/SimplePanic.zig
  lib/std/fmt.zig
  lib/std/time.zig
  src/Compilation.zig
  src/InternPool.zig
  src/Sema.zig
  src/Sema/bitcast.zig
  src/Type.zig
  src/Value.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
  src/codegen/llvm.zig
  src/crash_report.zig
  src/link/MachO.zig
  src/main.zig
  src/mutable_value.zig
  src/target.zig
  test/cases/exit.zig
Labels: release notes
