Repository ziglang/zig, pull requests merged in 2025-08, with the labels that each got.

#24649 std.Build.Watch: add macOS implementation based on FSEventStream
  lib/compiler/build_runner.zig
  lib/std/Build/Watch.zig
  lib/std/Build/Watch/FsEvents.zig
Labels: zig build system, release notes

#24699 remove RingBuffer; remove BoundedArray; use `@memmove`
  doc/langref/test_switch_dispatch_loop.zig
  lib/docs/wasm/markdown/Parser.zig
  lib/std/Io.zig
  lib/std/Io/DeprecatedReader.zig
  lib/std/Io/Reader/test.zig
  lib/std/Progress.zig
  lib/std/RingBuffer.zig
  lib/std/array_list.zig
  lib/std/base64.zig
  lib/std/bounded_array.zig
  lib/std/math/big/int.zig
  lib/std/os/windows.zig
  lib/std/std.zig
  src/Compilation.zig
  src/Sema.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
Labels: breaking, standard library, release notes

#24727 std/zip.zig: perform backslash-to-forward-slash before isBadFilename()
  lib/std/zip.zig
Labels: standard library

#24698 std: rework HTTP and TLS for new I/O API
  lib/compiler/resinator/cli.zig
  lib/compiler/resinator/compile.zig
  lib/compiler/resinator/cvtres.zig
  lib/compiler/resinator/errors.zig
  lib/compiler/resinator/ico.zig
  lib/compiler/resinator/main.zig
  lib/docs/wasm/markdown.zig
  lib/std/Build/Fuzz.zig
  lib/std/Build/WebServer.zig
  lib/std/Io.zig
  lib/std/Io/Reader.zig
  lib/std/Io/Writer.zig
  lib/std/Io/buffered_reader.zig
  lib/std/Io/limited_reader.zig
  lib/std/Io/test.zig
  lib/std/Uri.zig
  lib/std/crypto/tls.zig
  lib/std/crypto/tls/Client.zig
  lib/std/fifo.zig
  lib/std/fs/File.zig
  lib/std/http.zig
  lib/std/http/ChunkParser.zig
  lib/std/http/Client.zig
  lib/std/http/Server.zig
  lib/std/http/WebSocket.zig
  lib/std/http/protocol.zig
  lib/std/http/test.zig
  lib/std/net.zig
  lib/std/std.zig
  src/Package/Fetch.zig
  src/Package/Fetch/git.zig
Labels: breaking, standard library, release notes

#24743 std.Io: delete BufferedWriter
  lib/compiler/aro/aro/Driver.zig
  lib/compiler/aro/aro/Preprocessor.zig
  lib/compiler/aro/backend/Object/Elf.zig
  lib/compiler/libc.zig
  lib/compiler/resinator/compile.zig
  lib/compiler/resinator/cvtres.zig
  lib/compiler/resinator/main.zig
  lib/compiler/std-docs.zig
  lib/docs/wasm/markdown.zig
  lib/init/src/root.zig
  lib/std/Io.zig
  lib/std/Io/DeprecatedWriter.zig
  lib/std/Io/buffered_writer.zig
  lib/std/Io/test.zig
  lib/std/fmt.zig
  lib/std/zig/LibCInstallation.zig
  src/Package/Fetch.zig
  src/link/Lld.zig
  tools/docgen.zig
  tools/doctest.zig
  tools/gen_spirv_spec.zig
  tools/migrate_langref.zig
  tools/update_cpu_features.zig
  tools/update_crc_catalog.zig
Labels: breaking, standard library, release notes

#24702 Rewrite Linux syscalls generation
  lib/std/os/linux.zig
  lib/std/os/linux/syscalls.zig
  tools/generate_linux_syscalls.zig
Labels: ci-riscv64-linux

#22916 Adds non allocating alternatives to ZON parse functions
  lib/std/zon/parse.zig
Labels: breaking

#25034 std.compress: update lzma, lzma2, and xz to new I/O API
  lib/std/compress/lzma.zig
  lib/std/compress/lzma/decode.zig
  lib/std/compress/lzma/decode/lzbuffer.zig
  lib/std/compress/lzma/decode/rangecoder.zig
  lib/std/compress/lzma/test.zig
  lib/std/compress/lzma/vec2d.zig
  lib/std/compress/lzma2.zig
  lib/std/compress/lzma2/decode.zig
  lib/std/compress/xz.zig
  lib/std/compress/xz/Decompress.zig
  lib/std/compress/xz/block.zig
  lib/std/compress/xz/test.zig
  src/Package/Fetch.zig
Labels: breaking, standard library, release notes
