Repository ziglang/zig, pull requests merged in 2025-07, with the labels that each got.

#24146 Sema: Stop adding Windows implib link inputs for `extern "..."` syntax.
  build.zig
  src/Compilation.zig
  src/Sema.zig
  src/libs/mingw.zig
  src/main.zig
  test/standalone/simple/build.zig
  test/standalone/windows_argv/build.zig
  test/standalone/windows_bat_args/build.zig
  test/standalone/windows_spawn/build.zig
  test/tests.zig
Labels: breaking, release notes

#24505 update std.json and std.zon to new I/O API
  lib/compiler/resinator/main.zig
  lib/std/Build/Cache/Path.zig
  lib/std/Io/Reader.zig
  lib/std/json.zig
  lib/std/json/Scanner.zig
  lib/std/json/Stringify.zig
  lib/std/json/dynamic.zig
  lib/std/json/dynamic_test.zig
  lib/std/json/fmt.zig
  lib/std/json/hashmap_test.zig
  lib/std/json/scanner.zig
  lib/std/json/scanner_test.zig
  lib/std/json/static.zig
  lib/std/json/static_test.zig
  lib/std/json/stringify.zig
  lib/std/json/stringify_test.zig
  lib/std/json/test.zig
  lib/std/zig.zig
  lib/std/zig/Ast.zig
  lib/std/zon.zig
  lib/std/zon/Serializer.zig
  lib/std/zon/parse.zig
  lib/std/zon/stringify.zig
  src/main.zig
  src/print_env.zig
  src/print_targets.zig
  src/translate_c.zig
Labels: breaking, release notes

#24521 std.fs.File: delete writeFileAll and friends
  lib/compiler/build_runner.zig
  lib/compiler/objcopy.zig
  lib/std/Build/Step/Run.zig
  lib/std/c.zig
  lib/std/elf.zig
  lib/std/fs/AtomicFile.zig
  lib/std/fs/Dir.zig
  lib/std/fs/File.zig
  lib/std/fs/test.zig
  lib/std/json.zig
  lib/std/posix.zig
  src/Builtin.zig
  src/Compilation.zig
  src/fmt.zig
  src/link/MachO.zig
  src/main.zig
  test/incremental/fix_many_errors
  test/standalone/stack_iterator/build.zig
  tools/gen_stubs.zig
Labels: breaking, standard library, release notes

#24523 std.tar: update to new I/O API
  CMakeLists.txt
  lib/compiler/std-docs.zig
  lib/docs/wasm/main.zig
  lib/std/Build/Fuzz/WebServer.zig
  lib/std/Io.zig
  lib/std/Io/DeprecatedReader.zig
  lib/std/Io/DeprecatedWriter.zig
  lib/std/Io/Reader.zig
  lib/std/Io/buffered_atomic_file.zig
  lib/std/Io/c_writer.zig
  lib/std/Io/change_detection_stream.zig
  lib/std/Io/find_byte_writer.zig
  lib/std/Io/multi_writer.zig
  lib/std/Io/stream_source.zig
  lib/std/crypto/md5.zig
  lib/std/tar.zig
  lib/std/tar/Writer.zig
  lib/std/tar/test.zig
  lib/std/tar/writer.zig
  src/Compilation.zig
  src/Package/Fetch.zig
Labels: breaking, standard library, release notes

#24559 std: rework zstd for new I/O API
  lib/std/Io/DeprecatedReader.zig
  lib/std/Io/Reader.zig
  lib/std/Io/Writer.zig
  lib/std/compress.zig
  lib/std/compress/xz.zig
  lib/std/compress/xz/block.zig
  lib/std/compress/zstandard.zig
  lib/std/compress/zstandard/decode/block.zig
  lib/std/compress/zstandard/decode/fse.zig
  lib/std/compress/zstandard/decode/huffman.zig
  lib/std/compress/zstandard/decompress.zig
  lib/std/compress/zstandard/readers.zig
  lib/std/compress/zstandard/types.zig
  lib/std/compress/zstd.zig
  lib/std/compress/zstd/Decompress.zig
  lib/std/fs/File.zig
  lib/std/http/Server.zig
  lib/std/posix.zig
  src/Package/Fetch.zig
  src/Package/Fetch/git.zig
Labels: standard library, release notes

#24564 std.Progress: support progress bar escape codes
  lib/compiler/build_runner.zig
  lib/std/Progress.zig
Labels: release notes

#22587 std.Build: Deprecate `Step.Compile` APIs that mutate the root module
  doc/langref/build.zig
  doc/langref/build_c.zig
  doc/langref/build_object.zig
  lib/std/Build/Step/Compile.zig
  test/link/elf.zig
  test/link/link.zig
  test/link/macho.zig
  test/link/wasm/extern/build.zig
  test/src/Cases.zig
  test/src/RunTranslatedC.zig
  test/standalone/c_embed_path/build.zig
  test/standalone/extern/build.zig
  test/standalone/issue_794/build.zig
  test/standalone/stack_iterator/build.zig
  test/tests.zig
Labels: release notes
