Repository ziglang/zig, pull requests merged in 2025-09, with the labels that each got.

#25147 Reenable failing vector tests
  lib/std/fmt.zig
  lib/std/simd.zig
  test/behavior/vector.zig
Labels: ci-riscv64-linux

#25186 frontend: vectors and arrays no longer support in-memory coercion
  doc/langref.html.in
  doc/langref/test_vector.zig
  lib/std/debug.zig
  lib/std/mem.zig
  src/Sema.zig
  test/behavior/cast.zig
  test/behavior/union.zig
  test/behavior/vector.zig
  test/cases/compile_errors/in_memory_coerce_vector_to_array.zig
Labels: breaking, release notes

#25249 std.crypto: add AES-SIV and AES-GCM-SIV
  lib/std/crypto.zig
  lib/std/crypto/aes.zig
  lib/std/crypto/aes_gcm_siv.zig
  lib/std/crypto/aes_siv.zig
  lib/std/crypto/modes.zig
Labels: release notes

#25260 std.fmt: migrate bufPrintZ to bufPrintSentinel
  lib/std/fmt.zig
  lib/std/fs.zig
  lib/std/meta.zig
  lib/std/os.zig
  lib/std/posix.zig
  lib/std/process/Child.zig
Labels: breaking, standard library, release notes

#25298 std: delete SegmentedList again
  lib/std/segmented_list.zig
  lib/std/std.zig
  test/src/Debugger.zig
  tools/lldb_pretty_printers.py
  tools/update_cpu_features.zig
Labels: breaking, standard library, release notes

#25351 std.mem: introduce cut functions; rename "index of" to "find"
  lib/std/mem.zig
  src/main.zig
Labels: standard library, release notes
