Repository ziglang/zig, pull requests merged in 2025-02, with the labels that each got.

#22683 debug: fix MemoryAccessor file leak
  lib/std/debug.zig
  lib/std/debug/MemoryAccessor.zig
Labels: os-linux, arch-aarch64

#22707 compiler: do not propagate result type to `try` operand
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Sema.zig
  src/print_zir.zig
  test/behavior/try.zig
  test/cases/compile_errors/redundant_try.zig
Labels: breaking

#22713 openbsd: fix stage3 link
  build.zig
  lib/std/Target.zig
Labels: os-openbsd

#22722 std.MultiArrayList: popOrNull() -> pop() [v2]
  lib/std/multi_array_list.zig
Labels: breaking, release notes

#22721 std.ArrayHashMap: popOrNul() -> pop() [v2]
  lib/std/Build/Cache.zig
  lib/std/array_hash_map.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
  src/codegen/c.zig
  src/link/Coff.zig
Labels: breaking, standard library, release notes

#22808 introduce std.heap.SmpAllocator
  bootstrap.c
  build.zig
  lib/libc/musl/src/thread/riscv32/clone.s
  lib/libc/musl/src/thread/riscv64/clone.s
  lib/std/heap.zig
  lib/std/heap/PageAllocator.zig
  lib/std/heap/SmpAllocator.zig
  lib/std/heap/WasmAllocator.zig
  lib/std/heap/debug_allocator.zig
  src/main.zig
  stage1/config.zig.in
Labels: release notes

#22862 fuzzer: write inputs to shared memory before running
  lib/compiler/test_runner.zig
  lib/fuzzer.zig
  lib/init/src/main.zig
  lib/std/testing.zig
  lib/std/zig/tokenizer.zig
  src/zig_llvm.cpp
Labels: release notes

#22922 crypto.auth.Aegis128X*Mac: properly absorb tags in the first lane
  lib/std/crypto/aegis.zig
Labels: standard library

#22792 crypto.pwhash.bcrypt: make silently_truncate_password a member of Params
  lib/std/crypto/bcrypt.zig
  lib/std/crypto/benchmark.zig
Labels: breaking, standard library

#22659 link: fix ambiguous names in linker scripts
  src/link.zig
  test/link/elf.zig
Labels: linking, regression

#22714 langref improvements
  doc/langref.html.in
  doc/langref/TopLevelFields.zig
  doc/langref/entry_point.zig
  doc/langref/libc_export_entry_point.zig
  doc/langref/panic_handler.zig
  doc/langref/std_options.zig
  doc/langref/test_illegal_behavior.zig
  doc/langref/test_setRuntimeSafety_builtin.zig
Labels: docs

#22795 std.Build: Allow ConfigHeader values to be added outside of comptime
  lib/std/Build/Step/ConfigHeader.zig
Labels: zig build system, release notes

#22706 Sema: allow `@ptrCast` of slices changing the length
  lib/std/debug.zig
  lib/std/debug/no_panic.zig
  lib/std/debug/simple_panic.zig
  src/Sema.zig
  src/Zcu.zig
  test/behavior/ptrcast.zig
  test/cases/compile_errors/slice_cast_change_len.zig
  test/cases/safety/slice_cast_change_len_0.zig
  test/cases/safety/slice_cast_change_len_1.zig
  test/cases/safety/slice_cast_change_len_2.zig
  test/incremental/change_panic_handler_explicit
Labels: release notes

#22154 compiler: Implement `@disableIntrinsics()` builtin function.
  lib/std/zig/AstGen.zig
  lib/std/zig/AstRlAnnotate.zig
  lib/std/zig/BuiltinFn.zig
  lib/std/zig/Zir.zig
  lib/zig.h
  src/InternPool.zig
  src/Sema.zig
  src/codegen/c.zig
  src/codegen/llvm.zig
  src/print_zir.zig
Labels: proposal

#22488 implement a ubsan runtime for better error messages
  lib/std/Build/Step/Compile.zig
  lib/std/heap.zig
  lib/std/mem.zig
  lib/ubsan_rt.zig
  src/Compilation.zig
  src/Compilation/Config.zig
  src/Zcu.zig
  src/link.zig
  src/link/Coff.zig
  src/link/Elf.zig
  src/link/MachO.zig
  src/link/MachO/relocatable.zig
  src/link/Wasm.zig
  src/main.zig
  test/link/elf.zig
  test/link/glibc_compat/build.zig
  test/link/wasm/export-data/build.zig
  test/link/wasm/export/build.zig
  test/link/wasm/function-table/build.zig
  test/link/wasm/shared-memory/build.zig
  test/link/wasm/type/build.zig
  test/src/StackTrace.zig
  tools/incr-check.zig
Labels: release notes

#22994 implement new package hash format: `$name-$semver-$hash`
  build.zig.zon
  doc/build.zig.zon.md
  lib/init/build.zig
  lib/init/build.zig.zon
  lib/init/src/main.zig
  lib/std/array_list.zig
  src/Package.zig
  src/Package/Fetch.zig
  src/Package/Manifest.zig
  src/main.zig
Labels: breaking, release notes
