Repository ziglang/zig, pull requests merged in 2025-01, with the labels that each got.

#22370 Remove strict verifyContext invocation from hash_map implementation.
  lib/std/hash_map.zig
Labels: breaking, standard library, release notes

#22456 bsd: fix stage3 linking on freebsd and dragonfly
  src/target.zig
Labels: os-freebsd, os-dragonfly, regression

#22414 Sema: rewrite semantic analysis of function calls
  build.zig
  lib/compiler/aro_translate_c.zig
  lib/std/math/log_int.zig
  lib/std/os/windows.zig
  lib/std/zig.zig
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Sema.zig
  src/Zcu.zig
  src/translate_c.zig
  test/behavior/eval.zig
  test/behavior/generics.zig
  test/behavior/struct.zig
  test/behavior/typename.zig
  test/cases/compile_errors/arg_to_non_comptime_param_with_comptime_only_type_is_not_evaluated_at_comptime.zig
  test/cases/compile_errors/bad_usage_of_call.zig
  test/cases/compile_errors/comptime_call_of_function_pointer.zig
  test/cases/compile_errors/condition_comptime_reason_explained.zig
  test/cases/compile_errors/dereference_anyopaque.zig
  test/cases/compile_errors/explain_why_fn_is_called_at_comptime.zig
  test/cases/compile_errors/explain_why_generic_fn_is_called_at_comptime.zig
  test/cases/compile_errors/generic_function_instance_with_non-constant_expression.zig
  test/cases/compile_errors/generic_function_instantiation_inherits_parent_branch_quota.zig
  test/cases/compile_errors/generic_instantiation_failure_in_generic_function_return_type.zig
  test/cases/compile_errors/generic_method_call_with_invalid_param.zig
  test/cases/compile_errors/global_variable_initializer_must_be_constant_expression.zig
  test/cases/compile_errors/inline_call_runtime_value_to_comptime_param.zig
  test/cases/compile_errors/invalid_extern_function_call.zig
  test/cases/compile_errors/invalid_pointer_for_var_type.zig
  test/cases/compile_errors/nested_generic_function_param_type_mismatch.zig
  test/cases/compile_errors/never_inline_call_of_inline_fn_with_comptime_param.zig
  test/cases/compile_errors/non-const_expression_in_struct_literal_outside_function.zig
  test/cases/compile_errors/non_comptime_param_in_comptime_function.zig
  test/cases/compile_errors/recursive_inline_fn.zig
  test/cases/compile_errors/runtime_operation_in_comptime_scope.zig
  test/compile_errors.zig
  test/standalone/simple/std_enums_big_enums.zig
Labels: breaking, release notes

#22425 compiler: improve "... contains reference to comptime var" errors
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Sema.zig
  src/Value.zig
  src/Zcu/PerThread.zig
  src/print_value.zig
  src/print_zir.zig
  test/cases/compile_errors/compile_log_a_pointer_to_an_opaque_value.zig
  test/cases/compile_errors/comptime_var_referenced_at_runtime.zig
  test/cases/compile_errors/comptime_var_referenced_by_decl.zig
  test/cases/compile_errors/comptime_var_referenced_by_type.zig
  test/cases/comptime_aggregate_print.zig
Labels: release notes

#22548 (Hopefully) fix `error.BrokenPipe` failures
  lib/std/Build.zig
  lib/std/Build/Step/Compile.zig
  lib/std/Build/Step/Run.zig
  lib/std/process/Child.zig
  test/standalone/test_runner_module_imports/build.zig
  test/standalone/test_runner_path/build.zig
Labels: breaking, release notes

#22547 compiler: simplify generic functions, fix issues with inline calls
  lib/std/zig/AstGen.zig
  lib/std/zig/Zir.zig
  src/Air.zig
  src/Air/types_resolved.zig
  src/InternPool.zig
  src/Sema.zig
  src/Type.zig
  src/Value.zig
  src/Zcu.zig
  src/Zcu/PerThread.zig
  src/arch/wasm/CodeGen.zig
  src/codegen.zig
  src/codegen/c.zig
  src/codegen/c/Type.zig
  src/codegen/llvm.zig
  src/codegen/spirv.zig
  src/print_value.zig
  src/print_zir.zig
  test/behavior/fn.zig
  test/cases/compile_errors/anytype_param_requires_comptime.zig
  test/cases/compile_errors/bogus_method_call_on_slice.zig
  test/cases/compile_errors/coerce_anon_struct.zig
  test/cases/compile_errors/non-comptime-parameter-used-as-array-size.zig
Labels: breaking

#18912 optimized memcpy
  lib/compiler_rt.zig
  lib/compiler_rt/memcpy.zig
  lib/compiler_rt/memmove.zig
Labels: release notes

#22554 std.Build: add `addLibrary` function
  lib/init/build.zig
  lib/std/Build.zig
  test/behavior/x86_64/build.zig
  test/link/common_symbols/build.zig
  test/link/common_symbols_alignment/build.zig
  test/link/interdependent_static_c_libs/build.zig
  test/link/link.zig
  test/link/static_libs_from_object_files/build.zig
  test/src/Cases.zig
  test/standalone/coff_dwarf/build.zig
  test/standalone/dep_duplicate_module/build.zig
  test/standalone/extern/build.zig
  test/standalone/global_linkage/build.zig
  test/standalone/install_headers/build.zig
  test/standalone/load_dynamic_library/build.zig
  test/standalone/shared_library/build.zig
  test/standalone/stack_iterator/build.zig
  test/standalone/static_c_lib/build.zig
  test/standalone/windows_argv/build.zig
Labels: zig build system, release notes

#22572 compiler: include error trace in all functions, implement for x86_64 backend
  lib/std/builtin.zig
  src/InternPool.zig
  src/Sema.zig
  src/Zcu/PerThread.zig
  src/arch/x86_64/CodeGen.zig
  src/codegen/llvm.zig
  src/target.zig
  stage1/zig1.wasm
  test/cases/compile_errors/anytype_param_requires_comptime.zig
  test/cases/compile_errors/bogus_method_call_on_slice.zig
  test/cases/compile_errors/coerce_anon_struct.zig
  test/cases/compile_errors/implicit_cast_of_error_set_not_a_subset.zig
Labels: release notes

#22631 Sema: `@memcpy` changes
  src/Sema.zig
  src/Type.zig
  src/Value.zig
  test/cases/compile_errors/memcpy_alias.zig
  test/cases/compile_errors/memcpy_bad_type.zig
Labels: breaking, release notes

#22653 std: fix comptime SemanticVersion expr regression
  lib/std/os/windows.zig
  lib/std/posix.zig
Labels: os-windows, os-freebsd, regression

#22668 delete std.heap.WasmPageAllocator
  lib/std/heap.zig
  lib/std/heap/WasmAllocator.zig
  lib/std/heap/WasmPageAllocator.zig
  lib/std/heap/general_purpose_allocator.zig
Labels: breaking, standard library
